### ISSUE TITLE
Sidebery-like features

### ISSUE THREAD

**Issue by Marin-Kitagawa** [zen-browser/desktop#378] opened 2024-08-21 12:35 UTC
### What feature would you like to see?

Zen Browser is just wonderful. I love it so much. First, I know that there is already an issue (#114) with a similar name. I want to add more

1. Now, for switching workspaces, I have to click on the workspaces button and then switch the workspace. But in Sidebery, I can have the workspaces (Panels) vertically and switch the panels with ease.
2. Expandable tabs with custom width on hover
3. Manual and automatic tab unloading
4. Clearing cookies
5. Tree-like tabs and tree-like tab groups (as folders with custom icons). (Custom icon for folders is not available in Sidebery, but it'd be a good addition)
6. Custom icons (any image file of any type (in decreasing order of preference): SVG, PNG, JPG, etc.)
7. Reopening in a new container must discard the original tab and then open it in the new container. But now, it duplicates the tab and opens the duplicated tab in the chosen container.

Note: I use this browser both on Windows and Linux (NixOS). So, the platform chosen here is not the only one on which the above features are being requested.

### What platform are you seeing the problem on?

Linux

**Comment by mauro-balades** [comment] 2024-08-21 19:10
We are looking into this, im going to close it as this is a duplicate of other "smaller" issues, thanks!

**Closed by mauro-balades** 2024-08-21 19:10 UTC
Labels: kind: enhancement

**Comment by guigirl42** [comment] 2024-11-18 06:53
https://github.com/zen-browser/desktop/discussions/891#discussioncomment-11288211
