### ISSUE TITLE
GPU hardware acceleration off by default

### ISSUE THREAD

**Issue by Myouboku** [zen-browser/desktop#1012] opened 2024-08-28 16:59 UTC
### What happened?

By using recommanded settings, GPU hardware acceleration is off by default, that might be the source of a lot of performance issues with this browser.
Enabling it manually on my end fixed the video stuttering problem while playing multiple media.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.32

### Severity impact

Medium

### What platform are you seeing the problem on?

Windows

**Comment by umarhamzy** [comment] 2024-08-29 06:05
How do you enable this? 
Uncheck recommended performance settings and enable hardware acceleration?

**Comment by Myouboku** [comment] 2024-08-29 09:02
> How do you enable this? 
> Uncheck recommended performance settings and enable hardware acceleration?

Exactly

**Comment by HarryHeres** [comment] 2024-08-29 18:15
@mauro-balades This could be solved by setting the following preferences:
- defaultPerformanceSettings => disabled
- layers.acceleration => enabled

Snippet from the browser (`browser/components/preferences/main.js:2323`): 
<img width="613" alt="image" src="https://github.com/user-attachments/assets/ba852f4d-bb47-4c7e-9f6f-d3d96b866afa">

**Comment by mauro-balades** [comment] 2024-08-29 18:34
so...

```
layers.acceleration.disabled=false
browser.preferences.defaultPerformanceSettings.enabled=false
```
?

**Comment by mauro-balades** [comment] 2024-08-29 19:08
What would your implementation do exactly? To void you having to do extra work haha

**Comment by mauro-balades** [comment] 2024-08-29 19:18
It would be great if you could test it build it and test it out, otherwise, ill just add the changes I proposed

**Comment by HarryHeres** [comment] 2024-08-29 19:19
> It would be great if you could test it build it and test it out, otherwise, ill just add the changes I proposed

I'm testing it right now. Should I then just open a PR with a patch?

**Comment by mauro-balades** [comment] 2024-08-29 19:24
That would be great!

**Comment by Myouboku** [comment] 2024-08-29 19:50
Well... that's weird but after updating my AMD GPU driver, the issue seems to be solved so it might not be related to the browser, still strange that the base Firefox browser wasn't impacted.

I don't know if there is anything to solve, have you been able to reproduce the problem on your end ?

**Comment by HarryHeres** [comment] 2024-08-29 20:44
@mauro-balades Well then, do we want to enable the acceleration by default or do we want to keep it on "Recommended settings" and let Firefox decide?

**Comment by mauro-balades** [comment] 2024-08-29 21:19
What does it work best for you?

**Comment by HarryHeres** [comment] 2024-08-29 21:21
Tbh, I would leave it as-is and if we run into a similar problem in future, we could talk about some changes to the defaults. Therefore let's close it for now?

**Comment by mauro-balades** [comment] 2024-08-29 21:33
Should we enable `layers.acceleration` by default though?

**Comment by HarryHeres** [comment] 2024-08-29 21:46
> Should we enable `layers.acceleration` by default though?

There's no need for us to do that anymore as Firefox automatically enables it under the hood if it can find hardware capable of hardware rendering. 

I wanted to enable it by default despite the "recommended" default settings as I initially thought that there's a bug in Firefox that prevents some users to enable the hardware acceleration despite having a compatible hardware. As it turned out, it was an AMD driver installation issue, which was resolved by reinstalling the drivers. 

If we were to manually force the hardware acceleration on incompatible hardware, it could lead to some unexpected behaviour. Due to that, I would let Firefox decide, at least for now.

**Comment by Myouboku** [comment] 2024-08-29 21:58
To be clear, it might not be related to AMD either, I assumed that based on what I experienced but I still have no confirmation.

That said, I agree it would be better to let Firefox handle the default settings, if a similar problem appears a new issue will be opened

**Comment by mauro-balades** [comment] 2024-08-29 22:06
Should I close it then? It's a bummer, I thought we found some sort of speed improvement but not :(

**Comment by HarryHeres** [comment] 2024-08-29 22:08
> Should I close it then? It's a bummer, I thought we found some sort of speed improvement but not :(

Yup, I would close for the time being. It seemed promising indeed.

**Closed** 2024-08-29 22:11 UTC
Labels: kind: medium severity
