### ISSUE TITLE
`null` in toolbar won't disappear

### ISSUE THREAD

**Issue by skeithtan** [zen-browser/desktop#3337] opened 2024-12-01 21:07 UTC
### Captchas

- [ ] I have read the instructions.
- [ ] I have searched existing issues and avoided creating duplicates.
- [x] I am not filing an enhancement request.

### What happened?

I force quit the browser and reopened it but now there's a `null` in the toolbar and it does not disappear. Resetting the toolbar makes it worse. 

https://github.com/user-attachments/assets/48e1f0b7-1a6e-4342-a0b6-58da2af02d2c

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.22 (Firefox 132.0.1) (aarch64)

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by irmoodie** [comment] 2024-12-02 09:38
Most likely related, the two-way arrow button (⇄) to minimize/expand the vertical tab bar is no longer present (same Zen version and platform as op).

**Comment by LogFlames** [comment] 2024-12-03 11:12
Will also add, when I change the compact mode settings (hide sidebar, hide toolbar, hide both) more nulls are added.
<img width="333" alt="Screenshot 2024-12-03 at 12 12 09" src="https://github.com/user-attachments/assets/f072e226-ecc1-4778-be92-1f879eb8c5bb">

**Comment by TJdhyani** [comment] 2024-12-05 20:19
Facing the same issue

**Comment by allywilson** [comment] 2024-12-08 08:46
Had the same issue. Forced quit in macos. Then the null appeared in the top left and I couldn't minimise the vertical tabs bar. There was an update though, and that has fixed it.

**Comment by mr-cheffy** [comment] 2024-12-08 10:49
Does this still happen in the latest twilight?

**Comment by adityasz** [comment] 2024-12-08 19:02
@mr-cheff Yes. Can't resize the sidebar either. Enabling compact mode (with the single toolbar layout) or opening "Customize Toolbar..." adds a `null` to the toolbar every time.

Build ID: 20241208105113 (latest `zen-specific.AppImage`, new profile)
GNOME Wayland

**Comment by Nicolas1203** [comment] 2024-12-09 00:03
Weirdly enough restarting my computer fixed the issue.

zen verison: 1.0.1-a.22 (Firefox 132.0.1) (aarch64)
MacOS Sonoma Version 14.5 (23F79)

**Comment by adityasz** [comment] 2024-12-09 04:22
The issue is still there on build 20241209010650 (version 1.0.2-t.0, new profile). The sidebar can be resized now, but the `null`s still appear on entering compact mode or "Customize Toolbar...".

**Comment by Naezr** [comment] 2024-12-09 08:59
Same issue on Fedora 40 with the window control buttons on the left side enabled. `1.0.2-t.0 (Firefox 133.0) (2024-12-09) (64-bit)`

![image](https://github.com/user-attachments/assets/1f746f0b-709c-40da-9806-8da97efb54e0)

**Comment by kaido2ki** [comment] 2024-12-12 04:54
it seems to be fixed in `1.0.2-b.1`

**Closed as completed** 2024-12-12 08:26 UTC
Labels: Bug
