### ISSUE TITLE
Unloading Tabs

### ISSUE THREAD

**Issue by justingallant1988** [zen-browser/desktop#2672] opened 2024-11-05 17:40 UTC
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

If I enable tab unloader, and unload a tab, it becomes inaccessible/frozen. I need to restart the browser to fix.

If I disable tab unloader, the issue is gone because I have no longer have any option to unload pinned tabs I do not want open.

I have been advised this is fixed multiple times and just want to report that it currently is not. 

I am on the latest version 1.0.1-a.17 

https://github.com/user-attachments/assets/8dd68902-983a-4b48-a51a-c79d942a73ac

### Reproducible?

- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.17

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by CptnFizzbin** [comment] 2024-11-05 17:59
I was seeing the same issue, and just did a reinstall via the installer. I'm now not able to reproduce the issue.

**Comment by omarkily** [comment] 2024-11-06 04:36
I'm facing the same issue #2652

**Comment by RayZ3R0** [comment] 2024-11-07 06:57
Duplicate of #2652 please move there

**Closed as completed by RayZ3R0** 2024-11-07 06:57 UTC
Labels: Bug
