### ISSUE TITLE
Flatpak install script can't find the repo

### ISSUE THREAD

**Issue by tagliateo** [zen-browser/desktop#121] opened 2024-07-31 22:35 UTC
### What happened?

tried installing via flatpak using install script provided, returns : 
`error: Nothing matches io.github.zen_browser.zen in remote flathub
`
![image](https://github.com/user-attachments/assets/4270c2c3-99d9-4b78-8d9a-9a7b42629ddd)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.8

### Severity impact

Medium, High

### What platform are you seeing the problem on?

Linux

**Comment by mauro-balades** [comment] 2024-07-31 22:38
Duplicate of #106

**Closed** 2024-07-31 22:39 UTC
Labels: bug, kind: medium severity, kind: high severity
