### ISSUE TITLE
4k Display Issue

### ISSUE THREAD

**Issue by barryzhao823** [zen-browser/desktop#2409] opened 2024-10-30 02:37 UTC
### Captchas

- [ ] I have read the instructions.
- [ ] I have searched existing issues and avoided creating duplicates.
- [ ] I am not filing an enhancement request.

### What happened?

"I encountered an issue where the font rendering is blurry on a 4K display in full screen."

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

latest

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by ralphsun73221** [comment] 2024-10-30 02:42
This issue is very similar to [issue](https://github.com/zen-browser/desktop/issues/1276). It was fixed for a while before a14, but for some unknown reason, it has reappeared in this version.

**Comment by RayZ3R0** [comment] 2024-10-30 05:37
This is a duplicate of #2375 where this issue is already being addressed. Please follow the discussion there.

**Closed as completed by RayZ3R0** 2024-10-30 05:37 UTC
Labels: Bug
