### ISSUE TITLE
Page scaling

### ISSUE THREAD

**Issue by arybek** [zen-browser/desktop#3782] opened 2024-12-15 10:59 UTC
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

![SCR-20241215-kthh](https://github.com/user-attachments/assets/e36ecc98-3392-4263-9bf4-19c635a51c70)e, page scaling in ‘collapsed toolbar’ mode is not working correctly. On the right side, part of the page is cut off that should be visible.
<img width="1256" alt="SCR-20241215-kuss" src="https://github.com/user-attachments/assets/3fdec40f-efc5-46ea-a724-d2a3cfd9722b" />

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.2

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by chriskirknielsen** [comment] 2024-12-15 18:24
Probably a duplicate of #3678

**Comment by djorium** [comment] 2024-12-15 23:15
Duplicate of https://github.com/zen-browser/desktop/issues/3678

**Closed as completed by djorium** 2024-12-15 23:15 UTC
Labels: Bug
