### ISSUE TITLE
Discord tab crashes when calling someone

### ISSUE THREAD

**Issue by cilginc** [zen-browser/desktop#1800] opened 2024-09-29 18:26 UTC
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I use Flatpak+Wayland version of Zen Browser. When someone accetps the call I got crash in discord tab. When I reload it's crashing againg and again until call ends. I think it's a pipewire problem but I don't really know why this is happening. I also tested tested firefox and chromium, but only zen browser had this error.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.5 

### What platform are you seeing the problem on?

Linux

**Comment by jasinco** [comment] 2024-10-11 06:56
I do have the same problem. Is there any solution right now?

**Comment by cilginc** [comment] 2024-10-11 16:27
> I do have the same problem. Is there any solution right now?

I updated and checked again but It's still happening to me. Are you using flatpak version too? Have you tried aur version? I haven't tried yet but I still think it's pipewire issue.

**Comment by eduardo-pinheiro** [comment] 2024-11-01 14:14
I'm passing for some issue now, when I need to enter a discord voice conversation, in private calls or voice channels, I just open Firefox when I need to open a call on discord.
I found some links related to these problems, maybe help at discovery.
https://www.reddit.com/r/zen_browser/comments/1fhkqds/discord_web_crushing/
https://github.com/NixOS/nixpkgs/issues/332540

**Comment by Skaereth** [comment] 2024-11-10 22:04
I tried with the latest version of Zen (1.0.1-a.19), the issue is still present (flatpak on NixOS / Kde Wayland session).

When you connect to an empty audio room (server or direct call), no crash. But if anyone is already present or join the call / room, the tab crashes immediately.
You can also generate this crash when testing the mic in the audio/video preferences.
The issue is related to audio out, not mic in since the mic level is correctly recognized, both in audio/video preference tab or in an empty audio room.
I also tried to switch between jack and pulseaudio (both through pipewire), but the issue persists, no changes in discord audio settings seem to solve the issue.

**Comment by kossLAN** [comment] 2024-11-14 20:24
> I tried with the latest version of Zen (1.0.1-a.19), the issue is still present (flatpak on NixOS / Kde Wayland session).
> 
> When you connect to an empty audio room (server or direct call), no crash. But if anyone is already present or join the call / room, the tab crashes immediately. You can also generate this crash when testing the mic in the audio/video preferences. The issue is related to audio out, not mic in since the mic level is correctly recognized, both in audio/video preference tab or in an empty audio room. I also tried to switch between jack and pulseaudio (both through pipewire), but the issue persists, no changes in discord audio settings seem to solve the issue.

This follows my exact experiences, even with various different flake packaging of zen on NixOS and different variations of firefox packaging/branches they all crash in the same way, except the prebuilt binary firefox packages in nixpkgs (firefox-bin), Still don't think this issue belongs here, but I couldn't find it on bugzilla, and the only discussion I see on this issue is nixpkgs and here.

**Comment by Crinax** [comment] 2024-12-03 06:40
I have same problem too, but I use EndeavourOS with Hyprland and zen-browser-bin from aur

> I tried with the latest version of Zen (1.0.1-a.19), the issue is still present (flatpak on NixOS / Kde Wayland session).
> 
> When you connect to an empty audio room (server or direct call), no crash. But if anyone is already present or join the call / room, the tab crashes immediately. You can also generate this crash when testing the mic in the audio/video preferences. The issue is related to audio out, not mic in since the mic level is correctly recognized, both in audio/video preference tab or in an empty audio room. I also tried to switch between jack and pulseaudio (both through pipewire), but the issue persists, no changes in discord audio settings seem to solve the issue.

**Comment by ChristopherEverett** [comment] 2024-12-06 15:11
I too am facing the same issue.
OS: Arch
Zen version: zen-browser-bin (aur) 1.0.1.a.22-1

**Comment by cuffld** [comment] 2024-12-08 12:54
Facing same issue on Artix with firefox

**Comment by oldregime** [comment] 2024-12-08 16:26
I’m also experiencing the same issue on a Wayland session with Zen Browser. The crash only occurs when someone joins an ongoing call, but it works fine in an empty room. I’ve tried different audio settings and switching between PulseAudio and Jack, but the problem persists. It seems related to the audio output handling. Any updates on this?

**Comment by artysan-code** [comment] 2024-12-12 20:25
Same problem on an Arch Machine with Wayland, I used the package from AUR and still doesn't work.

**Comment by RobotoSkunk** [comment] 2024-12-15 07:44
This problem does not happen on Fedora 41 since 1.0.2-b.0 (Firefox 133.0)

**Comment by salamijason** [comment] 2024-12-15 09:17
Dupe of this https://github.com/zen-browser/desktop/issues/394

closing this post

**Closed by salamijason** 2024-12-15 09:17 UTC

**Comment by Barmanji** [comment] 2025-01-12 08:27
I thought i am the only one with the crash. I used zen in XORG and WAYLAND both, and this issue persist in both.
