### ISSUE TITLE
Tab crashes immediatly after i join a room on discord

### ISSUE THREAD

**Issue by fe2-Nyxar** [zen-browser/desktop#1412] opened 2024-09-13 02:17 UTC
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

![image](https://github.com/user-attachments/assets/f21abf2e-1024-4611-867f-6cf09cd252a4)

### Reproducible?

- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

Mozilla Zen 1.0.0-a.37

### What platform are you seeing the problem on?

Linux

### Relevant log output

```shell
[Parent 55751, IPC I/O Parent] WARNING: process 63585 exited on signal 11: file /home/runner/work/desktop/desktop/engine/ipc/chromium/src/base/process_util_posix.cc:335
```

**Comment by mauro-balades** [comment] 2024-09-13 08:29
Does it still happen in the latest version? (39)

**Comment by fe2-Nyxar** [comment] 2024-09-13 15:50
I guess

**Comment by mauro-balades** [comment] 2024-09-14 07:01
Is that all the output you had available?

**Comment by LightJack05** [comment] 2024-09-14 16:02
Reproduced it in a different website.
Same issue seems to be this one: #394 
This seems to be related to simultaneous mic usage and audio playback in a tab.

I used a random mic testing website to check it: https://webcammictest.com/check-mic.html

To reproduce just start a test, allow mic in the browser and click on the "Hear yourself" button (and possibly make some noise). The tab should crash.

Doesn't happen in standard Firefox.

**Comment by LightJack05** [comment] 2024-09-14 16:55
Update: Just built the browser from source, it works with the built from main.

**Comment by fe2-Nyxar** [comment] 2024-09-14 20:40
> To reproduce just start a test, allow mic in the browser and click on the "Hear yourself" button (and possibly make some noise). The tab should crash.

surprisingly the tab didn't crash, this issue is only present on discord

**Comment by fe2-Nyxar** [comment] 2024-09-14 20:42
> Update: Just built the browser from source, it works with the built from main.

try it on discord, maybe it's only me

**Comment by fe2-Nyxar** [comment] 2024-09-14 20:43
> Is that all the output you had available?

is there a log file that I can look into?

**Comment by LightJack05** [comment] 2024-09-14 22:35
> try it on discord, maybe it's only me

Discord also works on main. Given the fact that the last release is 5 days old, the patch might just not be in the build yet.
You could try to build it from source yourself. It might also just be that my build environment is different, I could try building at the point in time of the last release to reproduce the issue with my build environment.

**Comment by fe2-Nyxar** [comment] 2024-09-15 17:41
> Discord also works on main. Given the fact that the last release is 5 days old, the patch might just not be in the build yet. You could try to build it from source yourself.

I wish bro, I don't have enough ram :' (

**Comment by fe2-Nyxar** [comment] 2024-09-20 14:59
> > try it on discord, maybe it's only me
> 
> Discord also works on main. Given the fact that the last release is 5 days old, the patch might just not be in the build yet. You could try to build it from source yourself. It might also just be that my build environment is different, I could try building at the point in time of the last release to reproduce the issue with my build environment.

i got this popup while using discord 
![Screenshot_20240920_155544](https://github.com/user-attachments/assets/c150a0ed-1848-47ba-bce2-613e2128e1b1)

the site: https://support.mozilla.org/en-US/kb/speechd-setup?as=u&utm_source=inproduct

**Comment by m2x07** [comment] 2024-10-04 11:26
> Still happens on 1.0.1-a.3, Arch Linux.

also remains on 1.0.1-a.7, Arch Linux with flatpak using wayland

**Comment by nerfed** [comment] 2024-10-06 02:04
As long as I don't click accept or block on the firefox "Allow discord.com to use your microphone" popup I don't crash. So I can be in the call and listen but not talk.

**Comment by LightJack05** [comment] 2024-10-10 21:45
Also still happens for me in the prebuilt binaries... Still not when compiled from source... Now, compiling from source is kinda of impractical when not automated...

This is all the debug output I get in the console:
```
[Parent 161215, IPC I/O Parent] WARNING: process 161472 exited on signal 11: file /home/runner/work/desktop/desktop/engine/ipc/chromium/src/base/process_util_posix.cc:335
```
I got a core dump:

<details><summary>Coredumpctl output</summary>
<p>
```
           PID: 162845 (Isolated Web Co)
           UID: 1000 (LightJack05)
           GID: 1000 (LightJack05)
        Signal: 11 (SEGV)
     Timestamp: Thu 2024-10-10 23:34:47 CEST (3min 46s ago)
  Command Line: /opt/zen-browser-bin/zen-bin -contentproc -childID 3 -isForBrowser -prefsLen 35051 -prefMapSize 258693 -jsInitLen 234840 -parentBuildID 20240930160037 -greomni /opt/zen-browser-bin/omni.ja -appomni /opt/zen-browser-bin/browser/omni.ja -appDir /opt/zen-browser-bin/browser {bf614b77-b3ce-4ee9-949a-f2b0a43b2bef} 162605 tab
    Executable: /opt/zen-browser-bin/zen-bin
 Control Group: /user.slice/user-1000.slice/user@1000.service/kitty-160324-0.scope
          Unit: user@1000.service
     User Unit: kitty-160324-0.scope
         Slice: user-1000.slice
     Owner UID: 1000 (LightJack05)
       Boot ID: baf64c8714ef47d3a18e0059516b90ce
    Machine ID: 594f2070b97446d5ba9a676cf56a3ad9
      Hostname: Banana-PC
       Storage: /var/lib/systemd/coredump/core.Isolated\x20Web\x20Co.1000.baf64c8714ef47d3a18e0059516b90ce.162845.1728596087000000.zst (present)
  Size on Disk: 119.3M
       Message: Process 162845 (Isolated Web Co) of user 1000 dumped core.
                
                Stack trace of thread 163051:
                #0  0x000079ef4e4e371a n/a (libxul.so + 0x3ee371a)
                #1  0x000079ef500c1f21 n/a (libxul.so + 0x5ac1f21)
                #2  0x000079ef500b51f0 n/a (libxul.so + 0x5ab51f0)
                #3  0x000079ef50199620 n/a (libxul.so + 0x5b99620)
                #4  0x000079ef50197c39 n/a (libxul.so + 0x5b97c39)
                #5  0x000079ef50196dcc n/a (libxul.so + 0x5b96dcc)
                #6  0x000079ef500cbaeb n/a (libxul.so + 0x5acbaeb)
                #7  0x000079ef50170efb n/a (libxul.so + 0x5b70efb)
                #8  0x000079ef500e1cfe n/a (libxul.so + 0x5ae1cfe)
                #9  0x000079ef4d8baaad n/a (libxul.so + 0x32baaad)
                #10 0x000079ef4d8b9a13 n/a (libxul.so + 0x32b9a13)
                #11 0x000079ef4d83459d n/a (libxul.so + 0x323459d)
                #12 0x000079ef4d8b5f95 n/a (libxul.so + 0x32b5f95)
                #13 0x000079ef590ff4df n/a (libnspr4.so + 0x1b4df)
                #14 0x000079ef591b439d n/a (libc.so.6 + 0x9439d)
                #15 0x000079ef592392a4 __clone (libc.so.6 + 0x1192a4)
                
                Stack trace of thread 162845:
                #0  0x000079ef5922b63d __poll (libc.so.6 + 0x10b63d)
                #1  0x000079ef4d8c9e14 n/a (libxul.so + 0x32c9e14)
                #2  0x000079ef56d7009e n/a (libglib-2.0.so.0 + 0xc009e)
                #3  0x000079ef56d0ca55 g_main_context_iteration (libglib-2.0.so.0 + 0x5ca55)
                #4  0x000079ef4d8c4942 n/a (libxul.so + 0x32c4942)
                #5  0x000079ef4d8ba3f8 n/a (libxul.so + 0x32ba3f8)
                #6  0x000079ef4d8c89cd n/a (libxul.so + 0x32c89cd)
                #7  0x000079ef4d83459d n/a (libxul.so + 0x323459d)
                #8  0x000079ef4d8c3386 n/a (libxul.so + 0x32c3386)
                #9  0x000079ef4d8c321c n/a (libxul.so + 0x32c321c)
                #10 0x000079ef4d8c3179 n/a (libxul.so + 0x32c3179)
                #11 0x000079ef4d83459d n/a (libxul.so + 0x323459d)
                #12 0x000079ef4d825899 n/a (libxul.so + 0x3225899)
                #13 0x00006516a35512ea n/a (zen-bin + 0x342ea)
                #14 0x000079ef59145e08 n/a (libc.so.6 + 0x25e08)
                #15 0x000079ef59145ecc __libc_start_main (libc.so.6 + 0x25ecc)
                #16 0x00006516a3586ad2 _start (zen-bin + 0x69ad2)
                
                Stack trace of thread 162856:
                #0  0x000079ef5922bc5a read (libc.so.6 + 0x10bc5a)
                #1  0x000079ef4d825c0e n/a (libxul.so + 0x3225c0e)
                #2  0x000079ef591b439d n/a (libc.so.6 + 0x9439d)
                #3  0x000079ef5923949c n/a (libc.so.6 + 0x11949c)
                
                Stack trace of thread 162860:
                #0  0x000079ef591b0a19 n/a (libc.so.6 + 0x90a19)
                #1  0x000079ef591b3479 pthread_cond_wait (libc.so.6 + 0x93479)
                #2  0x00006516a3567106 _ZN7mozilla6detail21ConditionVariableImpl4waitERNS0_9MutexImplE (zen-bin + 0x4a106)
                #3  0x000079ef4d8ba6c0 n/a (libxul.so + 0x32ba6c0)
                #4  0x000079ef4d8b9aee n/a (libxul.so + 0x32b9aee)
                #5  0x000079ef4d83459d n/a (libxul.so + 0x323459d)
                #6  0x000079ef4d8b5f95 n/a (libxul.so + 0x32b5f95)
                #7  0x000079ef590ff4df n/a (libnspr4.so + 0x1b4df)
                #8  0x000079ef591b439d n/a (libc.so.6 + 0x9439d)
                #9  0x000079ef5923949c n/a (libc.so.6 + 0x11949c)
                
                Stack trace of thread 162862:
                #0  0x000079ef592371fd syscall (libc.so.6 + 0x1171fd)
                #1  0x000079ef4df9ea22 n/a (libxul.so + 0x399ea22)
                #2  0x000079ef530dc429 n/a (libxul.so + 0x8adc429)
                #3  0x000079ef530dbddf n/a (libxul.so + 0x8adbddf)
                #4  0x000079ef530d99db n/a (libxul.so + 0x8ad99db)
                #5  0x000079ef52e026de n/a (libxul.so + 0x88026de)
                #6  0x000079ef591b439d n/a (libc.so.6 + 0x9439d)
                #7  0x000079ef5923949c n/a (libc.so.6 + 0x11949c)
                
                Stack trace of thread 162864:
                #0  0x000079ef592371fd syscall (libc.so.6 + 0x1171fd)
                #1  0x000079ef4df9ea22 n/a (libxul.so + 0x399ea22)
                #2  0x000079ef530dc429 n/a (libxul.so + 0x8adc429)
                #3  0x000079ef530dbddf n/a (libxul.so + 0x8adbddf)
                #4  0x000079ef530d99db n/a (libxul.so + 0x8ad99db)
                #5  0x000079ef52e026de n/a (libxul.so + 0x88026de)
                #6  0x000079ef591b439d n/a (libc.so.6 + 0x9439d)
                #7  0x000079ef5923949c n/a (libc.so.6 + 0x11949c)
                
                Stack trace of thread 162865:
                #0  0x000079ef592371fd syscall (libc.so.6 + 0x1171fd)
                #1  0x000079ef4df9ea22 n/a (libxul.so + 0x399ea22)
                #2  0x000079ef530dc429 n/a (libxul.so + 0x8adc429)
                #3  0x000079ef530dbddf n/a (libxul.so + 0x8adbddf)
                #4  0x000079ef530d99db n/a (libxul.so + 0x8ad99db)
                #5  0x000079ef52e026de n/a (libxul.so + 0x88026de)
                #6  0x000079ef591b439d n/a (libc.so.6 + 0x9439d)
                #7  0x000079ef5923949c n/a (libc.so.6 + 0x11949c)
                
                Stack trace of thread 162869:
                #0  0x000079ef591b0a19 n/a (libc.so.6 + 0x90a19)
                #1  0x000079ef591b37e2 pthread_cond_timedwait (libc.so.6 + 0x937e2)
                #2  0x00006516a3566fc9 _ZN7mozilla6detail21ConditionVariableImpl8wait_forERNS0_9MutexImplERKNS_16BaseTimeDurationINS_27TimeDurationValueCalculatorEEE (zen-bin + 0x49fc9)
                #3  0x000079ef4d8be751 n/a (libxul.so + 0x32be751)
                #4  0x000079ef4d8baaad n/a (libxul.so + 0x32baaad)
                #5  0x000079ef4d8b9a13 n/a (libxul.so + 0x32b9a13)
                #6  0x000079ef4d83459d n/a (libxul.so + 0x323459d)
                #7  0x000079ef4d8b5f95 n/a (libxul.so + 0x32b5f95)
                #8  0x000079ef590ff4df n/a (libnspr4.so + 0x1b4df)
                #9  0x000079ef591b439d n/a (libc.so.6 + 0x9439d)
                #10 0x000079ef5923949c n/a (libc.so.6 + 0x11949c)
                
                Stack trace of thread 162870:
                #0  0x000079ef591b0a19 n/a (libc.so.6 + 0x90a19)
                #1  0x000079ef591b37e2 pthread_cond_timedwait (libc.so.6 + 0x937e2)
                #2  0x00006516a3566fc9 _ZN7mozilla6detail21ConditionVariableImpl8wait_forERNS0_9MutexImplERKNS_16BaseTimeDurationINS_27TimeDurationValueCalculatorEEE (zen-bin + 0x49fc9)
                #3  0x000079ef4d8cce93 n/a (libxul.so + 0x32cce93)
                #4  0x000079ef4d8baaad n/a (libxul.so + 0x32baaad)
                #5  0x000079ef4d8b9a13 n/a (libxul.so + 0x32b9a13)
                #6  0x000079ef4d83459d n/a (libxul.so + 0x323459d)
                #7  0x000079ef4d8b5f95 n/a (libxul.so + 0x32b5f95)
                #8  0x000079ef590ff4df n/a (libnspr4.so + 0x1b4df)
                #9  0x000079ef591b439d n/a (libc.so.6 + 0x9439d)
                #10 0x000079ef5923949c n/a (libc.so.6 + 0x11949c)
                
                Stack trace of thread 162883:
                #0  0x000079ef591b0a19 n/a (libc.so.6 + 0x90a19)
                #1  0x000079ef591b3479 pthread_cond_wait (libc.so.6 + 0x93479)
                #2  0x00006516a3567106 _ZN7mozilla6detail21ConditionVariableImpl4waitERNS0_9MutexImplE (zen-bin + 0x4a106)
                #3  0x000079ef4d8ba6c0 n/a (libxul.so + 0x32ba6c0)
                #4  0x000079ef4d8b9aee n/a (libxul.so + 0x32b9aee)
                #5  0x000079ef4d83459d n/a (libxul.so + 0x323459d)
                #6  0x000079ef4d8b5f95 n/a (libxul.so + 0x32b5f95)
                #7  0x000079ef590ff4df n/a (libnspr4.so + 0x1b4df)
                #8  0x000079ef591b439d n/a (libc.so.6 + 0x9439d)
                #9  0x000079ef5923949c n/a (libc.so.6 + 0x11949c)
                
                Stack trace of thread 162888:
                #0  0x000079ef591b0a19 n/a (libc.so.6 + 0x90a19)
                #1  0x000079ef591b3479 pthread_cond_wait (libc.so.6 + 0x93479)
                #2  0x00006516a3567106 _ZN7mozilla6detail21ConditionVariableImpl4waitERNS0_9MutexImplE (zen-bin + 0x4a106)
                #3  0x000079ef4d8ba6c0 n/a (libxul.so + 0x32ba6c0)
                #4  0x000079ef4d8b9aee n/a (libxul.so + 0x32b9aee)
                #5  0x000079ef4d83459d n/a (libxul.so + 0x323459d)
                #6  0x000079ef4d8b5f95 n/a (libxul.so + 0x32b5f95)
                #7  0x000079ef590ff4df n/a (libnspr4.so + 0x1b4df)
                #8  0x000079ef591b439d n/a (libc.so.6 + 0x9439d)
                #9  0x000079ef592392a4 __clone (libc.so.6 + 0x1192a4)
                
                Stack trace of thread 162919:
                #0  0x000079ef591b0a19 n/a (libc.so.6 + 0x90a19)
                #1  0x000079ef591b3479 pthread_cond_wait (libc.so.6 + 0x93479)
                #2  0x00006516a3567106 _ZN7mozilla6detail21ConditionVariableImpl4waitERNS0_9MutexImplE (zen-bin + 0x4a106)
                #3  0x000079ef4dca7d04 n/a (libxul.so + 0x36a7d04)
                #4  0x000079ef590ff4df n/a (libnspr4.so + 0x1b4df)
                #5  0x000079ef591b439d n/a (libc.so.6 + 0x9439d)
                #6  0x000079ef592392a4 __clone (libc.so.6 + 0x1192a4)
                
                Stack trace of thread 162920:
                #0  0x000079ef591b0a19 n/a (libc.so.6 + 0x90a19)
                #1  0x000079ef591b3479 pthread_cond_wait (libc.so.6 + 0x93479)
                #2  0x00006516a3567106 _ZN7mozilla6detail21ConditionVariableImpl4waitERNS0_9MutexImplE (zen-bin + 0x4a106)
                #3  0x000079ef4dca7d04 n/a (libxul.so + 0x36a7d04)
                #4  0x000079ef590ff4df n/a (libnspr4.so + 0x1b4df)
                #5  0x000079ef591b439d n/a (libc.so.6 + 0x9439d)
                #6  0x000079ef592392a4 __clone (libc.so.6 + 0x1192a4)
                
                Stack trace of thread 162861:
                #0  0x000079ef592371fd syscall (libc.so.6 + 0x1171fd)
                #1  0x000079ef4df9ea22 n/a (libxul.so + 0x399ea22)
                #2  0x000079ef530dc429 n/a (libxul.so + 0x8adc429)
                #3  0x000079ef530dbddf n/a (libxul.so + 0x8adbddf)
                #4  0x000079ef530d99db n/a (libxul.so + 0x8ad99db)
                #5  0x000079ef52e026de n/a (libxul.so + 0x88026de)
                #6  0x000079ef591b439d n/a (libc.so.6 + 0x9439d)
                #7  0x000079ef5923949c n/a (libc.so.6 + 0x11949c)
                
                Stack trace of thread 162924:
                #0  0x000079ef591b0a19 n/a (libc.so.6 + 0x90a19)
                #1  0x000079ef591b3479 pthread_cond_wait (libc.so.6 + 0x93479)
                #2  0x00006516a3567106 _ZN7mozilla6detail21ConditionVariableImpl4waitERNS0_9MutexImplE (zen-bin + 0x4a106)
                #3  0x000079ef4dca7d04 n/a (libxul.so + 0x36a7d04)
                #4  0x000079ef590ff4df n/a (libnspr4.so + 0x1b4df)
                #5  0x000079ef591b439d n/a (libc.so.6 + 0x9439d)
                #6  0x000079ef592392a4 __clone (libc.so.6 + 0x1192a4)
                
                Stack trace of thread 162871:
                #0  0x000079ef591b0a19 n/a (libc.so.6 + 0x90a19)
                #1  0x000079ef591b3479 pthread_cond_wait (libc.so.6 + 0x93479)
                #2  0x00006516a3567106 _ZN7mozilla6detail21ConditionVariableImpl4waitERNS0_9MutexImplE (zen-bin + 0x4a106)
                #3  0x000079ef4d8ba6c0 n/a (libxul.so + 0x32ba6c0)
                #4  0x000079ef4d8b9aee n/a (libxul.so + 0x32b9aee)
                #5  0x000079ef4d83459d n/a (libxul.so + 0x323459d)
                #6  0x000079ef4d8b5f95 n/a (libxul.so + 0x32b5f95)
                #7  0x000079ef590ff4df n/a (libnspr4.so + 0x1b4df)
                #8  0x000079ef591b439d n/a (libc.so.6 + 0x9439d)
                #9  0x000079ef5923949c n/a (libc.so.6 + 0x11949c)
                
                Stack trace of thread 162863:
                #0  0x000079ef592371fd syscall (libc.so.6 + 0x1171fd)
                #1  0x000079ef4df9ea22 n/a (libxul.so + 0x399ea22)
                #2  0x000079ef530dc429 n/a (libxul.so + 0x8adc429)
                #3  0x000079ef530dbddf n/a (libxul.so + 0x8adbddf)
                #4  0x000079ef530d99db n/a (libxul.so + 0x8ad99db)
                #5  0x000079ef52e026de n/a (libxul.so + 0x88026de)
                #6  0x000079ef591b439d n/a (libc.so.6 + 0x9439d)
                #7  0x000079ef5923949c n/a (libc.so.6 + 0x11949c)
                
                Stack trace of thread 162866:
                #0  0x000079ef591b0a19 n/a (libc.so.6 + 0x90a19)
                #1  0x000079ef591b37e2 pthread_cond_timedwait (libc.so.6 + 0x937e2)
                #2  0x000079ef5910031e PR_WaitCondVar (libnspr4.so + 0x1c31e)
                #3  0x000079ef4d93fb44 n/a (libxul.so + 0x333fb44)
                #4  0x000079ef590ff4df n/a (libnspr4.so + 0x1b4df)
                #5  0x000079ef591b439d n/a (libc.so.6 + 0x9439d)
                #6  0x000079ef5923949c n/a (libc.so.6 + 0x11949c)
                
                Stack trace of thread 162889:
                #0  0x000079ef591b0a19 n/a (libc.so.6 + 0x90a19)
                #1  0x000079ef591b3479 pthread_cond_wait (libc.so.6 + 0x93479)
                #2  0x00006516a3567106 _ZN7mozilla6detail21ConditionVariableImpl4waitERNS0_9MutexImplE (zen-bin + 0x4a106)
                #3  0x000079ef4d8ba6c0 n/a (libxul.so + 0x32ba6c0)
                #4  0x000079ef4d8b9aee n/a (libxul.so + 0x32b9aee)
                #5  0x000079ef4d83459d n/a (libxul.so + 0x323459d)
                #6  0x000079ef4d8b5f95 n/a (libxul.so + 0x32b5f95)
                #7  0x000079ef590ff4df n/a (libnspr4.so + 0x1b4df)
                #8  0x000079ef591b439d n/a (libc.so.6 + 0x9439d)
                #9  0x000079ef592392a4 __clone (libc.so.6 + 0x1192a4)
                
                Stack trace of thread 162858:
                #0  0x000079ef591b0a19 n/a (libc.so.6 + 0x90a19)
                #1  0x000079ef591b3479 pthread_cond_wait (libc.so.6 + 0x93479)
                #2  0x00006516a3567106 _ZN7mozilla6detail21ConditionVariableImpl4waitERNS0_9MutexImplE (zen-bin + 0x4a106)
                #3  0x000079ef4d8ba6c0 n/a (libxul.so + 0x32ba6c0)
                #4  0x000079ef4d8b9aee n/a (libxul.so + 0x32b9aee)
                #5  0x000079ef4d83459d n/a (libxul.so + 0x323459d)
                #6  0x000079ef4d8b5f95 n/a (libxul.so + 0x32b5f95)
                #7  0x000079ef590ff4df n/a (libnspr4.so + 0x1b4df)
                #8  0x000079ef591b439d n/a (libc.so.6 + 0x9439d)
                #9  0x000079ef5923949c n/a (libc.so.6 + 0x11949c)
                
                Stack trace of thread 162857:
                #0  0x000079ef592371fd syscall (libc.so.6 + 0x1171fd)
                #1  0x000079ef4d8393e5 n/a (libxul.so + 0x32393e5)
                #2  0x000079ef4d834be8 n/a (libxul.so + 0x3234be8)
                #3  0x000079ef4d83459d n/a (libxul.so + 0x323459d)
                #4  0x000079ef4d832191 n/a (libxul.so + 0x3232191)
                #5  0x000079ef4d831fc7 n/a (libxul.so + 0x3231fc7)
                #6  0x000079ef591b439d n/a (libc.so.6 + 0x9439d)
                #7  0x000079ef5923949c n/a (libc.so.6 + 0x11949c)
                
                Stack trace of thread 162942:
                #0  0x000079ef591b0a19 n/a (libc.so.6 + 0x90a19)
                #1  0x000079ef591b3479 pthread_cond_wait (libc.so.6 + 0x93479)
                #2  0x00006516a3567106 _ZN7mozilla6detail21ConditionVariableImpl4waitERNS0_9MutexImplE (zen-bin + 0x4a106)
                #3  0x000079ef500e1b1a n/a (libxul.so + 0x5ae1b1a)
                #4  0x000079ef50171aa9 n/a (libxul.so + 0x5b71aa9)
                #5  0x000079ef500e089c n/a (libxul.so + 0x5ae089c)
                #6  0x000079ef52ccbf63 n/a (libxul.so + 0x86cbf63)
                #7  0x000079ef52cd3d7b n/a (libxul.so + 0x86d3d7b)
                #8  0x000079ef52cc6d2c n/a (libxul.so + 0x86c6d2c)
                #9  0x000079ef52cc75fa n/a (libxul.so + 0x86c75fa)
                #10 0x000079ef4df9cc9b n/a (libxul.so + 0x399cc9b)
                #11 0x000079ef591b439d n/a (libc.so.6 + 0x9439d)
                #12 0x000079ef592392a4 __clone (libc.so.6 + 0x1192a4)
                
                Stack trace of thread 162887:
                #0  0x000079ef591b0a19 n/a (libc.so.6 + 0x90a19)
                #1  0x000079ef591b3479 pthread_cond_wait (libc.so.6 + 0x93479)
                #2  0x00006516a3567106 _ZN7mozilla6detail21ConditionVariableImpl4waitERNS0_9MutexImplE (zen-bin + 0x4a106)
                #3  0x000079ef4d8ba6c0 n/a (libxul.so + 0x32ba6c0)
                #4  0x000079ef4d8b9aee n/a (libxul.so + 0x32b9aee)
                #5  0x000079ef4d83459d n/a (libxul.so + 0x323459d)
                #6  0x000079ef4d8b5f95 n/a (libxul.so + 0x32b5f95)
                #7  0x000079ef590ff4df n/a (libnspr4.so + 0x1b4df)
                #8  0x000079ef591b439d n/a (libc.so.6 + 0x9439d)
                #9  0x000079ef592392a4 __clone (libc.so.6 + 0x1192a4)
                
                Stack trace of thread 163012:
                #0  0x000079ef591b0a19 n/a (libc.so.6 + 0x90a19)
                #1  0x000079ef591b37e2 pthread_cond_timedwait (libc.so.6 + 0x937e2)
                #2  0x00006516a3566fc9 _ZN7mozilla6detail21ConditionVariableImpl8wait_forERNS0_9MutexImplERKNS_16BaseTimeDurationINS_27TimeDurationValueCalculatorEEE (zen-bin + 0x49fc9)
                #3  0x000079ef4d8be751 n/a (libxul.so + 0x32be751)
                #4  0x000079ef4d8baaad n/a (libxul.so + 0x32baaad)
                #5  0x000079ef4d8b9a13 n/a (libxul.so + 0x32b9a13)
                #6  0x000079ef4d83459d n/a (libxul.so + 0x323459d)
                #7  0x000079ef4d8b5f95 n/a (libxul.so + 0x32b5f95)
                #8  0x000079ef590ff4df n/a (libnspr4.so + 0x1b4df)
                #9  0x000079ef591b439d n/a (libc.so.6 + 0x9439d)
                #10 0x000079ef592392a4 __clone (libc.so.6 + 0x1192a4)
                
                Stack trace of thread 162935:
                #0  0x000079ef591b0a19 n/a (libc.so.6 + 0x90a19)
                #1  0x000079ef591b3479 pthread_cond_wait (libc.so.6 + 0x93479)
                #2  0x00006516a3567106 _ZN7mozilla6detail21ConditionVariableImpl4waitERNS0_9MutexImplE (zen-bin + 0x4a106)
                #3  0x000079ef50a20a4b n/a (libxul.so + 0x6420a4b)
                #4  0x000079ef50a11f1a n/a (libxul.so + 0x6411f1a)
                #5  0x000079ef4d8baaad n/a (libxul.so + 0x32baaad)
                #6  0x000079ef4d8b9a13 n/a (libxul.so + 0x32b9a13)
                #7  0x000079ef4d83459d n/a (libxul.so + 0x323459d)
                #8  0x000079ef4d8b5f95 n/a (libxul.so + 0x32b5f95)
                #9  0x000079ef590ff4df n/a (libnspr4.so + 0x1b4df)
                #10 0x000079ef591b439d n/a (libc.so.6 + 0x9439d)
                #11 0x000079ef592392a4 __clone (libc.so.6 + 0x1192a4)
                
                Stack trace of thread 162886:
                #0  0x000079ef591b0a19 n/a (libc.so.6 + 0x90a19)
                #1  0x000079ef591b3479 pthread_cond_wait (libc.so.6 + 0x93479)
                #2  0x00006516a3567106 _ZN7mozilla6detail21ConditionVariableImpl4waitERNS0_9MutexImplE (zen-bin + 0x4a106)
                #3  0x000079ef4d8ba6c0 n/a (libxul.so + 0x32ba6c0)
                #4  0x000079ef4d8b9aee n/a (libxul.so + 0x32b9aee)
                #5  0x000079ef4d83459d n/a (libxul.so + 0x323459d)
                #6  0x000079ef4d8b5f95 n/a (libxul.so + 0x32b5f95)
                #7  0x000079ef590ff4df n/a (libnspr4.so + 0x1b4df)
                #8  0x000079ef591b439d n/a (libc.so.6 + 0x9439d)
                #9  0x000079ef5923949c n/a (libc.so.6 + 0x11949c)
                
                Stack trace of thread 163014:
                #0  0x000079ef591b0a19 n/a (libc.so.6 + 0x90a19)
                #1  0x000079ef591b3479 pthread_cond_wait (libc.so.6 + 0x93479)
                #2  0x00006516a3567106 _ZN7mozilla6detail21ConditionVariableImpl4waitERNS0_9MutexImplE (zen-bin + 0x4a106)
                #3  0x000079ef50a20a4b n/a (libxul.so + 0x6420a4b)
                #4  0x000079ef50a11f1a n/a (libxul.so + 0x6411f1a)
                #5  0x000079ef4d8baaad n/a (libxul.so + 0x32baaad)
                #6  0x000079ef4d8b9a13 n/a (libxul.so + 0x32b9a13)
                #7  0x000079ef4d83459d n/a (libxul.so + 0x323459d)
                #8  0x000079ef4d8b5f95 n/a (libxul.so + 0x32b5f95)
                #9  0x000079ef590ff4df n/a (libnspr4.so + 0x1b4df)
                #10 0x000079ef591b439d n/a (libc.so.6 + 0x9439d)
                #11 0x000079ef592392a4 __clone (libc.so.6 + 0x1192a4)
                
                Stack trace of thread 162923:
                #0  0x000079ef591b0a19 n/a (libc.so.6 + 0x90a19)
                #1  0x000079ef591b3479 pthread_cond_wait (libc.so.6 + 0x93479)
                #2  0x00006516a3567106 _ZN7mozilla6detail21ConditionVariableImpl4waitERNS0_9MutexImplE (zen-bin + 0x4a106)
                #3  0x000079ef4dca7d04 n/a (libxul.so + 0x36a7d04)
                #4  0x000079ef590ff4df n/a (libnspr4.so + 0x1b4df)
                #5  0x000079ef591b439d n/a (libc.so.6 + 0x9439d)
                #6  0x000079ef592392a4 __clone (libc.so.6 + 0x1192a4)
                
                Stack trace of thread 163048:
                #0  0x000079ef51bbe5a1 n/a (libxul.so + 0x75be5a1)
                #1  0x000079ef51bc4c38 n/a (libxul.so + 0x75c4c38)
                #2  0x000079ef4db274b8 n/a (libxul.so + 0x35274b8)
                #3  0x000079ef4dd38dee n/a (libxul.so + 0x3738dee)
                #4  0x000000576f9a64fd n/a (n/a + 0x0)
                #5  0x000000576fb27578 n/a (n/a + 0x0)
                #6  0x000000576fb28f32 n/a (n/a + 0x0)
                #7  0x000000576fa32e04 n/a (n/a + 0x0)
                #8  0x0000005770bc008a n/a (n/a + 0x0)
                #9  0x0000005770aac95b n/a (n/a + 0x0)
                #10 0x0000005770aa66bf n/a (n/a + 0x0)
                #11 0x0000005770aa6ba1 n/a (n/a + 0x0)
                #12 0x0000005770aa57c2 n/a (n/a + 0x0)
                #13 0x0000005770aa5196 n/a (n/a + 0x0)
                #14 0x0000005770aa84c1 n/a (n/a + 0x0)
                #15 0x0000005770ab1bf6 n/a (n/a + 0x0)
                #16 0x0000005770aa2a24 n/a (n/a + 0x0)
                #17 0x0000005770aa231a n/a (n/a + 0x0)
                #18 0x000000577007d68d n/a (n/a + 0x0)
                #19 0x000079ef51bbe237 n/a (libxul.so + 0x75be237)
                #20 0x000079ef33cbc018 n/a (n/a + 0x0)
                ELF object binary architecture: AMD x86-64
```
</p>
</details>

**Comment by m2x07** [comment] 2024-11-10 23:20
issue still remains on 1.0.1-a.17
using flatpak
windowing system: wayland

**Comment by okulvitra** [comment] 2024-12-07 09:56
Can confirm the issue is still happening today. 
Zen version: Version 1.0.1-a.22 (64-bit)
OS: Zorin OS 17.2 Core

Happening when allowing access to microphone.

**Comment by salamijason** [comment] 2024-12-15 09:02
Dupe of this issue https://github.com/zen-browser/desktop/issues/394

Will be closing this one.

**Closed by salamijason** 2024-12-15 09:02 UTC
