### ISSUE TITLE
Items with `backdrop-filter` overflow roundings

### ISSUE THREAD

**Issue by ghivert** [zen-browser/desktop#3133] opened 2024-11-20 21:13 UTC
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

When an item is at the top of the HTML tree, and is styled with `backdrop-filter`, the element does not get rounded in the page.

Some examples :
<img width="1014" alt="Capture d’écran 2024-11-20 à 22 11 57" src="https://github.com/user-attachments/assets/ade789c7-ea4d-4cd1-9761-be8e74b16d70">
<img width="1017" alt="Capture d’écran 2024-11-20 à 22 12 08" src="https://github.com/user-attachments/assets/495b79c8-b3ed-4178-9d4c-a72a0c30df28">

Can be seen on [https://sketch-gleam.netlify.app/](https://sketch-gleam.netlify.app/).

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.19

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by Woutuuur** [comment] 2024-12-17 02:29
This issue also occurs on [zen-browser.com](https://zen-browser.app/), see https://github.com/zen-browser/desktop/issues/3557. 

It also happens on [x.com](https://x.com/). Commenting out these seemingly unrelated styles on X's stylesheet fixes it:
```
.r-1xcajam{position:fixed;}
.r-18u37iz{flex-direction:row;}
.r-1awozwy{align-items:center;}
```
So the problem does not seem unique to `backdrop-filter`.

It seems we can't simply rely on `border-radius` for the clipping since there are combinations of elements & styles that do not get clipped by `overflow: hidden`.

**Comment by mr-cheffy** [comment] 2024-12-27 20:11
Duplicate of #3053

**Closed as completed by mr-cheffy** 2024-12-27 20:11 UTC
Labels: Bug
