### ISSUE TITLE
Updater is not signed; Windows gives warnings

### ISSUE THREAD

**Issue by donlassini** [zen-browser/desktop#1702] opened 2024-09-24 18:59 UTC
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Logged on to my PC today; a prompt asked if I wanted to run setup.exe (which had an unknown publisher).
Path is c:\Users\<me>\AppData\Local\Temp\7zS02228DC0\setup.exe
File is not signed, nor are files in the "core" folder in the same place.
The only signed binaries are msvcp140.dll and the two vcruntime140's.

setup.exe:
Product Name: Zen Browser
Copyright: Zen HQ
Version: 1.0.1-a.3.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.3

### What platform are you seeing the problem on?

Windows

**Comment by mr-cheffy** [comment] 2024-10-19 10:58
Duplicate of [https://github.com/zen-browser/desktop/issues/37](https://github.com/zen-browser/desktop/issues/37)

**Closed** 2024-10-19 10:58 UTC
