### ISSUE TITLE
Cant move tab to existing new window

### ISSUE THREAD

**Issue by joelpriyanth10** [zen-browser/desktop#2524] opened 2024-11-01 06:09 UTC
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I use multiple monitors and have windows of the browser in each. I can move a tab and create a new window but I am not able to move the tab into an existing window.

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.17

### What platform are you seeing the problem on?

Windows

**Comment by RayZ3R0** [comment] 2024-11-01 08:12
Seems to be a Windows issue, cant reproduce on linux. We'll look into it

**Comment by krisMG21** [comment] 2024-11-02 23:47
I'm on Windows 10 and seems to be working fine. 
There is not visual cue at the moment (it would be very appreciated), but a tab, when dropped on the **tab bar**, it's added onto the existing ones in the window, if dropped anywhere different a new window it's created.

In Windows 11 could be different maybe? Or, if it happened on w10, something to do with it being in another monitor?

**Comment by tedbergstrand** [comment] 2024-11-04 18:38
I don't have this problem in Windows 11. I'm able to move tabs from one window to another one on a different monitor.

**Comment by joelpriyanth10** [comment] 2024-11-07 06:22
Oh wait it seems to work fine if I have the sidebar on. I use compact mode and hide to sidebar, when I drag the tab the sidebar does not pop out.

**Comment by krisMG21** [comment] 2024-11-07 10:14
Ohhh, that makes sense. Without the sidebar visible, you cant add tabs to the window because the hover zone for that is at the sidebar only.
Then amazing, everything going smooth. 

Now it's choice of design if the dropzone for tabs can be extended to all the window, adding the tab at the bottom of the sidebar by default, since we are not hovering in it to choose.

**Comment by RayZ3R0** [comment] 2024-11-07 18:44
Will be closing this then, thanks!

**Closed as completed by RayZ3R0** 2024-11-07 18:44 UTC

**Comment by joelpriyanth10** [comment] 2024-11-07 20:37
> Ohhh, that makes sense. Without the sidebar visible, you cant add tabs to the window because the hover zone for that is at the sidebar only. Then amazing, everything going smooth.
> 
> Now it's choice of design if the dropzone for tabs can be extended to all the window, adding the tab at the bottom of the sidebar by default, since we are not hovering in it to choose.

Is there a way to auto expand the sidebar when hovering over a tab? This is what normally happens in arc as well.

**Comment by YaYaTurre** [comment] 2024-11-07 20:45
> Is there a way to auto expand the sidebar when hovering over a tab? This is what normally happens in arc as well.

Yes, it is in Settings under Look & Feel. 
<img width="770" alt="Screenshot 2024-11-07 at 20 43 52" src="https://github.com/user-attachments/assets/791c7099-c2f6-4178-ae75-fa38a4a61319">

**Comment by joelpriyanth10** [comment] 2024-11-07 20:47
It says won’t work on compact mode unfortunately. Would be nice to have
this as an option in the future.
