### ISSUE TITLE
Pop-up dialog appears hidden

### ISSUE THREAD

**Issue by mohvn** [zen-browser/desktop#3496] opened 2024-12-10 17:00 UTC
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

![image](https://github.com/user-attachments/assets/05aff173-f8d3-42c6-9955-da89342403e3)

The pop-up dialog seems to be rendering but is not visible to the user. It appears to be incorrectly positioned in the interface.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.0 (Firefox 133.0) (64-bit)

### What platform are you seeing the problem on?

Windows

**Comment by mr-cheffy** [comment] 2024-12-29 00:13
Duplicate of https://github.com/zen-browser/desktop/issues/3897

**Closed as completed by mr-cheffy** 2024-12-29 00:13 UTC
Labels: Bug
