### ISSUE TITLE
After updating to 1.0.1-a.16, Zen tabs occasionally become completely unresponsive with no content loading (Due to Glance?)

### ISSUE THREAD

**Issue by imJoshuaRice** [zen-browser/desktop#2459] opened 2024-10-31 09:53 UTC
Edit: I believe @tedbergstrand has identified the most likely cause - the Glance mechanic. I have had none of the below mentioned issues since I stopped using that feature.
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I updated to 1.0.1-a.16 this morning.

At least four times in the last two hours, when clicking on a tab - nothing appears to happen. The navigation bar still shows the content, the title of the tab on the side shows the title, but nothing loads.

When this happens, the tabs also cannot be re-ordered or dragged out to become a new window.

When this happens, the Zen Sidebar continues to work but any links opened as new tabs are still broken.

This requires a restart each time. I will record the next time it happens and attach to this issue.

I have marked this as not reproducible on Mozilla Firefox as I have been using the same version (Firefox 132.0) since the 29th.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.16

### What platform are you seeing the problem on?

Windows

**Comment by JSGRD22** [comment] 2024-10-31 10:04
This also happens on a.15.

**Comment by oreliain** [comment] 2024-10-31 10:45
Hello, I updated zen browser on 1.0.1-a.15 then to 1.0.1-a.16. I confirm I reproduce the issue on both versions.
If I could be more precise, the unloaded tabs are inactives.

- After 20 minutes, tab is automatically unloaded and become inactive (I cannot display it again)
- If I unload a specific tab via the context menu (on right click) the problem is the same

As a workaround, I disabled the auto unload tab feature in settings

Platform : Ubuntu 24.04.1 LTS

**Comment by imJoshuaRice** [comment] 2024-10-31 11:23
> As a workaround, I disabled the auto unload tab feature in settings

It sounds like your issue is: https://github.com/zen-browser/desktop/issues/2437, specifically unloaded tabs.

I can replicate the tab unloading issue, but when that happens you can close-reopen the affected tab and it doesn't stop you opening new ones. Or like you said, you can just disable tab unloading.

**This** issue may be related in some way given the timing, but to make the distinction; when this issue occurs, no tabs can be interacted with. This _includes_ opening new ones. The only content that seemed to load was from the Zen Sidebar web panel.

With the issue I am reporting - all tabs become unresponsive with no content loading at all. The tabs do not become grayed out to denote they are unloaded.


Just thought I'd make it clearer!

**Comment by IdaEdz** [comment] 2024-10-31 11:32
> It sounds like your issue is: #2460, specifically unloaded tabs.

I oppose these issues being related. #2460 has to do with the bookmark-bar element expanding beyond the window size.
But I agree that these problems came with the same update. a.15.

**Comment by tedbergstrand** [comment] 2024-10-31 11:42
After updating to a.16, my tabs are going inactive on their own and become unclickable, even after reloading. And then new tab functionality seems to break, too. Fully unresponsive. So I'm having both of the problems you guys seem to be having.

I'm going back to 1.0.1-a.12 and turning off auto-update for the foreseeable future. Even if I have to click don't update every time I open the browser. Something's gotten broken in every update since a.12. And Glance isn't useful, so I don't really care if I lose it.

**Comment by IdaEdz** [comment] 2024-10-31 11:50
I wanted to share my current workaround for this issue: 
Alt+F4 the window and open it again. Makes all the tabs clickable again.

**Comment by Sebo1090** [comment] 2024-10-31 12:06
I have a similar problem, on the earlier version of this problem I did not have, now it is enough that the tabs are unopened for 5 minutes and they stop responding to startup, what is worse after a while the problem builds up and you can not even enter the settings, the only thing left is to close the browser

**Comment by imJoshuaRice** [comment] 2024-10-31 12:18
> > It sounds like your issue is: #2460, specifically unloaded tabs.
> 
> I oppose these issues being related. #2460 has to do with the bookmark-bar element expanding beyond the window size. But I agree that these problems came with the same update. a.15.

Apologies, I somehow linked 2460 when I typed in 2437. I've updated my comment.




> I wanted to share my current workaround for this issue: Alt+F4 the window and open it again. Makes all the tabs clickable again.

Yes, as previously mentioned - when this particular problem occurs there is no way around it (like there is with the unloaded tabs issue), it requires a restart.

**Comment by jphjsoares** [comment] 2024-10-31 12:41
This also happens on MacOS

**Comment by Sebo1090** [comment] 2024-10-31 12:49
Is there any way to return to the earlier version without messing up something else, because now the browser is completely useless

**Comment by tedbergstrand** [comment] 2024-10-31 13:29
> Is there any way to return to the earlier version without messing up something else, because now the browser is completely useless

It's in the Releases section found here: https://github.com/zen-browser/desktop/releases/. 

This is the version I've rolled back to-- prior to the addition of Glance and the strange bugs in the sidebar, due to the refactor.  https://github.com/zen-browser/desktop/releases/tag/1.0.1-a.12 

As soon as you re-install, make sure to go to the settings and disable Auto-Update, or when you restart the browser, it'll update itself back to the broken version.

**Comment by Frestein** [comment] 2024-10-31 23:11
Duplicate of https://github.com/zen-browser/desktop/issues/2436.

**Comment by imJoshuaRice** [comment] 2024-11-01 00:06
> Duplicate of #2436.

That issue is with regards to unloaded tabs, 

> This issue may be related in some way given the timing, but to make the distinction; when this issue occurs, no tabs can be interacted with. This includes opening new ones. The only content that seemed to load was from the Zen Sidebar web panel.
> 
> With the issue I am reporting - all tabs become unresponsive with no content loading at all. The tabs do not become grayed out to denote they are unloaded.

**Comment by tedbergstrand** [comment] 2024-11-01 01:22
> > Duplicate of #2436.
> 
> That issue is with regards to unloaded tabs,
> 
> > This issue may be related in some way given the timing, but to make the distinction; when this issue occurs, no tabs can be interacted with. This includes opening new ones. The only content that seemed to load was from the Zen Sidebar web panel.
> > With the issue I am reporting - all tabs become unresponsive with no content loading at all. The tabs do not become grayed out to denote they are unloaded.

Agreed. There's more than one bug here-- or a single bug is manifesting in different ways. I experienced full-on lockouts as well as the unloaded tabs being the only lockouts when I was running a.16.

**Comment by DevSnyco** [comment] 2024-11-01 04:54
this should be fixed in the new release `1.0.1-a.17`

**Comment by tedbergstrand** [comment] 2024-11-01 14:51
It's not. Same thing happened within one minute of launching a.17. Full lockout, as all tabs were active.

These problems coincide, timing-wise, with the refactoring of the sidebar and the addition of Glance. I have very little doubt that this bug is related to the way Glance is implemented.

I'm going back to a.12, again.

**Comment by Asharax** [comment] 2024-11-01 16:19
It seems like this is fixed for me after the update & browser restart.

**Comment by tedbergstrand** [comment] 2024-11-01 16:58
Ash's experience made me think maybe I did something wrong.

So I tried again and got another full freezeout, with video proof this time. This is minutes ago on a.17, after a full restart of the computer to ensure as clean of a test environment as I could manage.

It still looks like it's related to Glance. If you notice the URL bar, it says Instagram, where I glanced into. But if you look at the page, it's a Reddit page. All tabs have become unresponsive to both clicks and Control+Tab.

https://github.com/user-attachments/assets/89f35318-b3cb-44b3-af19-7ea221642a38

New tabs are able to be created with the button, but cannot be interacted with. Changing the URL does not change the page or release the lock on the tabs.

This behavior isn't consistent. Sometimes it breaks the tabs, sometimes it breaks Glance and prevents it from opening again, and sometimes it works as expected (slow ass Apple transitions and all-- I know they've been sped up, but they're completely unnecessary). But it's happening because of Glance. I'm almost certain, now.

**Comment by imJoshuaRice** [comment] 2024-11-01 18:21
> It still looks like it's related to Glance. If you notice the URL bar, it says Instagram, where I glanced into. But if you look at the page, it's a Reddit page. All tabs have become unresponsive to both clicks and Control+Tab.
> Screen.Recording.2024-11-01.125558.mp4
> 
> New tabs are able to be created with the button, but cannot be interacted with. Changing the URL does not change the page or release the lock on the tabs.
> 
> This behavior isn't consistent. Sometimes it breaks the tabs, sometimes it breaks Glance and prevents it from opening again, and sometimes it works as expected (slow ass Apple transitions and all-- I know they've been sped up, but they're completely unnecessary). But it's happening because of Glance. I'm almost certain, now.

It sounds like you're on to something, that is exactly the behavior I was experiencing. 

For me, I did the update after reading the patch notes and tried out Glance a few times. At some point after returning back to Zen from whatever I was doing, I had those issues. I then vaguely recall using Glance a handful of other times without really thinking about it.

On top of this, I have had absolutely zero issues since my initial report - but I now realize.. I haven't used Glance a single time since.

**Comment by tedbergstrand** [comment] 2024-11-01 18:42
I'm glad that was your experience, too.

My hunch is that since Glance windows aren't really tabs, but kind of are tabs (or children of tabs), the browser doesn't handle closing them properly all the time. I really think Glance should be a Split option or should take over the Web Panel and float it. Those features both work, already.

**Comment by knoopx** [comment] 2024-11-03 16:25
I'm on 1.0.1-a.17 (64-bit, Linux) and experiencing related issues after upgrading. I did not turn this on but it replaced the default ctrl+click anyway, and whenever I launch it by mistake it takes like 3 seconds to be interactive (because of the long intrusive animations) and then it won't release mouse/kb control back once closed, forcing me to restart the browser. no offense intended but not a fan of the feature/current status to be enabled by default.

**Comment by Asharax** [comment] 2024-11-03 17:01
@tedbergstrand you're 100% right, I wasn't using glance before, the issue I was facing with was about tab unloading. I can now reliably replicate the same issue on both Mac and Linux when using glance.

**Comment by justingallant1988** [comment] 2024-11-05 14:46
This is still occuring on 1.0.1-a.17

Currently if I unload a pinned tab, I cannot click on it again. Once I click unload thats it. I have to restart the browser to make it clickable/accessible again.

**Comment by mr-cheffy** [comment] 2024-11-06 20:50
let's see if it got fixed on verion 18

**Comment by tedbergstrand** [comment] 2024-11-07 14:30
> let's see if it got fixed on verion 18

Seems like you nailed it! I can't get it to present itself in t.18, right now.

Thanks @mauro-balades! For everything! <3

**Closed as completed** 2024-11-10 03:17 UTC
Labels: Bug
