### ISSUE TITLE
[Windows]-[UI Issue]-open previous tabs message position issue

### ISSUE THREAD

**Issue by zJohnWick** [zen-browser/desktop#194] opened 2024-08-09 04:52 UTC
### What happened?

Actual Result: "open previous tabs" message position is wrong. 
![image](https://github.com/user-attachments/assets/0d8aecee-883e-4d66-b495-f598a467a518)

Expected Result: "open previous tabs" message position height and width should match with the Vertical Tabs size. Or that message should be displayed horizontally like official Firefox. 

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

Alpha build - 1.0.0-a.15 (2024-08-07)

### Severity impact

Medium

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment] 2024-08-09 07:12
For UI issues, please use the low priority

**Comment by mauro-balades** [comment] 2024-08-09 07:13
Duplicate of #179

**Closed by mauro-balades** 2024-08-09 07:13 UTC
Labels: kind: low severity
