### ISSUE TITLE
Zeb browser crashes

### ISSUE THREAD

**Issue by Alexei1R** [zen-browser/desktop#1141] opened 2024-08-31 19:50 UTC
### What happened?

Zeb browser crashes; I've noticed this several times, and almost every time there were different tabs open. I use Arch, NVIDIA, and Wayland. 
I installed the  browser from aur "https://aur.archlinux.org/packages/zen-browser-bin"

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0

### Severity impact

Medium

### What platform are you seeing the problem on?

Linux

### Relevant log output

```shell
~🐍 v3.12.5 
🚀 22:29:14 ❯ zen-browser &         
[1] 25126

~🐍 v3.12.5 
✦ 🚀 22:29:38 ❯ Crash Annotation GraphicsCriticalError: |[0][GFX1-]: Wayland protocol error: wp_linux_drm_syncobj_surface_v1#91: error 4: Missing timeline
 (t=580.475) [GFX1-]: Wayland protocol error: wp_linux_drm_syncobj_surface_v1#91: error 4: Missing timeline

Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
Crash Annotation GraphicsCriticalError: |[C0][GFX1-]: CompositorBridgeChild receives IPC close with reason=AbnormalShutdown (t=5Exiting due to channel error.
Crash Annotation GraphicsCriticalError: |[C0][GFX1-]: CompositorBridgeChild receives IPC close with reason=AbnormalShutdown (t=5Crash Annotation GraphicsCriticalError: |[C0][GFX1-]: CompositorBridgeChild receives IPC close with reason=AbnormalShutdown (t=5Exiting due to channel error.
80.689) 64.153) Exiting due to channel error.
Crash Annotation GraphicsCriticalError: |[C0][GFX1-]: CompositorBridgeChild receives IPC close with reason=AbnormalShutdown (t=581.76) [GFX1-]: CompositorBridgeChild receives IPC close with reason=AbnormalShutdown
Exiting due to channel error.

[1]  + segmentation fault (core dumped)  zen-browser

~🐍 v3.12.5 
✦ 🚀 22:39:10 ❯
```

**Comment by frandmb** [comment] 2024-08-31 20:10
Duplicate of #296

**Comment by mauro-balades** [comment] 2024-09-01 10:00
Yes, please do follow those instructions until firefox fixes them in 130

**Closed by mauro-balades** 2024-09-01 10:00 UTC
Labels: kind: medium severity
