### ISSUE TITLE
Toggle Sidebar shortcut don't work on Windows 11

### ISSUE THREAD

**Issue by BartekSmalec** [zen-browser/desktop#1313] opened 2024-09-07 19:19 UTC
### Captchas

- [x] I have read the instructions.
- [x] I have searched existing issues and avoided creating duplicates.
- [x] I am not filing an enhancement request.

### What happened?

Hello on windows when i try to set "Toggle sidebar" shortcut it don't work properly. Instead of sidebar it toggle bookmark sidebar. When I press this shortcut second time bookmark sidebar disappear. With this settings both shortcuts Ctrl + p, Ctrl +m toggle bookmark sidebar. I've also tried with check "Disable Zen Browser's default keyboard shortcuts" option and without it with the same result :( It didn't have any impact.
![image](https://github.com/user-attachments/assets/2252f138-24d5-4cfc-a17a-0c73f049ceae)
![image](https://github.com/user-attachments/assets/9cca3962-17ca-452b-8c0e-c9659604f61d)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.37 (64-bit)

### What platform are you seeing the problem on?

Windows

**Comment by n7itro** [comment] 2024-09-07 20:51
The `Toggle sidebar` shortcut refers to the bookmarks toolbar. What did you expect it to do?

**Comment by BartekSmalec** [comment] 2024-09-07 20:59
How can i toggle "left sidebar" with tabs using shortcut ? The same action i can do using this button with two arrows in left corner. 
![image](https://github.com/user-attachments/assets/ac65207e-a006-4f7d-99c7-e6d55af795ac)

**Comment by NOCanoa** [comment] 2024-09-07 23:27
btw if some short cuts dont work, try disabling the default ones and see it it works

**Comment by NOCanoa** [comment] 2024-09-07 23:33
@BartekSmalec Its curenly not possible, there looks like there is a misconfiguration on our end.

@mauro-balades Show Bookmark Sidebar(open only) and Toggle Sidebar(open/close) , do the same thing 🤦‍♂️

**Comment by mauro-balades** [comment] 2024-09-08 08:24
I'll see what I can do

**Comment by BartekSmalec** [comment] 2024-09-11 11:11
> the setting u're looking for might just be toggle web panels kinda weird that it's called sidebar, but in shortcuts it's web panels also if shortcuts don't work try setting them up with capitalized letter, ie. ctrl + P instead of ctrl + p

It doesn't work for me. As far I understand based on @NOCanoa response "Toggle sidebar" shortcut should toggle and untoggle sidebar with tabs.

**Comment by HarryHeres** [comment] 2024-09-11 12:10
Closing - will be fixed in #1363

**Comment by jeff-hykin** [comment] 2024-09-16 13:47
Not sure if you want this reported here or a new issue, but I believe currently webpages override built-in browser shortcuts.

Ex: I'm cycling through workspaces with meta+shift+e, but then I hit a google spreadsheet tab, and then it gets trapped. I've got to make a new tab in order to continue cycling through workspaces.

Notes
- I bet it won't be a super-easy fix because the settings tab needs to capture user input when re-binding shortcuts
- For MacOS, a fix (that I would also love for other reasons) could be to put the shortcut-actions in the top bar (the File,Edit,View,History,etc). If its in the top bar, then a MacOS system shortcut can be made to select the option, and it should take precedence over the webpage shortcuts.

**Comment by HarryHeres** [comment] 2024-09-16 18:28
I don't think I follow? Do you mean it the way that some tabs (applications) capture the shortcuts?

**Comment by jeff-hykin** [comment] 2024-09-16 21:33
Ah I didn't realize what I was complaining about was actually standard behavior in Firefox, which probably added to the confusion. Maybe my thing is more of a feature request.

To clarify what I meant:
Expected behavior: CMD+R always reloads the page, unless focused on the bind-a-key in the settings panel
Actual behavior: CMD+R reloads except on pages, like Microsofts online-excel, where the webpage makes its own binding

**Comment by jeff-hykin** [comment] 2024-09-16 21:37
> I don't think I follow? Do you mean it the way that some tabs (applications) capture the shortcuts?

Sorry I had #1363 open in a different tab and accidentally put my comment on here instead.
I went ahead and moved my comment+update over to that thread

**Closed** 2024-10-30 15:09 UTC
Labels: Bug
