### ISSUE TITLE
console.log does't print on terminal when put directly

### ISSUE THREAD

**Issue by lucaspereirasouzat** [zen-browser/desktop#683] opened 2024-08-25 17:05 UTC
### What happened?

![image](https://github.com/user-attachments/assets/0d38ebd5-5c1c-442f-b03a-d0adaead823a)

Should print console.log 

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a-28

### Severity impact

Medium, High

### What platform are you seeing the problem on?

Linux

**Comment by rrojan** [comment] 2024-08-25 17:06
`alert`, `confirm`, etc have no effect either.

**Comment by FlashAmarillo** [comment] 2024-08-26 01:40
I tried and I'm like 😮 🤣

**Comment by Iziram** [comment] 2024-08-26 06:34
related to #593

**Comment by mauro-balades** [comment] 2024-08-26 10:28
Duplicate of https://github.com/zen-browser/desktop/issues/593

**Closed by mauro-balades** 2024-08-26 10:28 UTC
Labels: kind: medium severity, kind: high severity
