### ISSUE TITLE
How to put the search bar in its place?

### ISSUE THREAD

**Issue by iustinm1** [zen-browser/desktop#3567] opened 2024-12-11 12:10 UTC
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

The search bar detached itself from it should be and i cant find the setting to revert this
![image](https://github.com/user-attachments/assets/6784c8d3-23af-43a8-a25a-8574921b797c)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

latest

### What platform are you seeing the problem on?

Windows

**Comment by Raiden0456** [comment] 2024-12-11 12:18
this is intentional and yeah its not for everyone, definitely should be a toggle

**Comment by GeorgeV220** [comment] 2024-12-11 12:37
![image](https://github.com/user-attachments/assets/7b994ab6-e2a2-45a4-972b-d79ab386bb77)
uhm tbh I thought it was a bug..

**Comment by FA-TAAA** [comment] 2024-12-11 12:46
![image](https://github.com/user-attachments/assets/fe8a8fde-1b80-45a1-823c-181053baf1ef)
![image](https://github.com/user-attachments/assets/fef55d48-6a42-4fc0-a2dd-def3edb50c61)

I really don't like it. And there's also another bug.

**Comment by CostcoFanboy** [comment] 2024-12-11 13:05
I'm ngl I thought missing the ability to turn it off was the bug until I read this. Then I grew unsure if the entire design was bugged.
So I wrote https://github.com/zen-browser/desktop/issues/3570, will close that because now it's a dupe.

It's a shame because this browser was honestly perfect until this decision.

**Comment by FA-TAAA** [comment] 2024-12-11 13:08
> I'm ngl I thought missing the ability to turn it off was the bug until I read this. Then I grew unsure if the entire design was bugged. So I wrote #3570, will close that because now it's a dupe.
> 
> It's a shame because this browser was honestly perfect until this decision.

For real bro. I love this browser. I have no clue why they add changes nobody ask for.

**Comment by GeorgeV220** [comment] 2024-12-11 13:08
> ![image](https://private-user-images.githubusercontent.com/95973966/394749238-fef55d48-6a42-4fc0-a2dd-def3edb50c61.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM5MjI3MzIsIm5iZiI6MTczMzkyMjQzMiwicGF0aCI6Ii85NTk3Mzk2Ni8zOTQ3NDkyMzgtZmVmNTVkNDgtNmE0Mi00ZmMwLWEyZGQtZGVmM2VkYjUwYzYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjExVDEzMDcxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5ZGFmYmZiNTg4YzU2NjFmYjVmY2ZiYjUyZTEzNzMyZWI4MGFjOGMxYTRiNDk2Yjc0OTQ3MDEyNzAwZTk1OTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.-2aj24Zt-MSBRY61QIrRf1Ywn8mtxXEJFMEHoGtXJ6c)
> 
> I really don't like it. And there's also another bug.


Ah yeah, the true macOS experience

**Comment by GeorgeV220** [comment] 2024-12-11 13:09
> > I'm ngl I thought missing the ability to turn it off was the bug until I read this. Then I grew unsure if the entire design was bugged. So I wrote #3570, will close that because now it's a dupe.
> > It's a shame because this browser was honestly perfect until this decision.
> 
> For real bro. I love this browser. I have no clue why they add changes nobody ask for.

ok even if they wanted those changes, add a toggle.. or make it a mod or something idk

**Comment by dror-g** [comment] 2024-12-11 13:21
It's even worse in Compact Mode - 
navbar appears at top on hover, jumps to middle on click,
And not centered, right side with settings cog overflows outside screen.

![Screenshot at 2024-12-11 13-17-28](https://github.com/user-attachments/assets/3223f741-fa42-4760-a216-8469b9663065)

**Comment by mertkont** [comment] 2024-12-11 13:41
Hello, I have the same problem right now. Waiting for the solution. I tried things in settings of the browser, but couldn't solved.

**Comment by Minnona** [comment] 2024-12-11 13:48
Yeah, I hate it too

**Comment by LucasCoppola** [comment] 2024-12-11 14:39
I have the same problem, but using the Floating URLbar mod to center it works as a temporary solution until it's fixed, at least on Windows.

**Comment by trinajstica** [comment] 2024-12-11 14:42
where is Floating URLbar mod? they removed it? I hate such drastic changes, really...

**Comment by LucasCoppola** [comment] 2024-12-11 14:51
> where is Floating URLbar mod? they removed it? I hate such drastic changes, really...

I think they did. I have it installed but I can't find it on the Zen website.

**Comment by GeorgeV220** [comment] 2024-12-11 15:11
> I have the same problem, but using the Floating URLbar mod to center it works as a temporary solution until it's fixed, at least on Windows.

can you upload the mod as zip or something?

**Comment by orangepancakes** [comment] 2024-12-11 15:30
It's ridiculous that beta is entirely different browser than alpha and you can't opt out of those useless and tasteless changes.

**Comment by tomsik-radek** [comment] 2024-12-11 15:39
This and the icon... I'm adding my name to the "please revert" list.

**Comment by leuchtrakete666** [comment] 2024-12-11 15:40
puhh, this thread saved my day ...

i already was thinking i am too stupid to find the toggle to turn this "feature" off.

please add to opt-in for this. 

anybody know a temporarily solution for this? i was searching the about:config for an obvious setting with `urlbar` search term, but nothing usable shows up.

**Comment by GeorgeV220** [comment] 2024-12-11 16:21
> puhh, this thread saved my day ...
> 
> i already was thinking i am too stupid to find the toggle to turn this "feature" off.
> 
> please add to opt-in for this.
> 
> anybody know a temporarily solution for this? i was searching the about:config for an obvious setting with `urlbar` search term, but nothing usable shows up.


You can use this theme (not released yet):  
[GitHub Link](https://github.com/zen-browser/theme-store/pull/863/files)  

I created a `userChrome.css` file in `C:\Users\<user>\AppData\Roaming\zen\Profiles\<profile>\chrome` and pasted the contents of the `chrome.css` file inside. (Restart your browser afterward.)

**Comment by leuchtrakete666** [comment] 2024-12-11 18:12
> > puhh, this thread saved my day ...
> > i already was thinking i am too stupid to find the toggle to turn this "feature" off.
> > please add to opt-in for this.
> > anybody know a temporarily solution for this? i was searching the about:config for an obvious setting with `urlbar` search term, but nothing usable shows up.
> 
> You can use this theme (not released yet): [GitHub Link](https://github.com/zen-browser/theme-store/pull/863/files)
> 
> I created a `userChrome.css` file in `C:\Users\<user>\AppData\Roaming\zen\Profiles\<profile>\chrome` and pasted the contents of the `chrome.css` file inside. (Restart your browser afterward.)

thank you for your effort, but unfortunately your `css` don't resolve the issue. instead of having a centered floating urlbar it is now offset to the right.

the goal should be to revert it completely and have the traditional urlbar. 

 
![Bildschirmfoto_20241211_190727](https://github.com/user-attachments/assets/ad7b90d8-a446-4703-a317-99c74251d52a)

**Comment by GeorgeV220** [comment] 2024-12-11 19:03
Well, if you are not using other mods then it's gonna work.

![image](https://github.com/user-attachments/assets/5e78e9b5-0ea2-4ff3-a50e-522c428835bd)

**Comment by LucasCoppola** [comment] 2024-12-11 19:22
> > I have the same problem, but using the Floating URLbar mod to center it works as a temporary solution until it's fixed, at least on Windows.
> 
> can you upload the mod as zip or something?

I found the CSS code of the Floating URLbar mod that was on my system [Link](https://gist.github.com/LucasCoppola/dc17b9f1be868c6142fea6f7b06e9abc).

**Comment by karamanliev** [comment] 2024-12-11 19:53
> > I'm ngl I thought missing the ability to turn it off was the bug until I read this. Then I grew unsure if the entire design was bugged. So I wrote #3570, will close that because now it's a dupe.
> > It's a shame because this browser was honestly perfect until this decision.
> 
> For real bro. I love this browser. I have no clue why they add changes nobody ask for.

There is some loud minority on reddit which wants a copy paste of Arc browser.

**Comment by leuchtrakete666** [comment] 2024-12-11 20:13
> Well, if you are not using other mods then it's gonna work.
> 
> ![image](https://private-user-images.githubusercontent.com/30936682/394882139-5e78e9b5-0ea2-4ff3-a50e-522c428835bd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM5NDgyMzQsIm5iZiI6MTczMzk0NzkzNCwicGF0aCI6Ii8zMDkzNjY4Mi8zOTQ4ODIxMzktNWU3OGU5YjUtMGVhMi00ZmYzLWE1MGUtNTIyYzQyODgzNWJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjExVDIwMTIxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUwNGE4YjI5YmYwOWYwMDcxY2E0ZGYzMmQ2ZTQxNTdlN2ViOGE0OWU1YjhjZmJiM2Y4MjNiMjMwOGI4Mjg2YzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.9TwlnAdVuZRdwHVVAQNmHKjVPnufq9S-dAYDGBCUIAs)

it's vanilla zen. maybe because it's linux i am using.

**Comment by yoonthegoon** [comment] 2024-12-12 01:18
correct me if i'm wrong but this appears to be a duplicate of https://github.com/zen-browser/desktop/issues/3539

preference to disable this new feature is being added in 1.0.2-b.1 which is now just waiting for approval for release
https://github.com/zen-browser/desktop/actions/runs/12283814398

**Comment by Lokke** [comment] 2024-12-12 01:23
make these look and feel an opt-in or revert these changes made to the address bar, please.
i've chosen Zen browser because it's minimalist and efficient UI, but these extra pixels to move my mouse to a given search result or browsing history entry don't make any sense to me.
also why do we have to click the URL bar, and then double click the text of the URL twice to enter a new address or keyword?

**Comment by CostcoFanboy** [comment] 2024-12-12 01:50
> make these look and feel an opt-in or revert these changes made to the address bar, please. i've chosen Zen browser because it's minimalist and efficient UI, but these extra pixels to move my mouse to a given search result or browsing history entry don't make any sense to me. also why do we have to click the URL bar, and then double click the text of the URL twice to enter a new address or keyword?

It's strange that they didn't create a separate "Zen Labs" section in the settings, similar to "Firefox Labs," to clearly distinguish between the two and provide experimental features as opt-in until they are fully developed.

I understand that Zen hasn't reached its first major version under semantic versioning yet so that may be why.

**Comment by plandem** [comment] 2024-12-12 03:19
This and new icon is so annoying. If you want such drastic changes with UI, then it should be for new users only, while for other to keep as it was and suggestion "wizard" to switch for new settings. Turn ON new ui layouts for old users is the fastest way to lose existing users.

**Comment by stuartmaxwell** [comment] 2024-12-12 09:38
I tried some of the fixes suggested here, but ultimately it was better to roll-back to an older version. You just need to disable auto-updates first, and then install the correct version from here: https://github.com/zen-browser/desktop/releases/tag/1.0.1-a.22

**Comment by aksdb** [comment] 2024-12-12 12:55
I am also taken aback by this change. Zen 1.0.1-alpha looked SO good. It was eye-pleasing. It felt slick, the colors were smooth, all the UI elements were placed gracefully. With the beta it just looks out of place. The default light-theme looks ... off. The search bar jumping away from the location you clicked at feels distracting. It doesn't follow the color theme. A very central element looks completely out of place now.

**Comment by CostcoFanboy** [comment] 2024-12-14 00:20
The best fix I have found is so far is to reinstall Firefox and put `sidebar.verticalTabs` to `true` in `about:config`. 🤷

**Comment by tranquil-tr0** [comment] 2024-12-16 03:48
If I am understanding the issue correctly, you should be able to revert this behavior in settings by finding the "General settings for the URL bar" setting and then setting the value in "Behavior" to "Normal" rather than "Floating ..."

**Comment by syscat29** [comment] 2024-12-16 03:52
> If I am understanding the issue correctly, you should be able to revert this behavior in settings by finding the "General settings for the URL bar" setting and then setting the value in "Behavior" to "Normal" rather than "Floating ..."

Indeed. Settings > Look and Feel > Zen URL Bar > Choose desired behavior

**Comment by stuartmaxwell** [comment] 2024-12-16 03:54
That preference was only added in 1.0.2-b.2, presumably to fix the complaints raised here and in other issues.

**Closed as completed** 2024-12-21 22:27 UTC
