### ISSUE TITLE
Antivirus deletes the app

### ISSUE THREAD

**Issue by abelendeshaw** [zen-browser/desktop#2291] opened 2024-10-23 10:44 UTC
### Captchas

- [x] I have read the instructions.
- [x] I have searched existing issues and avoided creating duplicates.
- [x] I am not filing an enhancement request.

### What happened?

While using zen browser after installation it works just fine for first start up but after that my antivirus detects it as a torjan and removes it completely and after reinstallation it just doesn't connect to the internet, no tabs load, and a new fresh install after removing all app data just gets it deleted again. 

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.12

### What platform are you seeing the problem on?

Windows

**Comment by mr-cheffy** [comment] 2024-10-26 16:32
Duplicate of https://github.com/zen-browser/desktop/issues/37. Please follow the discussion there

**Closed as completed by mr-cheffy** 2024-10-26 16:32 UTC
