### ISSUE TITLE
Spacing between icons and tabs in the tab bar

### ISSUE THREAD

**Issue by litaniecontrelapeur** [zen-browser/desktop#2869] opened 2024-11-11 03:34 UTC
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

![image](https://github.com/user-attachments/assets/6e81609c-4276-41c3-9a72-e29433c13c9b)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.19

### What platform are you seeing the problem on?

Windows

**Comment by universish** [comment] 2024-11-11 03:50
It says “Default Workspaces” or the name of the currently open Workspaces. By default the Workspaces logo does not appear when the sidebar is hidden unless you have selected the icon. It looks like a blank space. 
This is not a bug. 
Please explain if the problem you are experiencing is real. If not, close the issue.

**Comment by litaniecontrelapeur** [comment] 2024-11-11 04:12
I do not use workspaces (deactivated), maybe that's why

**Comment by litaniecontrelapeur** [comment] 2024-11-11 04:18
> It says “Default Workspaces” or the name of the currently open Workspaces. By default the Workspaces logo does not appear when the sidebar is hidden unless you have selected the icon. It looks like a blank space. This is not a bug. Please explain if the problem you are experiencing is real. If not, close the issue.

when I activate workspaces effectively a D is put in that blank space, but even so, restarting and deactivating again, the space is maintained, just like the image I posted

**Comment by ell1010** [comment] 2024-11-11 16:06
![image](https://github.com/user-attachments/assets/61e6ee2a-41e3-486f-86d1-02cb5aaed3e6)
same issue here. Gap at the top of the tab list (workspaces disabled)

**Comment by antikovt** [comment] 2024-11-11 21:55
Yep, when workspaces are disabled the gap is still there and looks bad.

Also I don't see why it shouldn't be possible to move the workspaces button around, to either the bottom of the tabbar or even to the toolbar.

**Comment by RicardsR** [comment] 2024-11-19 21:22
Yep, having the same issue here. Couple of update ago (I think at the start of November or end of October) this wasn't an issue for me. When ever the reworked "Show New Tab Button on Tab List" appeared, after that update this issue appeared for me. Turning this feature off to hide the new tab button but doesn't help with the gap. This seems to be a specific issue with the "Workspaces" functionality.
The "New Tab" icon in the screenshot is placed by me while customizing the tool bar to showcase the gap that was added. Before the update I had the same configuration but without the gap.

![image](https://github.com/user-attachments/assets/2fad5bef-16fd-40ea-b609-4aaef1b6f0ea)

**Comment by yoonthegoon** [comment] 2024-12-12 00:52
+1

**Comment by universish** [comment] 2024-12-12 05:29
@yoonthegoon @RicardsR @antikovt @ell1010 
Please specify your OS edition (e.g. Windows 11 Pro), your OS version (e.g. for windows 11: 24H2) (if linux, your distribution and distribution version) and your zen browser version.

**Comment by universish** [comment] 2024-12-12 05:32
@litaniecontrelapeur @yoonthegoon @RicardsR @antikovt @ell1010 
Could you try this:
Right click on the toolbar --> Customize toolbar --> Click and drag the space and drop it into the overflow menu below. 
Please write down what happens when you do this.

**Comment by yoonthegoon** [comment] 2024-12-12 06:23
OS: macOS 15.1.1 24B91 arm64

I've tried dragging it, but it simply selects and moves my whole window when I drag it. There isn't an element there. It's likely an empty space that's been added for the purpose of giving the workspace icon enough space to not be crowded.

**Comment by litaniecontrelapeur** [comment] 2024-12-12 14:57
> @litaniecontrelapeur @yoonthegoon @RicardsR @antikovt @ell1010 Could you try this: Right click on the toolbar --> Customize toolbar --> Click and drag the space and drop it into the overflow menu below. Please write down what happens when you do this.

doesn't work

**Closed as completed** 2024-12-27 16:10 UTC

**Comment by yoonthegoon** [comment] 2024-12-27 16:13
is this closed as resolved or unresolved?

**Comment by RicardsR** [comment] 2024-12-27 16:26
After checking out the issue now, seems like its fixed as of the latest update.

> is this closed as resolved or unresolved?
