### ISSUE TITLE
sidebar becomes unresponsive when moving tabs to other workspaces

### ISSUE THREAD

**Issue by Miyazono1** [zen-browser/desktop#2441] opened 2024-10-31 04:32 UTC
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

when moving tabs to another workspace, the entire sidebar becomes unresponsive until you reopen zen. right clicking tabs on the bar, or anywhere on the sidebar at all does nothing, and only fixes itself if you restart zen.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1 a15

### What platform are you seeing the problem on?

Windows

**Comment by yhansy** [comment] 2024-10-31 08:08
Same as https://github.com/zen-browser/desktop/issues/2343

**Comment by salamijason** [comment] 2024-11-10 03:24
Closing this one cuz dupe of the issue mentioned by above user. Thank you!

**Closed as completed by salamijason** 2024-11-10 03:24 UTC
Labels: Bug
