### ISSUE TITLE
PDF font's not showing

### ISSUE THREAD

**Issue by Iampooo** [zen-browser/desktop#3799] opened 2024-12-16 00:15 UTC
### Captchas

- [x] I have read the instructions.
- [x] I have searched existing issues and avoided creating duplicates.
- [x] I am not filing an enhancement request.

### What happened?

can see several font in pdf 
![image](https://github.com/user-attachments/assets/072f56ea-9761-4001-8432-e0f536bd02e2)

### Reproducible?

- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2

### What platform are you seeing the problem on?

Windows

**Comment by djorium** [comment] 2024-12-16 01:24
Duplicate of https://github.com/zen-browser/desktop/issues/3238

**Closed as completed by djorium** 2024-12-16 01:24 UTC
Labels: Bug
