### ISSUE TITLE
Full screen bug

### ISSUE THREAD

**Issue by rajath-2** [zen-browser/desktop#3269] opened 2024-11-28 14:54 UTC
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

videos dont go into complete full screen leaving a bar at the top on the latest twilight build
![image](https://github.com/user-attachments/assets/02023bd1-5031-4514-b219-5995b0dda317)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-t.20

### What platform are you seeing the problem on?

Windows

**Comment by saltymouse** [comment] 2024-12-19 05:57
Same issue on macOS 15.1.1 with Zen Browser 1.0.2-b.2 (Firefox 133.0.3) (aarch64).
Zen's top frame border (seen as faded blue bar in my screenshot, above YouTube's title text) is visible on any full-screen video (YouTube, Vimeo, etc.).
![zen-top-border-full-yt2](https://github.com/user-attachments/assets/065dabf8-8e61-4482-a7ac-b2e67f5d41f7)

**Comment by spectro-vi** [comment] 2024-12-20 01:25
Same issue on MacOS 15.1.1 with Zen Browser 1.02-b.3 (Firefox 133.0.3) (aarch64). However, it only appears when using single toolbar layout. With multiple toolbars or collapsed toolbars, the strip is no longer visible.

**Comment by spectro-vi** [comment] 2024-12-21 01:40
This seems to be a duplicate of https://github.com/zen-browser/desktop/issues/3792#issue-2740802880

**Closed as completed** 2024-12-22 09:39 UTC
Labels: Bug, twilight
