### ISSUE TITLE
When you close the browser and reopen it, all tabs are present

### ISSUE THREAD

**Issue by senbaby114** [zen-browser/desktop#2607] opened 2024-11-03 14:07 UTC
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I want to close the browser and reopen it, and all the tabs are closed

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.17

### What platform are you seeing the problem on?

Windows

**Comment by VSparl** [comment] 2024-11-03 15:48
Have you unchecked this option?
![image](https://github.com/user-attachments/assets/c2bee404-b4dc-493e-8d58-1d892afb40af)
I have it checked because I want to keep my tabs but if you don't want to keep them you should be able to uncheck the box.

If you're wondering how to get here:

1. Type `about:preferences` into the URL bar
2. you should see this as the first thing that pops up

**Comment by ilusi0n** [comment] 2024-11-04 20:51
It seems a duplicate of  https://github.com/zen-browser/desktop/issues/2601
I was able to reproduce this on a new install (linux and macOS). I was able to fix it creating a `user.js`in the profile folder with `user_pref("browser.startup.page", 3);`

**Closed as not planned** 2024-12-12 16:09 UTC
Labels: Bug
