### ISSUE TITLE
CMD + W not working

### ISSUE THREAD

**Issue by marcorubiol** [zen-browser/desktop#727] opened 2024-08-26 05:33 UTC
### What happened?

I try to use CMD + W to close a tab, but it is not working. 
When I do it through the menu, it works, and I can see that the shortcut is assigned to the close tab operation. I also tried disabling Zen Browser's default keyboard shortcuts and adding it myself, but still no luck. 
Please note that this shortcut works in other browsers without any conflict (including Firefox).

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0

### Severity impact

Critical

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by n7itro** [comment] 2024-08-26 06:25
Possible duplicate of #376 or #283

**Comment by Iziram** [comment] 2024-08-26 06:28
CMD + W working fine on my mac. (Zen 1.0.0-a.29 macOs aarch64)

**Comment by JoshuaKeegan3** [comment] 2024-08-26 06:44
Works fine on my mac as well

**Comment by marcorubiol** [comment] 2024-08-27 17:06
I don't know if can be related with the language if my keyboard. Mine is in spanish and I suspect that Carlos' one will be also in spanish.

**Comment by marcorubiol** [comment] 2024-08-28 14:36
> > I don't know if can be related with the language if my keyboard. Mine is in spanish and I suspect that Carlos' one will be also in spanish.
> 
> I'm Brazilian, actually 😅 But my keyboard and OS language are both English - US.
> 
> The CMD + W shortcut is working now since I changed other shortcuts to use ALT + Shift + Key instead of the defaults

Ups. Sorry. Trying to help

**Comment by mauro-balades** [comment] 2024-08-29 19:43
This has been reported multiple times, im gonna close to do some cleaning up, you can follow the issues @n7itro linked 👍🏽

**Closed by mauro-balades** 2024-08-29 19:43 UTC
Labels: kind: low severity
