### ISSUE TITLE
Font size is too small on tabs

### ISSUE THREAD

**Issue by nazmiyigitefe** [zen-browser/desktop#1580] opened 2024-09-21 12:26 UTC
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

In my Windows device font size is a little bit weird, they're normal on my MacOS device.

![Ekran görüntüsü 2024-09-21 152411](https://github.com/user-attachments/assets/9743d04d-8c0d-4aad-a480-b3602826b688)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a2

### What platform are you seeing the problem on?

Windows

**Comment by n7itro** [comment] 2024-09-21 14:52
Duplicate of #1518, #1524, #1544

Please actually verify that your issue is not a duplicate before posting.

**Closed by n7itro** 2024-09-21 14:52 UTC
