### ISSUE TITLE
New Tab Pop-Up not fully visible

### ISSUE THREAD

**Issue by jdeck95** [zen-browser/desktop#2112] opened 2024-10-15 08:09 UTC
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

The Pop-Up off the "New Tab"-Button is cut off and not fully displayed. It is only happening, when the sidebar is expanded. When the sidebar is collapsed it works without problems.

<img width="279" alt="Bildschirmfoto 2024-10-15 um 10 07 13" src="https://github.com/user-attachments/assets/f45f2251-6e5a-4904-a40e-e0900d004aea">

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.9 (64-bit)

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by sjclayton** [comment] 2024-10-15 08:27
May be a macOS specific issue, as I cannot reproduce this on Linux running 1.0.1-a.9 

EDIT: OS - Arch Linux using KDE Plasma 6.2

**Comment by AnarionBe** [comment] 2024-10-15 13:03
It also happen on Debian 12

**Comment by RayZ3R0** [comment] 2024-10-30 06:42
That's weird, I cannot reproduce this. @AnarionBe and @jdeck95 Can you try this on the latest version a.14 and see if it still happens

**Comment by AnarionBe** [comment] 2024-10-30 08:03
@RayZ3R0 Worked as expected on a.14. Thanks

**Comment by RayZ3R0** [comment] 2024-10-30 08:47
Alright then, I'll be closing this issue. Should be fixed for jdeck95 too. If it is not, please reopen.

**Closed as completed by RayZ3R0** 2024-10-30 08:47 UTC
