### ISSUE TITLE
new tab icon and button disappeared after update

### ISSUE THREAD

**Issue by makalin** [zen-browser/desktop#1649] opened 2024-09-23 18:43 UTC
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

new tab icon and button disappeared after 1.0.1-a.3 (64-bit) update also bottom icons were fine what happened to them?

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.3 (64-bit)

### What platform are you seeing the problem on?

macOS - Intel, Windows

**Comment by n7itro** [comment] 2024-09-23 18:52
Duplicate of #1640

**Closed by n7itro** 2024-09-23 18:52 UTC
