### ISSUE TITLE
distorted fonts apearing in google docs 

### ISSUE THREAD

**Issue by DDiegoLopez** [zen-browser/desktop#3733] opened 2024-12-14 00:56 UTC
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

The text in Google Docs looks distorted, but when you select the text, it corrects to how it should normally look; this does not happen in other browsers; I have already tried in Firefox, Floorp, Edge, and Brave.

**How it looks**
![Captura de pantalla 2024-12-13 185103](https://github.com/user-attachments/assets/6409ae7b-ba60-4000-9d9a-d940ae2a8498)

**when select text**
![Captura de pantalla 2024-12-13 185225](https://github.com/user-attachments/assets/575c4bc8-2bd2-4c90-83fd-175b91f692b8)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.1

### What platform are you seeing the problem on?

Windows

**Comment by JSGRD22** [comment] 2024-12-17 13:37
Duplicate of #3238 (same underlying bug)

**Comment by syscat29** [comment] 2024-12-17 14:35
Closing this, let's keep it all in one thread #3541

**Closed as completed by syscat29** 2024-12-17 14:35 UTC
Labels: Bug
