### ISSUE TITLE
Pinning a tab upon browser startup closes the previously pinned tabs

### ISSUE THREAD

**Issue by BoscoDomingo** [zen-browser/desktop#2949] opened 2024-11-12 10:56 UTC
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Whenever you pin a tab, all the existing ones get closed and replaced. This happens consistently when starting the browser again

https://github.com/user-attachments/assets/ae399b5c-e001-4676-bae4-25ac9f5e438f

(Sorry for the music, I didn't realise it was unmuted)

![image](https://github.com/user-attachments/assets/dd4a5c29-17f5-496e-bbb9-665abe3025d3)
As you can see, the Google and Improved Initiative tabs are there (ignore the New Tabs, I closed those myself manually)

Pinning more tabs after that works fine. However, if you pin another one after restarting the browser, all existing pins are closed. You can then reopen them with the shortcut or via UI.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.19

### What platform are you seeing the problem on?

Windows

**Comment by Rexxyyy** [comment] 2024-11-12 10:59
i cant re-create it my zen, it looks like its just on your case. Can you please send logs?

**Comment by BoscoDomingo** [comment] 2024-11-12 11:01
@Rexxyyy Sure, mind letting me know how to attach them? I haven't seen a guide

**Comment by Rexxyyy** [comment] 2024-11-12 11:02
> @Rexxyyy Sure, mind letting me know how to attach them? I haven't seen a guide

edit this threads and paste logs

**Comment by BoscoDomingo** [comment] 2024-11-12 11:03
@Rexxyyy Sorry my bad, I meant how to get said logs. Is there an option in the settings, must I run a command...?

**Comment by universish** [comment] 2024-11-12 15:29
The problem in the url you have bhaset and your problem are different problems.  You have created an issue with the pinned tab. The other issue you mentioned is related to essentials. Essentials are the basic pinned tabs of all workspaces, open in all workspaces and open in all windows. 
A pinned tab is only pinned and opened in the workspace you have pinned. It is not fixed in other workspaces. If you open a new window, it is also fixed in the new window only in the workspace you have pinned, not in others.

**Comment by universish** [comment] 2024-11-12 15:37
I could not reproduce this bug in fedora.

**Comment by BoscoDomingo** [comment] 2024-11-12 22:27
I ended up going for the installed version (used to use the Portable) and reverting to a.17 as well as using a completely fresh profile. Gonna wait for a bit for more stability in terms of Essentials and pinned tabs

**Comment by mr-cheffy** [comment] 2024-12-23 16:05
Duplicate of https://github.com/zen-browser/desktop/issues/2989

**Closed as completed by mr-cheffy** 2024-12-23 16:05 UTC
Labels: Bug
