### ISSUE TITLE
Live streaming from you tube and twitch are not working on zen 

### ISSUE THREAD

**Issue by Naveenv01** [zen-browser/desktop#481] opened 2024-08-23 13:35 UTC
### What happened?

Live streaming from you tube and twitch are not working on Ubuntu 24 04 

screen shot attached below
![image](https://github.com/user-attachments/assets/309b0913-5e71-47eb-a4b0-0fe0c4e1ff9d)

![image](https://github.com/user-attachments/assets/e3c68838-c5f9-4d98-b5d6-3e05574e509f)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.28 (2024-08-22)

### Severity impact

Critical

### What platform are you seeing the problem on?

Linux

**Comment by Moshyfawn** [comment] 2024-08-24 02:18
Seems like a duplicate of #477

**Closed** 2024-08-24 10:36 UTC
Labels: kind: critical severity
