### ISSUE TITLE
Pinned tabs change their position

### ISSUE THREAD

**Issue by ploydi** [zen-browser/desktop#2020] opened 2024-10-11 11:48 UTC
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

If you have a pinned tab open when you close the browser, the next time you open the browser, the pinned tab is moved to the first place.

Expected behavior: Pinned tabs remain in their places.

https://github.com/user-attachments/assets/06e58bdb-b6ea-4328-a98f-8c706e3bd954

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.8

### What platform are you seeing the problem on?

Linux

**Comment by sjclayton** [comment] 2024-10-12 10:50
~~Cannot reproduce this, also on Linux running 1.0.1-a.8,  I am having the expected behaviour in this case.~~

Confirming this behaviour as well, but it may be related to another issue... see reference below.

**Comment by Tc-001** [comment] 2024-10-12 17:27
Can reproduce. This happens if you have "Open previous windows and tabs" enabled in startup.
For a workaround you can disable it and the order should remain the same between openings.

**Comment by sjclayton** [comment] 2024-10-12 19:38
Maybe related to #1822

**Comment by sjclayton** [comment] 2024-10-12 19:41
@ploydi 

What happens if the pinned tab you have selected is the first in order? Does this behaviour happen still or no?

**Comment by ploydi** [comment] 2024-10-12 21:28
> @ploydi
> 
> What happens if the pinned tab you have selected is the first in order? Does this behaviour happen still or no?

No, it works correctly in this case

> Can reproduce. This happens if you have "Open previous windows and tabs" enabled in startup. For a workaround you can disable it and the order should remain the same between openings.

But then all tabs in workspaces will be closed  😢

> Maybe related to #1822

Hmm, this behavior has not occurred to me

**Comment by ploydi** [comment] 2024-10-12 21:30
> Can reproduce. This happens if you have "Open previous windows and tabs" enabled in startup. For a workaround you can disable it and the order should remain the same between openings.

But then all tabs in workspaces will be closed  😢

**Comment by ploydi** [comment] 2024-10-12 21:33
> Maybe related to #1822

Hmm, this behavior has not occurred to me

**Comment by sjclayton** [comment] 2024-10-12 21:50
> > @ploydi
> > What happens if the pinned tab you have selected is the first in order? Does this behaviour happen still or no?
> 
> No, it works correctly in this case

This is the same behaviour as in the issue I linked, the first pinned tab is acting the same as the first tab in the regular tab list in this case, and if the second one is selected it is switched with the first one.

> > Maybe related to #1822
> 
> Hmm, this behavior has not occurred to me

If you select any other tab (not pinned), when you relaunch Zen check which tab is selected? I bet you it's not the same as the one you last had open and instead it's the one below it that is active.

**Comment by ploydi** [comment] 2024-10-12 22:27
> > > @ploydi
> > > What happens if the pinned tab you have selected is the first in order? Does this behaviour happen still or no?
> > 
> > 
> > No, it works correctly in this case
> 
> This is the same behaviour as in the issue I linked, the first pinned tab is acting the same as the first tab in the regular tab list in this case, and if the second one is selected it is switched with the first one.
> 
> > > Maybe related to #1822
> > 
> > 
> > Hmm, this behavior has not occurred to me
> 
> If you select any other tab (not pinned), when you relaunch Zen check which tab is selected? I bet you it's not the same as the one you last had open and instead it's the one below it that is active.

Ohh, yeah, you're right, I just noticed this behavior.

**Comment by RayZ3R0** [comment] 2024-10-30 15:53
Cannot reproduce this. Does this still happen on latest version? (a.14 as of this comment)

**Comment by ploydi** [comment] 2024-10-30 17:37
> Cannot reproduce this. Does this still happen on latest version? (a.14 as of this comment)

Yes, it still happens in the latest version (a.14): with mods turned off, with mods removed and with a brand new profile

**Comment by RayZ3R0** [comment] 2024-10-30 17:54
Ok yeah, I just tried again and it does happen. We'll look into it

**Comment by kristijanribaric** [comment] 2024-10-31 21:10
Fixed in 1.0.1-a.16. Thanks!

**Closed by kristijanribaric** 2024-10-31 21:10 UTC
