### ISSUE TITLE
Essentials tabs not working in new windows

### ISSUE THREAD

**Issue by plankobostjan** [zen-browser/desktop#3012] opened 2024-11-14 11:07 UTC
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

When I open a new window (either normal or private) essentials tabs (the grid) are there, but all of them are empty and not loading.
![image](https://github.com/user-attachments/assets/4134a399-c429-40f5-bfe8-514a0529ff85)

Additionally, I think essentials tabs should not be transferred to private windows. 

### Reproducible?

- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.19

### What platform are you seeing the problem on?

Linux, Windows

**Comment by neogeographica** [comment] 2024-11-21 17:37
FWIW, I experienced this same behavior (on Linux and macOS) with pinned tabs that existed from before the "essentials" feature, which I had moved to essentials after upgrading Zen.

I unpinned all of those tabs now and then I directly added them all back into essentials; now they seem to behave correctly, i.e. they appear properly in new windows.

**Comment by JSGRD22** [comment] 2024-12-20 05:11
This should be fixed in the latest release

**Comment by mr-cheffy** [comment] 2024-12-23 16:05
Duplicate of https://github.com/zen-browser/desktop/issues/2989

**Closed as completed by mr-cheffy** 2024-12-23 16:05 UTC
Labels: Bug
