### ISSUE TITLE
Sidebar reaches Top and side when in compact mode 

### ISSUE THREAD

**Issue by davidbecker808** [zen-browser/desktop#1766] opened 2024-09-27 10:51 UTC
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

![grafik](https://github.com/user-attachments/assets/b1159de9-3a81-4064-98f5-67e45cddf8eb)
when using the Tabs on the right, the Sidebar reaches the top and the side and has no padding

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

Version 1.0.1-a.5 (64-bit)

### What platform are you seeing the problem on?

Windows

**Comment by KarimElsayad247** [comment] 2024-09-27 13:31
Duplicate of https://github.com/zen-browser/desktop/issues/1716

Though I prefer the title on this one.

**Comment by mr-cheffy** [comment] 2024-10-12 19:55
This is fixed now, thanks!

**Closed** 2024-10-12 19:55 UTC
