### ISSUE TITLE
Web panels get unloaded / reloaded on every toggle

### ISSUE THREAD

**Issue by sjclayton** [zen-browser/desktop#2022] opened 2024-10-11 12:56 UTC
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Every time I use the sidebar button or keyboard shortcut to toggle the web panel, all panels get reloaded thus losing their last state. This was not the case with 1.0.1-a.7

**Expected result:**

When the web panel is toggled the panels open to the last state they were in previously.

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.8

### What platform are you seeing the problem on?

Linux

**Comment by Axenide** [comment] 2024-10-11 18:15
This is happening to me too but every web panel unloads/reloads.

Edit: Just noticed that the panels stay loaded until I reopen the sidebar.

**Comment by sjclayton** [comment] 2024-10-11 18:34
@Axenide 

You appear to be correct, I don't know why it appeared that only the last active panel got unloaded/reloaded on toggle. It is definitely all of them.

EDIT: Updated issue to correctly align with this behaviour.

**Comment by cimarronline** [comment] 2024-10-12 12:49
Yes, I can confirm this too. The web panel feature is really nice, especially because it keeps its state, so I hope this issue can be resolved. (Great work on Zen, I'm promoting it to my friends and in tech forums.)

**Comment by TheJPMZ** [comment] 2024-10-15 11:29
This issue is also present on Windows 11, 1.0.1-a.9

**Comment by JanDubcak** [comment] 2024-10-16 09:21
Issue also for me. I'd love sidebar to keep it's state so that my video is not interrupted every time I open sidebar with ctrl+p.
Device:
Windows 11 Enterprise: 22631.4169
Z2n: 1.0.1-a.10 (Firefox 130.0) (64-bit)

Btw: Thanks to Zen staff for modding firefox to the thing I always wanted. Firefox with split view, vertical tabs, and workspaces. This is a dream come true for me.

**Comment by Axenide** [comment] 2024-10-21 04:52
This issue persists in Zen 1.0.1-a.12

**Comment by CrisisModel** [comment] 2024-10-28 15:12
Issue still exists on Zen 1.0.1-a.14.

**Comment by salamijason** [comment] 2024-10-30 10:22
A similar issue came up in the discord where the opening the sidepanel after closing them wouldn't go to the last opened tab but the splash screen.

Disabling this option in the settings fixed it and I would doing that for the time being.
![Image](https://github.com/user-attachments/assets/363be5d6-e075-42d7-a392-d7a9dc1d0c73)


However, even if the splash screen was first shown when reopening the sidepanel, the tabs that were previously opened in them retained their state. I was not able to reproduce the following behavior: 

> every web panel unloads/reloads.

If possible please do provide screen recordings of what you mean so we can look deeper into the issue.

**Comment by TheJPMZ** [comment] 2024-10-30 18:25
I attach a screen recording of the issue, which persists on Version 1.0.1-a.14 (64-bit) for Windows 11. 

On the recording you will see:
- Youtube music refreshing when reopening the panel with and without the option "Close the panel..." 
- A timer restarting when reopening the panel

https://github.com/user-attachments/assets/182e218d-1481-49b0-b967-0a8648273e92

**Comment by orswn** [comment] 2024-10-31 03:48
After investigating with the browser debugger, I identified that the page unloads specifically at this line: [ZenSidebarManager.mjs#L601](https://github.com/zen-browser/desktop/blob/d24a9a2583eb4b7c9021d3cb373b7701f87dad28/src/browser/base/zen-components/ZenSidebarManager.mjs#L601).

To confirm, I commented out this line, and the web panel remained loaded as expected.

**Comment by sjclayton** [comment] 2024-11-11 05:11
Issue still persists on 1.0.1-a.19

**Comment by XCraftMC23** [comment] 2024-12-02 21:24
Still an issue on a.22. This is probably the most prominent bug for me personally, the sidebar is such a nice addition but I essentially can't use it without it getting in the way constantly.

**Comment by cimarronline** [comment] 2024-12-02 21:34
This seems to be fixed on the Twilight build (thanks!). The side panel is not reloading every time it is toggled. It looks like it's [commit 6d41232](https://github.com/zen-browser/desktop/commit/6d41232a3eeea266038703cc1282cbab8799c576). So it should be in the next release.

**Comment by XCraftMC23** [comment] 2024-12-07 07:34
After some further troubleshooting, I've found that it works for me on the regular Twilight build, but not on the AVX2 build. If I remove the avx2 version of twilight and install the normal version, then it works as intended.

I'm on Arch using the builds provided on the AUR, which seem to have the most recent twilight builds.
I cannot seem to be able to build zen myself, which is why I am using the AUR versions for troubleshooting.

**Comment by salamijason** [comment] 2024-12-10 12:41
The twilight build is ahead by a bit compared to the alpha build so we should probably wait until the beta release (very soon as of this comment) to see if it's fixed then. Please let me know if you encounter the issue again on the next release.

**Comment by Axenide** [comment] 2024-12-10 17:42
I tested Twilight AVX2 and web panels work as intended.

**Comment by TheJPMZ** [comment] 2024-12-12 05:04
This is fixed in version 1.0.2-b.0 (64-bit) Windows 11

**Comment by salamijason** [comment] 2024-12-15 08:36
Looks like the bug is gone now! Will be closing this issue now but feel free to re-open if you still face the issue. Thanks for your input!

**Closed by salamijason** 2024-12-15 08:36 UTC
