### ISSUE TITLE
Close button interaction area is incorrect while in Compact Mode and 'Tabs on the right' option toggled on

### ISSUE THREAD

**Issue by Broome92** [zen-browser/desktop#3814] opened 2024-12-16 09:50 UTC
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

While Zen Browser is in Compact Mode, if you have the option 'Tabs on the right' on, the Close button can only be properly clicked on its leftmost edge.

![zen_sR4cM2zUgD](https://github.com/user-attachments/assets/bacbb22d-d2a5-4891-a7e3-1a46f5482ca7)

![zen_2Kmo8vMUDh](https://github.com/user-attachments/assets/66572608-42a7-425b-8ad8-970fe07334b1)

Attempting to click anywhere else within the Close button does nothing.

While not in compact mode, the entire close button is clickable, and properly closes the browser.

This doesn't appear to happen at all when tabs are on the left.

I also tested with all mods and extensions off.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.2 (Firefox 133.0.3) (64-bit)

### What platform are you seeing the problem on?

Windows

**Comment by NTICompass** [comment] 2024-12-16 12:53
Duplicate of #3571

**Closed as completed** 2024-12-16 22:30 UTC
Labels: Bug
