### ISSUE TITLE
PDF viewer renders text incorrectly

### ISSUE THREAD

**Issue by Robot-Inventor** [zen-browser/desktop#3238] opened 2024-11-28 02:58 UTC
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Some text in the PDF file is not rendered correctly. This issue does not occur with all text and does not appear in Firefox.

As an example, I have attached screenshots showing the rendering issue when displaying the PDF file from the following URL.

https://www.stat.go.jp/data/jyutaku/2023/pdf/g_kekka.pdf

Zen Browser:
![Zen Browser](https://github.com/user-attachments/assets/a2c66e62-0889-49d7-9c2e-e0f84e2a252a)

Firefox:
![Firefox](https://github.com/user-attachments/assets/8cfd8fca-b01f-4265-a511-61d4463b29e0)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.20

### What platform are you seeing the problem on?

Windows

**Comment by jacobselbo** [comment] 2024-12-10 15:32
Issue is still present on 1.0.2-b.0, and appears to have gotten worse. PDF displayed correctly on 1.0.1-a.20, but is now rendered incorrectly on 1.0.2-b.0.

Zen Browser 1.0.2-b.0:
![image](https://github.com/user-attachments/assets/70d27cd0-f53f-43ee-85d6-6627ccc350f2)

Firefox:
![image](https://github.com/user-attachments/assets/7636af7f-77fa-4add-8162-2b55ca6c7f34)

**Comment by Slusho64** [comment] 2024-12-10 17:38
I've encountered this as well at [https://tamsang-nyc.com/wp-content/uploads/2024/01/PDF1-7.pdf](https://tamsang-nyc.com/wp-content/uploads/2024/01/PDF1-7.pdf)

Zen:
![Screenshot 2024-12-10 122735](https://github.com/user-attachments/assets/1ce67ad3-fb51-4f6e-a4c8-39ffb70292f6)

Firefox:
![Screenshot 2024-12-10 123814](https://github.com/user-attachments/assets/f906cee4-bfb4-461d-9af2-d5401b94623d)

**Comment by urbanlutz** [comment] 2024-12-11 07:48
same issue here. Potential duplicated issue to #3537.

**Comment by JSGRD22** [comment] 2024-12-11 14:29
Update: I seem to own an installation where this issue isn't present. Will investigate when I have time.

Edit: I have diffed prefs.js and there is nothing to indicate there should be a difference in font rendering between the two machines, so this likely doesn't have a "simple fix".

Edit 2: I tested on another machine and could not reproduce the bug either. I do know that the machines where the bug is not present are a laptop with an integrated amd radeon GPU and a desktop with a discrete nvidia GPU, while the machine where the bug is present is a dual GPU work laptop containing an integrated intel iris xe GPU and a nvidia discrete GPU. Does everyone else having this issue have a similar setup, or is this just a coincidence?

**Comment by jacobselbo** [comment] 2024-12-11 17:53
Coincidence, I have an integrated GPU on a laptop and the issue exists. #3537 brings up a good point though, I tried zooming out the pdf to 60% and the issue disappears with a pdf I showed. However the pdf by Slusho64 seems to not be fixed with zooming in/out

**Comment by m7medVision** [comment] 2024-12-14 16:20
I have same issue and it is English latter 
![image](https://github.com/user-attachments/assets/ebfeeae9-1e61-4daa-a2c1-298cd8f08e63)

**Comment by JSGRD22** [comment] 2024-12-17 13:37
This is the earliest issue I could find about this problem and duplicates should be linked here, so I’ll cover some extra info:
- This issue is also present on google docs
- Disabling hardware acceleration fixes this issue
- Pinning “repair text encoding” to the toolbar via customise toolbar and clicking it fixes this issue, at least for me

**Comment by Slusho64** [comment] 2024-12-17 14:27
Thanks, disabling hardware acceleration fixed it for me (it's in Settings > General > Performance > uncheck "Use recommended performance settings").

**Comment by syscat29** [comment] 2024-12-17 14:36
Closing this, let's keep it all in one thread #3541

**Closed as completed by syscat29** 2024-12-17 14:36 UTC
Labels: Bug
