### ISSUE TITLE
Sidebar problem

### ISSUE THREAD

**Issue by akcayaksungur** [zen-browser/desktop#1916] opened 2024-10-05 17:53 UTC
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

If the history tab is opened while the sidebar is on the right side, the sidebar moves itself back to the left side and cannot be moved until the browser is restarted

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.7 (64 bit)

### What platform are you seeing the problem on?

Linux

**Comment by mauro-balades** [comment] 2024-10-06 20:58
Could you send a screenshot or video to showcase this issue?

**Comment by akcayaksungur** [comment] 2024-10-07 14:10
I forgot to mention. This error occurs when you open history with Ctrl+H shortcut or open firefox's own sidebar

https://github.com/user-attachments/assets/8c567741-0cf6-4a7d-a008-dcf51c406244

**Comment by BrhmDev** [comment] 2024-10-11 16:23
I cannot reproduce this. Is this still a problem?

**Comment by salamijason** [comment] 2024-10-31 18:14
Can't reproduce this on latest version here either. Since author hasn't replied in weeks, will close the issue.

**Closed by salamijason** 2024-10-31 18:14 UTC

**Comment by akcayaksungur** [comment] 2024-10-31 19:33
My mistake, I apologize. Problem solved thanks.
