### ISSUE TITLE
"Zen Glance" Preview Window Blank After Opening and Closing New Glance Window

### ISSUE THREAD

**Issue by sasank-pankam** [zen-browser/desktop#2720] opened 2024-11-07 13:27 UTC
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Description: When using the "Glance" feature in Zen Browser, I observed an issue where previously loaded tabs turn blank after expanding one Glance preview to full screen, then opening and closing another Glance preview. The previously loaded tab displays only the default theme color rather than the content.

Steps to Reproduce:

    Open Zen Browser and navigate to any webpage.
    Use Ctrl + Click on a link to open it in a Glance preview window.
    Expand the Glance window to full screen.
    Open another Glance preview (by Ctrl + Click on a different link).
    Close the second Glance preview.

Expected Behavior:  The previously loaded tab should retain its content, unaffected by the actions in new Glance windows.

Observed Behavior: After closing the second Glance preview, the previously loaded tab goes blank, displaying only the default theme color instead of its content. (However, the preview of the tab in the tab switcher does not go blank.)

Environment:

    Browser Version: 1.0.1-a.17
    Operating System:  Linux archlinux 6.11.4-arch2-1

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.17

### What platform are you seeing the problem on?

Linux

**Comment by RayZ3R0** [comment] 2024-11-07 13:39
Duplicate of #2575 and should be fixed in next update

**Closed as completed by RayZ3R0** 2024-11-07 13:39 UTC
Labels: Bug

**Comment by sasank-pankam** [comment] 2024-11-11 16:44
i couldn't find the bug when i want to report the bug,
sorry for the duplicate issue.
