### ISSUE TITLE
After 1.0.2-b.3 update, with compact mode enabled and multiple toolbars chosen, mouse movement can't expand the tab view (Linux).

### ISSUE THREAD

**Issue by Klusio19** [zen-browser/desktop#3905] opened 2024-12-20 12:11 UTC
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

After newest update 1.0.2-b.3, when compact mode is enabled, and `multiple toolbars` is chosen, I can't easily make the sidebar expand by the mouse movement. If I choose `single toolbar`, issue does not exist. (Shown in the video) Windows version is working fine too.

OS: Arch Linux
DE: KDE Plasma 6.2.4
WM: KWin (Wayland)

https://github.com/user-attachments/assets/6ee926c5-611f-4bb1-907d-e40a3f0824f0

### Reproducible?

- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.3

### What platform are you seeing the problem on?

Linux

**Comment by mr-cheffy** [comment] 2024-12-20 18:34
Can't reproduce. Please remove custom css / mods

**Comment by Klusio19** [comment] 2024-12-20 19:03
I never changed any css since don't even know what custom css is. With mods disabled, nothing changes.

https://github.com/user-attachments/assets/7ea41029-359c-48aa-b83d-c5619b100ade

**Comment by mr-cheffy** [comment] 2024-12-23 14:40
What's your `zen.theme.content-element-separation` value in about:config?

**Comment by Klusio19** [comment] 2024-12-23 15:18
> What's your `zen.theme.content-element-separation` value in about:config?

Bingo. It was 1. When changed to something more, like 2, 3 or more, issue dissapears.
By this comment you reminded me, that I changed that value some time ago, because I don't like the default value of this, which makes this weird spacing.

However, like I mentioned in the original post, with all previous version including 1.0.2-b.2, it worked perfectly fine with that `zen.theme.content-element-separation` value set to 1.

**Comment by Klusio19** [comment] 2024-12-23 15:21
> Can't reproduce. Please remove custom css / mods

And if you meant `custom CSS` by changing some values in about:config, I am really sorry, I didn't know that you meant this, and as I said, I completely forgot that I changed that value.

**Comment by mr-cheffy** [comment] 2024-12-23 18:20
> > What's your `zen.theme.content-element-separation` value in about:config?
> 
> Bingo. It was 1. When changed to something more, like 2, 3 or more, issue dissapears. By this comment you reminded me, that I changed that value some time ago, because I don't like the default value of this, which makes this weird spacing.
> 
> However, like I mentioned in the original post, with all previous version including 1.0.2-b.2, it worked perfectly fine with that `zen.theme.content-element-separation` value set to 1.

Im going to close this issue then since it was because you changed the config. Ill open a new one to discuss about how we could maybe fix this issue. Thanks!

**Closed as completed by mr-cheffy** 2024-12-23 18:20 UTC
Labels: Bug
