### ISSUE TITLE
Keyboard shortcuts not working

### ISSUE THREAD

**Issue by t00l5** [zen-browser/desktop#1745] opened 2024-09-26 07:18 UTC
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

When setting keyboard shortcuts and then closing the settings page all custom set keybinds get set back to default

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.5

### What platform are you seeing the problem on?

Windows

**Comment by sjclayton** [comment] 2024-09-26 08:14
Duplicate of #1715

**Comment by edheltzel** [comment] 2024-10-07 14:59
@sjclayton issue #1715 is currently closed but I'm personally still having the issues with the keyboard shortcuts - I really just want the native keybindings to work... like `cmd+w` `cmd+q`  

https://github.com/zen-browser/desktop/issues/1715#issuecomment-2397169610

**Comment by sjclayton** [comment] 2024-10-07 15:05
@t00l5 Please try updating to 1.0.1-a.7 as this is now fixed. Then this issue should be able to be closed.

@edheltzel If you search around issues, I'm pretty sure other macOS users are having similar problems to you.. I don't use macOS myself, also I'm not one of the devs so I can't really help you... Sorry 🙁

**Comment by edheltzel** [comment] 2024-10-07 15:07
I'm currently  on Sequoia `15.0.1` and Zen `1.0.1-a.7`
![SCR-20241007-jxts](https://github.com/user-attachments/assets/11cb764a-0aff-4309-b815-ffcc92fe5778)

**Comment by sjclayton** [comment] 2024-10-07 15:12
@edheltzel Are you having issues changing/saving shortcuts... or is the problem you are having just to do with native shortcuts not working? Because these are very clearly separated issues. I was asking the author of the issue to try upgrading to the latest alpha version not you.. 😃

**Comment by edheltzel** [comment] 2024-10-07 16:09
> @edheltzel Are you having issues changing/saving shortcuts... or is the problem you are having just to do with native shortcuts not working? Because these are very clearly separate issues. I was asking the author of the issue to try upgrading to the latest alpha version not you.. 😃

Changing shortcuts doesn't save and causes the native key bindings to break, I have to hit the reset button to get some of the native bindings back or just quit and reopen. 

Oooh ok gotcha on the upgrade stuff, no worries at all.

**Comment by sjclayton** [comment] 2024-10-07 16:17
@edheltzel Alrighty.. I believe the macOS part of these issues are still being resolved, maybe the next update will fix this stuff for you guys as well.

**Comment by 26CAllen** [comment] 2024-10-18 12:05
+1 this issue is true for the flatpak version as well

**Comment by saltymouse** [comment] 2024-11-03 23:50
Just wanted to share that I've been testing this on macOS Sequoia 15.0.1, and after upgrading from 1.0.1-a.7 to 1.0.1-a.17, all keyboard shortcuts are working perfectly now.

Native shortcuts like `Cmd Q` (quit), `Cmd ,` (settings), and others all work as expected.
I've also tested setting custom shortcuts and they persist properly after closing/reopening the browser.

**Comment by edheltzel** [comment] 2024-11-04 10:36
Agree with @saltymouse my issues have been resolved regarding shortcuts/key bindings

**Closed** 2024-12-12 16:08 UTC
