### ISSUE TITLE
Macbook Pro Passkey issue

### ISSUE THREAD

**Issue by swsvindland** [zen-browser/desktop#479] opened 2024-08-23 12:58 UTC
### What happened?

When I use a website like google or github that signs in with a passkey on desktop it prompts to use the touchID sensor on my macbook keyboard. This happens even when the macbook is closed and being used with external keyboards and monitors and the touch ID sensor is unavailable. other browsers usually offer a fallback to keychain password or a QR code to scan on my phone. 

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.28

### Severity impact

Medium

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by sameer1612** [comment] 2024-08-23 19:02
No passkey support in macbook pro. 

Rest assured touch sensor works perfectly. I am even using it in my regular firefox developer edition flawlessly. 

Firefox:
<img width="1029" alt="image" src="https://github.com/user-attachments/assets/6f543209-7ccb-4879-bff3-832b5f3b9a0c">


Zen:
<img width="1035" alt="image" src="https://github.com/user-attachments/assets/63557cb1-22d6-4051-8911-72b7e1b7d703">

**Comment by sameer1612** [comment] 2024-08-23 19:04
Devs please address this. I really liked zen but it becomes a deal breaker for me, since I gotta use passkey everyday in various official sites. 🤝

**Comment by btrsco** [comment] 2024-08-23 19:14
+1 my passkeys/webauthn is handled via 1Password. A QR code would be great at the very least

**Comment by sameer1612** [comment] 2024-08-23 19:52
> +1 my passkeys/webauthn is handled via 1Password. A QR code would be great at the very least

I wonder how big an effort it will be, or is this a mere bug. Since, Firefox already has it working fine.

**Comment by mauro-balades** [comment] 2024-08-24 10:45
Duplicate of https://github.com/zen-browser/desktop/issues/437

**Closed by mauro-balades** 2024-08-24 10:45 UTC
Labels: kind: medium severity

**Comment by castrojr913** [comment] 2024-09-06 21:09
@mauro-balades @sameer1612  The issue also happens on my side with Zen browser 1.0.0-a.37 (64-bit).  I'm using a Macbook M1 Pro  14'' 2021 with Sonoma 14.6.1 (23G93).

**Comment by dulranga** [comment] 2024-11-02 18:29
I can confirm this happened with Macbook M1 Pro 14'' 2021 macos 15.1 (24B83)
zen version - 1.0.1-a.17 (Firefox 132.0) (aarch64)

**Comment by owengalenjones** [comment] 2024-11-16 21:16
Same here, MBP Apple M3 MacOS 15.0.1, had to open FireFox to leave this comment as passkey just doesn't work.

**Comment by obatola** [comment] 2024-11-22 23:08
same here m1 mac

**Comment by JadenMonare** [comment] 2024-11-24 21:21
here too, M3 macOS15

**Comment by mikailkraft** [comment] 2024-12-10 15:41
Passkeys not working, M2 Macbook Air, macOS 15.0.1, Zen v1.0.1-a.18

**Comment by rrooddooxx** [comment] 2024-12-12 01:02
same here, while firefox works well, please support this fix, would really make zen stand out against other options, thanks!!

**Comment by lincolnaleixo** [comment] 2024-12-31 19:10
was so excited to use zen until this. impossible to use, oh well, back to safari

**Comment by syscat29** [comment] 2024-12-31 19:14
Always remember to check the link issues my guys
![image](https://github.com/user-attachments/assets/04722eda-0724-4ba9-8357-a529ab13e6cf)

**Comment by supperdoggy** [comment] 2025-01-30 14:56
is it still not fixed?...

**Comment by tails618** [comment] 2025-01-30 18:14
@supperdoggy please actually read through the PR; you will see that it was closed and marked as a duplicate of #437 (and thus discussion should be there instead), and if you read through that PR you will see that the dev asked not to post comments that don't positively contribute.

**Comment by gokgokay** [comment] 2025-02-28 20:00
When will it be fixed?

**Comment by zakthedev** [comment] 2025-03-01 00:46
I hope this gets fixed

**Comment by patmilla** [comment] 2025-03-15 23:51
seems to be fixed in #437
