### ISSUE TITLE
In full screen, the padding on the right and bottom remains.

### ISSUE THREAD

**Issue by redisthenewblack** [zen-browser/desktop#1428] opened 2024-09-13 21:31 UTC
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

In fullscreen on youtube or any video player, the padding on the right and bottom remains.

![image](https://github.com/user-attachments/assets/f4624433-d0bb-4264-af92-e9c8c9cfcdd8)

Previous issue was closed: https://github.com/zen-browser/desktop/issues/67

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

Version 1.0.0-a.39 (64-bit)

### What platform are you seeing the problem on?

Windows

**Comment by Dean-Corso** [comment] 2024-09-13 23:59
So I can confirm that problem in full screen mode. I made a image you can see it in ZEN & Firefox. Left, right & bottom issue you don't have in Firefox.
![ZEM_Firefox_2024-09-14_014316](https://github.com/user-attachments/assets/a93b0f74-dc56-40a6-95ea-73a7f80d8e3a)

I also did notice a problem when you minimize / maximize the ZEN browser window. So every time when I restore the window back to visible then the entire browser window is blank (some grayed color) and after few seconds +1 it gets refreshed and is showing all browser elements again. That's annoying. Maybe there is some notification issue in ZEN. Just check this out please.

Another problem with ZEN is that it lags somehow. Slowness in reaction etc. I can't say that the performance of ZEN is better or same good as in Firefox yet. I'm testing ZEN since yesterday. 😃

**Comment by NOCanoa** [comment] 2024-09-14 01:10
yeah know issues, should be fixed next release

**Closed** 2024-09-14 07:00 UTC
