### ISSUE TITLE
Essential Tabs & Pinned workspace tabs behave fishy in multi-window scenarios

### ISSUE THREAD

**Issue by bdbch** [zen-browser/desktop#3057] opened 2024-11-17 01:12 UTC
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I think both these features are great and a big improvement to Zen but they currently render the browser useless to me.

I'm using multiple browser windows very often and I believe browsers are not a "one-window" tool only, specially in multi-screen setups. Because of that it's hard to have a "main" window.

For me it happens really often that when I'm using workspaces and essential tabs and I create a new window I have:

1. My essentials also on the second window but in different order and some of the tabs are not even loaded (pointing to a blank page)
2. Workspace tabs are all shown at once and I need to click on a workspace to kinda "put them in the right workspace" again

It's confusing specially with a collapsed sidebar because there can sometimes be tabs from my work-workspace showing up in my personal workspace etc.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.19

### What platform are you seeing the problem on?

Windows

**Comment by bdbch** [comment] 2024-11-17 14:03
I think my expectation for secondary windows would be to not have essential tabs at all (as they don't make sense in a second window, can't sync tabs between windows I think).

Workspaces in a secondary window should be fixable.

**Comment by bdbch** [comment] 2024-11-17 19:06
Potentially related to #3070

**Comment by Kuttesch** [comment] 2024-11-17 21:01
Yes that could very well be, it seems most of the incorrectly behaving tasks are related to opening another window of some sort

**Comment by mr-cheffy** [comment] 2024-12-23 16:05
Duplicate of https://github.com/zen-browser/desktop/issues/2989

**Closed as completed by mr-cheffy** 2024-12-23 16:05 UTC
Labels: Bug
