### ISSUE TITLE
web pannel does not retain page when pinned and unpinned

### ISSUE THREAD

**Issue by neurokitti** [zen-browser/desktop#2287] opened 2024-10-23 01:41 UTC
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

https://github.com/user-attachments/assets/a80789d6-3e32-4244-90fc-8bbd8c40f626

the page resets to the web panel default.

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-t12

### What platform are you seeing the problem on?

Windows

**Comment by sjclayton** [comment] 2024-10-23 13:31
Duplicate of #2022

**Comment by neurokitti** [comment] 2024-10-23 13:48
> Duplicate of #2022

should i just close this issue? or leave it up?

**Comment by sjclayton** [comment] 2024-10-23 13:51
You can close it, keep all discussion on the original issue.

**Closed as completed** 2024-10-23 14:41 UTC
