### ISSUE TITLE
Windows Defender flagging zen.exe:  DefenseEvasion.A!ml

### ISSUE THREAD

**Issue by shaeriz** [zen-browser/desktop#728] opened 2024-08-26 05:37 UTC
### What happened?

I was browsing normally when Windows Defender suddenly closed Zen and detected this virus on zen.exe : DefenseEvasion.A!ml. No idea what could have caused that. I'm using latest Windows 11 and Windows Defender update.

![image](https://github.com/user-attachments/assets/565dc250-3030-4f98-9338-d3051f8f747f)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.029

### Severity impact

High

### What platform are you seeing the problem on?

Windows

**Comment by n7itro** [comment] 2024-08-26 05:53
Duplicate of #37 and #718

**Closed** 2024-08-26 05:53 UTC
Labels: kind: high severity
