### ISSUE TITLE
Close to right right on a side bar?

### ISSUE THREAD

**Issue by KUKARAF** [zen-browser/desktop#607] opened 2024-08-24 19:10 UTC
### What happened?

When you right click on a tab >> Close multiple tabs, 2 options are visible that are not quite right. 
I believe Close to the right should be called close bellow and close to the left should be called closed above

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.28 (64-bit)

### Severity impact

Low

### What platform are you seeing the problem on?

Linux

**Comment by Zykkl** [comment] 2024-08-24 19:13
Dupe of #521

**Closed** 2024-08-24 19:13 UTC
Labels: kind: low severity
