### ISSUE TITLE
Cmd+Q doesn't close or prompt Zen to close (MacOS)

### ISSUE THREAD

**Issue by Criseda** [zen-browser/desktop#2119] opened 2024-10-15 09:37 UTC
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

On MacOS, pressing the CMD+Q will not close Zen, it will just make the "Zen Browser" flash in the top left. Going into it and pressing "Quit Zen" will do the job, but the shortcut does not.

https://github.com/user-attachments/assets/09238b18-411c-4581-ac7b-ef84bb70008c

### Reproducible?

- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.9 (aarch64)

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by mr-cheffy** [comment] 2024-10-15 10:14
>  I have searched existing issues and avoided creating duplicates.

It's a pinned issue, please try to search for duplicates before posting an issue, thanks!

Duplicate of https://github.com/zen-browser/desktop/issues/1629

**Closed as completed by mr-cheffy** 2024-10-15 10:14 UTC
