### ISSUE TITLE
Strange behaviour of Switch to tab when using pinned tabs and workspaces

### ISSUE THREAD

**Issue by kakato10** [zen-browser/desktop#3024] opened 2024-11-14 20:55 UTC
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Steps to reproduce:
1. Create 2 workspaces
2. Pin a tab to workspace 2.
3. Open this pinned tab
4. Go to workspace 1 and open a website inside of it
5. Focus the address bar
6. Enter the url of the pinned tab
7. Click on the suggestions with "Switch to tab"

ER: Zen switches to workspace 2 and focuses the pinned tab
AR: The pinned tab appears inside the pinned tabs for Workspace 1, and Workspace 2 is not focused. If the user selects again Workspace 2, pinned tabs are back to their correct state for both Workspaces.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.19

### What platform are you seeing the problem on?

Windows

**Comment by tbpassin** [comment] 2024-11-25 19:54
I can confirm that the focused tab appears on a newly selected workspace, whether or not it is pinned. But sometimes this does not happen, although I cannot reproduce the conditions.  

In addition, and maybe more concerning, when I open a private window, some selection of tabs from the existing non-private window appears **in the tab bar of the private window.** I haven't filed an separate issue on this because I suspect it's an aspect of this same issue.

These very annoying behaviors showed up on my Windows 10 machine after the recent update to version 1.0.1-a.19. I have the tab bar on the left of the main window; it is not compactified.

These behaviors do not occur with Zen v1.0.1-a.3 on a Linux VM. The tab bar is configured the same way on both machines.

**Comment by mr-cheffy** [comment] 2024-12-23 16:05
Duplicate of https://github.com/zen-browser/desktop/issues/2989

**Closed as completed by mr-cheffy** 2024-12-23 16:05 UTC
Labels: Bug
