### ISSUE TITLE
Right click on tabs randomly stops working, restart fixes it for a while

### ISSUE THREAD

**Issue by zaknafein99** [zen-browser/desktop#3500] opened 2024-12-10 17:16 UTC
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Exactly that. Suddenly the right click in tabs stops working. I have to restart Zen to view the right click menu again, and then, in a few minutes, it stops working again

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.0 (Firefox 133.0) (64-bit)

### What platform are you seeing the problem on?

Windows

**Comment by RyanJMoore10** [comment] 2024-12-10 17:35
Also experiencing this. Seems to start after I send tabs to a new workspace.

**Comment by zaknafein99** [comment] 2024-12-10 18:21
> Also experiencing this. Seems to start after I send tabs to a new workspace.

It may be related to an extension? It's working fine since I removed Session Paw (a session manager). Can't reproduce now, even tried sending tabs to another workspace

**Comment by zaknafein99** [comment] 2024-12-10 18:22
NVM! It returned, I keep moving tabs between workspaces and the issue reappeared

**Comment by RyanJMoore10** [comment] 2024-12-10 18:23
Any chance you were/are using sideberry?

**Comment by zaknafein99** [comment] 2024-12-10 18:28
> Any chance you were/are using sideberry?

Mmm. I have the extension installed, but not actively using it. I'll try removing it

**Comment by zaknafein99** [comment] 2024-12-10 18:36
Nope! Sidebery removed and it still happens

**Comment by neurokitti** [comment] 2024-12-21 22:29
if i am not mistaken this is a duplicate of the following issues:
https://github.com/zen-browser/desktop/issues/3046
https://github.com/zen-browser/desktop/issues/2980

if not then let me know!

**Closed as completed by neurokitti** 2024-12-21 22:29 UTC
Labels: Bug

**Comment by zaknafein99** [comment] 2024-12-22 21:18
> if i am not mistaken this is a duplicate of the following issues: #3046 #2980
> 
> if not then let me know!

Yes, seems to be the same!
