### ISSUE TITLE
Browser crashing when entering/logging into your Gmail account with a Passkey

### ISSUE THREAD

**Issue by motionless-isdev** [zen-browser/desktop#2336] opened 2024-10-27 01:10 UTC
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Browser is crashing whenever a user tries to enter/log into an email account in Gmail when passkeys is showing. It can be reproduce whenever the user's passkey list is shown, but it won't when passkeys is disabled.

https://github.com/user-attachments/assets/7acb0700-52db-4726-b1e2-8cced8dd82b2

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1

### What platform are you seeing the problem on?

Windows

**Comment by salamijason** [comment] 2024-10-29 11:20
Yo it looks like the version number u inputted is incomplete? Could you check again if the issue is reproducible on the latest version?  1.0.1-a.14 as of Oct 29

**Comment by salamijason** [comment] 2024-12-02 15:50
User has not replied in a couple weeks. Closing the issue now. Please reopen if issue persists.

**Closed as completed by salamijason** 2024-12-02 15:50 UTC
Labels: Bug
