### ISSUE TITLE
Rounded viewport corners are not rounded on some websites

### ISSUE THREAD

**Issue by georg-stone** [zen-browser/desktop#3053] opened 2024-11-16 19:13 UTC
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

So, I was developing my website, and noticed that the viewport corners on the page weren't rounded on the bottom left and the top left. When going inside the browser console, I removed the body element, and the problem went away. I continued to debug by changing styles and removing other nested elements, but it didn't work. The website URL is [flowtide.app](https://flowtide.app). 

**UPDATE:** My website was since migrated to Astro, but the issue can still be reproduced on the Zen browser website.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.19

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by Arichy** [comment] 2024-12-04 15:11
Same here, and even the zen browser official website could reproduce this issue. There is no left-top radius and left-bottom radius.
![image](https://github.com/user-attachments/assets/446ae329-96a6-42f0-810d-570407ee4db7)

**Comment by georg-stone** [comment] 2024-12-08 03:13
It's probably just Next.js's fault, since both mine (I have since updated it to use Astro) and Zen's worked with it.

**Comment by JSGRD22** [comment] 2024-12-11 00:46
This issue was fixed by zen.view.experimental-rounded-view but has resurfaced in 1.0.2-b.0

**Comment by hoangdinhini** [comment] 2024-12-17 04:53
Same here, but seems to be random, not related to any specific websites. I am on Windows 11.

**Closed as duplicate** 2024-12-21 10:20 UTC
Labels: Bug

**Comment by mr-cheffy** [comment] 2024-12-21 10:22
note: You can add `zen.view.experimental-rounded-view` to true in about:config
