### ISSUE TITLE
Bookmarks toolbar bug

### ISSUE THREAD

**Issue by Silver-Fox** [zen-browser/desktop#2453] opened 2024-10-31 08:20 UTC
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Turning on bookmarks toolbar makes the tabs area smaller and makes the close, minimize buttons on smaller windows impossible to press.

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.16

### What platform are you seeing the problem on?

Windows

**Comment by ptdodat** [comment] 2024-10-31 08:26
I have the same problem

**Comment by mr-cheffy** [comment] 2024-10-31 15:10
Duplicate of https://github.com/zen-browser/desktop/issues/2434, please follow the discussion there, it has been fixed for v17

**Closed as not planned by mr-cheffy** 2024-10-31 15:10 UTC
Labels: Bug
