### ISSUE TITLE
Apply the browser theme to history menu

### ISSUE THREAD

**Issue by sidsharths1245** [zen-browser/desktop#555] opened 2024-08-24 07:33 UTC
### What happened?

The theme isn't applied to the history menu.
![zen_Q48V7lqIdO](https://github.com/user-attachments/assets/2ba7028b-a746-4bf4-ac6c-26e41424aa42)

I also had a another suggestion

What if this history menu opens up when we hit ctrl+H. This one has more options and looks way better than the default menu. Maybe a "Theme" can be made for this.
![zen_3D5Q8iL2cx](https://github.com/user-attachments/assets/4bcdb932-54ff-4bf9-820f-f0334d7e019d)

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.28 (64-bit)

### Severity impact

Low

### What platform are you seeing the problem on?

Windows

**Comment by dewantawsif** [comment] 2024-08-24 08:27
> I also had a another suggestion

It's better for developers if you make separate feature request instead of adding it inside a bug report

**Comment by Zykkl** [comment] 2024-08-24 15:55
possible dupe of #501?

**Comment by NOCanoa** [comment] 2024-08-24 16:00
2) that wold be done in the shortcuts setting page.

**Comment by NOCanoa** [comment] 2024-08-24 16:01
1) dont understand what u mean from what i can see your border color is the same as the history menu.

**Closed** 2024-08-24 16:05 UTC
Labels: kind: low severity
