### ISSUE TITLE
Essentials do not transfer to newly opened windows

### ISSUE THREAD

**Issue by sprutxz** [zen-browser/desktop#2875] opened 2024-11-11 06:24 UTC
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

When opening new windows, pinned tabs transfer across but essential tabs don't. Also pinned tabs across workspace seem to merge on initial launch, getting fixed once you switch between workspace

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.19

### What platform are you seeing the problem on?

Windows

**Comment by DipsoNOR** [comment] 2024-11-11 07:44
Generally both Essentials and Pinned tabs behave really inconsistent after the essentials update. Needs to be tested a lot more robustly. I keep losing tabs, having essentials and/or pinned tabs move between my two main windows. (I usually have one browse and one Youtube/entertainment window going)

**Comment by universish** [comment] 2024-11-11 16:53
https://github.com/zen-browser/desktop/issues/2871

**Comment by jfcostello** [comment] 2024-11-11 19:30
> Generally both Essentials and Pinned tabs behave really inconsistent after the essentials update. Needs to be tested a lot more robustly. I keep losing tabs, having essentials and/or pinned tabs move between my two main windows. (I usually have one browse and one Youtube/entertainment window going)

Yeah this is my experience, too. For both Essentials and Pins, newly opened second windows sometimes get some of them, sometimes it gets some of them with the containers mixed up, sometimes it puts all of them in one workplace, and sometimes it gets none of them

And then sporadically I'll just lose all Essentials and Pins completely, either on restart or just randomly (It happened when I pinned something once)

**Comment by juampivallejo** [comment] 2024-11-12 02:54
For me new tabs most of the time transfer the "essentials" to the newer one, however they all created with the same container as the default one for the workspace that the new window is open with.
This ends up being very annoying because I have to remove all essentials and open them again with the right container since all the session information is lost.

**Comment by universish** [comment] 2024-11-12 12:28
I don't have this problem.
I have not been able to reproduce the problem.

**Comment by BoscoDomingo** [comment] 2024-11-12 12:44
#2949 related

**Comment by radu-solomon** [comment] 2024-11-29 15:09
Same issue with Version 1.0.1-a.20. 

I really hope this gets fixed. Essentials are great but I use multi window a lot and having the essentials all be present in all my windows makes life so much easier. I saw some talk in another issue about essentials only being available in the first window open which I hope is not what will be done because that would in my opinion defeat the purpose of the essentials.

**Comment by sprutxz** [comment] 2024-12-10 19:04
> Same issue with Version 1.0.1-a.20.
> 
> I really hope this gets fixed. Essentials are great but I use multi window a lot and having the essentials all be present in all my windows makes life so much easier. I saw some talk in another issue about essentials only being available in the first window open which I hope is not what will be done because that would in my opinion defeat the purpose of the essentials.

Idk if you've had this fixed yet but readding the urls as essentials seems to fix the issue for me

**Comment by mr-cheffy** [comment] 2024-12-23 16:05
Duplicate of https://github.com/zen-browser/desktop/issues/2989

**Closed as completed by mr-cheffy** 2024-12-23 16:05 UTC
Labels: Bug
