### ISSUE TITLE
Keyboard shortcuts glitched

### ISSUE THREAD

**Issue by YelehaUwU** [zen-browser/desktop#2131] opened 2024-10-15 14:47 UTC
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I am unable to use any keyboard shortcuts, and after trying to reset them, the menu just got completely empty.
After trying to create a new profile, it still persists.

![image](https://github.com/user-attachments/assets/28fe9cf0-7214-4243-901a-78cbafd6354d)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

a9

### What platform are you seeing the problem on?

Windows

**Comment by sjclayton** [comment] 2024-10-15 15:00
Duplicate of #2111, Related #2118

This can be closed, fixed in next update (a.10)

**Closed as completed** 2024-10-15 15:44 UTC
