### ISSUE TITLE
UI is bugged and websites don't load

### ISSUE THREAD

**Issue by DebadityaMalakar** [zen-browser/desktop#2469] opened 2024-10-31 12:45 UTC
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I have been using Zen Browser for over 3months now, however recently after today's update the Ui got extremely bugged and not a single website loads or works.

![image](https://github.com/user-attachments/assets/16213f9e-6fbf-4e92-946e-e08c61fff84b)

### Reproducible?

- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

Alpha build - 1.0.1-a.16 (2024-10-31)

### What platform are you seeing the problem on?

Windows

**Comment by limonkufu** [comment] 2024-10-31 13:00
I am also seeing this on MacOS after a.16 update

**Comment by aL0NEW0LF** [comment] 2024-10-31 13:10
https://github.com/user-attachments/assets/72c83368-59e0-41d9-951e-1fce077c5646

The exact bug I got is that when tabs unload, they don't load when you click on them; you have to reload the tab.
It doesn't show in the video, but I right-clicked on the tab to unload it, then clicked on it but it doesn't load, until u reload it.

**Comment by aakay** [comment] 2024-10-31 13:20
tab unloader might be the problem. i see this behaviour when inactive tabs are unloaded and when i try to open them, they just don't react to any clicks and tab is not switched.

**Comment by JerryLerman** [comment] 2024-10-31 13:21
Same for me. No website renders. Ubuntu 20.04.6 LTS

**Comment by 12th-devs** [comment] 2024-10-31 13:22
Same here

Windows 11 x86

a.16

**Comment by aL0NEW0LF** [comment] 2024-10-31 13:24
Exactly what happened to me, in the video I try to mimic the unload, but I first noticed it when tabs auto unload.

**Comment by Swearfy** [comment] 2024-10-31 13:37
+1 tab unloader is the issue, as soon as the tab is auto unloading UI just breaks. On my end reload won't work unless you do a full browser restart and if you close active tab and it switches to one inactive you wont be able to open a new tab.

Only work around restart browser and disable tab unloader

**Comment by adithyaharun** [comment] 2024-10-31 13:38
+1 happened to me as well. The workaround is to close the tab and reopen it, or disable tab unloader.

**Comment by berkaykrc** [comment] 2024-10-31 13:40
+1 unresponsive tabs and UI

**Comment by Swearfy** [comment] 2024-10-31 13:47
https://github.com/zen-browser/desktop/issues/2436 > Seems fixed on v17

**Comment by LopesLs** [comment] 2024-10-31 13:47
+1 to me, happens a lot, restart zen browser is the palliative approach

**Comment by Li-An** [comment] 2024-10-31 13:52
Same problem here Win 10 64 bits. 
After the update, I got the @DebadityaMalakar screen. After reinstalling, I got the tab unloader problem.

**Comment by RayZ3R0** [comment] 2024-10-31 14:43
Duplicate of #2436  It will be fixed in the next update

**Closed as completed by RayZ3R0** 2024-10-31 14:43 UTC
Labels: Bug
