### ISSUE TITLE
Light mode makes some buttons look disabled

### ISSUE THREAD

**Issue by 88572** [zen-browser/desktop#3312] opened 2024-11-30 15:40 UTC
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Turning on light mode makes some buttons appear to be disabled, as shown in the screenshots:
![image](https://github.com/user-attachments/assets/3f0211c4-4059-4403-9b19-9fa025d934a0)
(Pink color scheme, light mode)
![image](https://github.com/user-attachments/assets/d0a730e8-0442-49f5-828d-eedd9cd0d1fa)
(Same color scheme, dark mode)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.22

### What platform are you seeing the problem on?

Linux

**Comment by LeMoonStar** [comment] 2024-11-30 16:21
While I cannot reproduce this exact look - the dialogues do look very weird in general.

While testing, I was also unable to switch them from light to dark mode (using the latest twilight build `1.0.1-t.22 (Firefox 133.0) (2024-11-30)` with default settings under a new profile - I will test this under "stable" Zen as well )

![Image](https://github.com/user-attachments/assets/067ed3de-e2a5-42f8-878e-fe4ba5aabec9)
![Image](https://github.com/user-attachments/assets/66c57042-b07a-4d44-bbb2-6ec071a152bc)

**Comment by LeMoonStar** [comment] 2024-11-30 16:28
On "stable" Zen `1.0.1-a.22 (Firefox 132.0.1) (64-bit)` The dialogues look as shown in the issue for me, however I still cannot switch the light/dark mode for them.

![Screenshot From 2024-11-30 17-26-14](https://github.com/user-attachments/assets/629920d1-cf18-4fa7-bbf6-25baf37d05a7)
![Screenshot From 2024-11-30 17-26-25](https://github.com/user-attachments/assets/e75fe317-dbdb-4be5-abd4-35e7fd1b6611)

**Comment by 88572** [comment] 2024-11-30 17:04
To switch themes of the dialogue, you need to go to `about:addons` and switch Firefox themes.

**Comment by mr-cheffy** [comment] 2024-12-21 11:38
Should be fixed now 👍🏽

**Closed as completed by mr-cheffy** 2024-12-21 11:38 UTC
Labels: Bug
