### ISSUE TITLE
bug : Zen glance goes to next tab on closing glance instead of previous

### ISSUE THREAD

**Issue by RealDishwash** [zen-browser/desktop#2677] opened 2024-11-05 23:01 UTC
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

When exiting out of the zen glance view, it switches the the tab after, rather than showing the tab opened zen glance within

Expected behaviour: I expect it to revert to the tab i opened zen glance in, rather than switching to the next tab in the list

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.17

### What platform are you seeing the problem on?

Linux

**Comment by Shockshwat** [comment] 2024-11-06 12:35
Duplicate of #2526, Fixed in twilight version.

**Closed as completed** 2024-11-06 22:00 UTC
Labels: Bug
