### ISSUE TITLE
Workspacetabs closing when opening another window from other workspace

### ISSUE THREAD

**Issue by Kuttesch** [zen-browser/desktop#3070] opened 2024-11-17 15:12 UTC
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Steps to Reproduce

    Open two tabs in Workspace 1.
    Switch to Workspace 2.
    Open a new window.
    Switch back to Workspace 1.

Expected Result

The two tabs opened in step 1 should remain open and visible in Workspace 1.

Actual Result

The two tabs opened in step 1 are closed when switching back to Workspace 1 in step 4.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.19

### What platform are you seeing the problem on?

Windows

**Comment by mr-cheffy** [comment] 2024-12-23 16:05
Duplicate of https://github.com/zen-browser/desktop/issues/2989

**Closed as completed by mr-cheffy** 2024-12-23 16:05 UTC
Labels: Bug
