### ISSUE TITLE
Unloaded Pages Cannot Be Opened Again

### ISSUE THREAD

**Issue by stafsa** [zen-browser/desktop#2491] opened 2024-10-31 19:31 UTC
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Hi, as you can see from the title, I can't reopen the unloaded sites.I mean, you know, zen browser has a feature that unloads the unused sites after a selected amount of minutes.It's set to 20 minutes for me.And after I uploaded the zen browser, I can't use unloaded sites.I've put a video to make you fully understand the issue.Also, even if I reload the sites, they're still unclickable.

https://github.com/user-attachments/assets/0fd0bbfc-3944-4348-80e0-4e020e4fa871

Note:Github didn't allow me to upload a file that's 14 MB so I increased the size of it, so that's why the mark appears.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.16(64 bit)

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by jgonzales20** [comment] 2024-10-31 20:11
same issue for me, this issue is due to tab unloader

Quick Fix:
Disable tab unloader then restart zen, this will keep your tabs open on restart.

**Comment by danilosekulovikj** [comment] 2024-10-31 20:52
Having the same issue on Linux.

**Comment by decryptedchaos** [comment] 2024-10-31 21:11
Yep been happening since the last couple of releases.

**Comment by Frestein** [comment] 2024-10-31 23:13
Duplicate of https://github.com/zen-browser/desktop/issues/2436.

**Comment by DevSnyco** [comment] 2024-11-01 04:54
this is fixed in the new release `1.0.1-a.17`

**Comment by dipudangol2** [comment] 2024-11-01 06:04
this is why they should not make the update prompt appear each 10 minutes, Whenever i find a version that i like it just keeps persuading us to update and after updating there are new bugs.

**Comment by RayZ3R0** [comment] 2024-11-01 11:03
Fixed in a.17, thanks for reporting! Also please try not to create duplicate issues

**Closed as completed by RayZ3R0** 2024-11-01 11:03 UTC
Labels: Bug
