### ISSUE TITLE
New Tab button has disappeared from the menu bar customization

### ISSUE THREAD

**Issue by realSilasYang** [zen-browser/desktop#2806] opened 2024-11-10 08:45 UTC
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

The New Tab button has disappeared from the menu bar customization, leaving the only option to open a new tab located at the bottom of the tabs. This placement is quite inconvenient, especially when multiple tabs are open, as it requires scrolling down to locate the button. Many users prefer having the New Tab button easily accessible at the top of the tab bar, similar to previous versions of the browser, where it was more straightforward to use.

To improve this situation, it would be beneficial to restore the New Tab button to a more prominent position in the interface, allowing for quicker access without the need to scroll. This change would enhance usability, particularly for users who frequently open new tabs.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.18

### What platform are you seeing the problem on?

Windows

**Comment by kar731** [comment] 2024-11-10 08:50
Duplicate of #2778

**Comment by JakubPavlicek** [comment] 2024-11-10 08:52
+1 I also prefer having the "New Tab" button at the top

**Closed as not planned** 2024-11-10 08:52 UTC
Labels: Bug
