### ISSUE TITLE
sidebar (setting, history, etc) getting sink when i create tab and reach my limit

### ISSUE THREAD

**Issue by Ndraaa15** [zen-browser/desktop#1230] opened 2024-09-04 10:47 UTC
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

when i create new tab and reach the limit the bottom sidebar getting sink and the page (new tab) getting bigger. And that's made i can't scroll to find the setting button

![image](https://github.com/user-attachments/assets/c19da055-7192-4f3f-bd99-4fb60abc89ae)
![image](https://github.com/user-attachments/assets/3c8969cc-da7e-4414-8e8f-d79b8caf8ac9)
![image](https://github.com/user-attachments/assets/36cc3946-608c-4694-8dc1-c2af94785cae)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.35

### What platform are you seeing the problem on?

Windows

**Comment by n7itro** [comment] 2024-09-04 15:13
Duplicate of #1209

**Closed by n7itro** 2024-09-04 15:13 UTC
Labels: kind: medium severity
