### ISSUE TITLE
closing glance window on some websites breaks zen until restarted

### ISSUE THREAD

**Issue by ell1010** [zen-browser/desktop#2536] opened 2024-11-01 11:31 UTC
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [ ] I am not filing an enhancement request.

### What happened?

when you control click to open a glance window and the click outside the bounds of the window, it seems to minimise the window but zen stiill thinks its open and not only can you not do anything on the tab you were on, you can no longer switch tabs or close the glance window (without closing the current tab) until you restart zen (seems to only be specific websites repeatable on instagram for instance)

https://github.com/user-attachments/assets/b1f30910-ed8e-46cf-8aa1-e23fffd5b380

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.17

### What platform are you seeing the problem on?

Windows

**Comment by 0skar2** [comment] 2024-11-01 17:42
Glance is generally very unstable, and i dont understand why they enabled it by default (and didnt even bother with at least adding a small "ALPHA" tag to let people know its not very stable at the moment)

**Comment by 0skar2** [comment] 2024-11-01 19:41
In addition, websites opened with Glance are being saved to the history, im unsure whether its intended behaviour or not though, but for me, it shouldnt be.

**Comment by neurokitti** [comment] 2024-11-02 01:47
> Glance is generally very unstable, and i dont understand why they enabled it by default (and didnt even bother with at least adding a small "ALPHA" tag to let people know its not very stable at the moment)

its deffinatly gotten more stable in the last update but its still a bit buggy.

**Comment by RayZ3R0** [comment] 2024-11-07 13:42
This should be fixed in the next update, lets see

**Comment by Lumoo** [comment] 2024-11-08 11:42
I would add to this:
When using the Glance feature, if I open a tab and close it with the shortcut `[CTRL] + [W]`, the browser remains in "Glance mode" across all other tabs. This prevents further use of the Glance feature. Restarting the browser temporarily resolves the issue.

Steps to reproduce: 
1. Open a tab using the Glance feature.
2. Close the tab with [CTRL] + [W].
3. Attempt to use the Glance feature on other tabs.


https://github.com/user-attachments/assets/a9db4612-d1b5-403c-8b97-228f03252c74

**Closed as not planned** 2024-12-16 16:04 UTC
Labels: Bug
