### ISSUE TITLE
Compact Tabbar Broken

### ISSUE THREAD

**Issue by NatryN** [zen-browser/desktop#2036] opened 2024-10-11 20:33 UTC
### Captchas

- [X] I have read the instructions.
- [X] I am not filing an enhancement request.
- [X] I have searched existing issues and avoided creating duplicates.

### What happened?

![image](https://github.com/user-attachments/assets/086acc1d-38d0-4268-9e1a-e0eb20c27b7b)
I just update zen browser, how can i fix my tabbar.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.8

### What platform are you seeing the problem on?

Linux

**Comment by sjclayton** [comment] 2024-10-11 21:17
Also experiencing this, for me it seems to only affect tabs opened in workspaces that previously had no open tabs (just the auto created empty / new tab) before the a.8 update, workspaces that had tabs open before the update the sidebar looks like it normally should when collapsed in compact mode.

**Comment by sjclayton** [comment] 2024-10-11 21:20
Maybe related - #2015

**Comment by NatryN** [comment] 2024-10-11 21:32
I pin a tab and it look better, but I want that but without pining a tab.
![image](https://github.com/user-attachments/assets/9b751ab2-9b4a-44cd-9fc8-19e113597747)

**Comment by sjclayton** [comment] 2024-10-11 22:07
@NatryN 

What happens if you unpin the tab... Does the bug re-appear or do the tabs look normal?

**Comment by NatryN** [comment] 2024-10-11 22:19
> @NatryN
> 
> What happens if you unpin the tab... Does the bug re-appear or do the tabs look normal?

the bug re-apper

**Comment by antikovt** [comment] 2024-10-13 17:02
+1, also wanna add that the paddings in this implementation are quite ugly, especially compared to the [Floating Compact Sidebar](https://github.com/zen-browser/theme-store/tree/main/themes/46690a54-5eff-4141-8af8-9cd772ab6e2c) extension (that's now broken). How about just implementing the extension as a switch in settings?

![Screenshot 2024-10-13 184939](https://github.com/user-attachments/assets/42419d6e-1c1d-47eb-a5e3-bc489cacf998)
With the extension enabled, ignore the now broken shadows, notice the equal padding relative to the page

![Screenshot 2024-10-13 184950](https://github.com/user-attachments/assets/a2857a28-477e-4ab0-afe7-cb3bdf4fb93c)
Without the extension, notice the offset, especially vertically

**Comment by scanash00** [comment] 2024-10-13 22:05
This has been fixed and will be available in the next Zen Browser Release.

Fixed on: Zen Twilight Build

This might be related: https://github.com/zen-browser/desktop/commit/e840184e7fac54d523e8a4fd61b73b44ae33419c

**Comment by antikovt** [comment] 2024-10-13 22:07
> This has been fixed and will be available in the next Zen Browser Release.

Have the paddings been adjusted too?

**Comment by scanash00** [comment] 2024-10-13 22:08
> > This has been fixed and will be available in the next Zen Browser Release.
> 
> Have the paddings been adjusted too?

Probably, yes. https://github.com/zen-browser/desktop/commit/e840184e7fac54d523e8a4fd61b73b44ae33419c

**Comment by scanash00** [comment] 2024-10-13 22:12
You can always try it yourself by dowloading the twilight build at https://github.com/zen-browser/desktop/releases/tag/twilight

**Comment by FireDrop6000** [comment] 2024-10-15 02:44
> This has been fixed and will be available in the next Zen Browser Release.
> 
> Fixed on: Zen Twilight Build
> 
> This might be related: [e840184](https://github.com/zen-browser/desktop/commit/e840184e7fac54d523e8a4fd61b73b44ae33419c)

Downloaded **v1.0.1-a.9** today morning. Looks like the issue didn't get fixed. I am on Arch btw.

Edit: Seems like the problem is with Floating Compact Sidebar Zen Mod.

![1728959991_grim](https://github.com/user-attachments/assets/260542ce-b9a6-49de-b100-568690f81f79)

**Comment by sjclayton** [comment] 2024-10-15 06:36
The issue with the icons being cut off is resolved for me in 1.0.1-a.9 on Linux.. any other issues that would appear related to this are probably being caused by mods. 

This can probably be closed now.

**Comment by mr-cheffy** [comment] 2024-10-15 13:56
Sourds good!

**Closed as completed** 2024-10-15 13:56 UTC

**Comment by antikovt** [comment] 2024-10-26 21:50
> > Have the paddings been adjusted too?
> 
> Probably, yes. [e840184](https://github.com/zen-browser/desktop/commit/e840184e7fac54d523e8a4fd61b73b44ae33419c)
> You can always try it yourself by dowloading the twilight build at https://github.com/zen-browser/desktop/releases/tag/twilight

Sadly, no, the paddings of the tabbar still visually conflict with the paddings of the compact view. Idk if anyone will ever get to changing this or if people would agree with me, but I think the paddings used in the extension I linked higher in the chain are much more visually appealing. 

![Screenshot 2024-10-26 234306](https://github.com/user-attachments/assets/f475b965-49e5-4bf2-acc8-789617f99400)
