### ISSUE TITLE
Passkeys don't work on zen browser on macOS

### ISSUE THREAD

**Issue by Builderstafsa** [zen-browser/desktop#2068] opened 2024-10-13 10:38 UTC
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Hi!As you can see in the title, I can't use passkeys on zen browser(I mean finger print passkeys).I'm using mac, and while I was using google, It's working perfectly.I've put an photograph to make you understand.
<img width="465" alt="Ekran Resmi 2024-10-13 13 34 11" src="https://github.com/user-attachments/assets/ec23b70a-0b92-4e40-8557-c59c7993cae0">
And here's the photograph on zen browser.I put my finger on the finger print button but nothing happens on zen browser.Please fix that bug.
<img width="409" alt="Ekran Resmi 2024-10-13 13 34 52" src="https://github.com/user-attachments/assets/1d836aa3-74b8-4036-b51d-3efb7e628aec">

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.8

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by mr-cheffy** [comment] 2024-10-13 15:58
Duplicate of https://github.com/zen-browser/desktop/issues/437

**Closed as completed by mr-cheffy** 2024-10-13 15:58 UTC
