### ISSUE TITLE
Closing the second to last tab in a split view opens an unrelated tab

### ISSUE THREAD

**Issue by LeMoonStar** [zen-browser/desktop#2139] opened 2024-10-15 17:21 UTC
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

When in a split view with exactly two tabs, which are separated by other tabs in the tab list, **closing one tab causes Zen to display an unrelated tab**, instead of the remaining tab. This is unexpected (and annoying) behavior.

[!A video showing the described behavior](https://github.com/user-attachments/assets/a0d79159-ed88-4cdd-8657-8310ec04c75f)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.9

### What platform are you seeing the problem on?

Linux, Windows

**Comment by joshuaanthonydeleon** [comment] 2024-10-18 03:42
Have you tried upgrading to the latest version. on 1.0.1-a.8 and 1.0.1-a.10 I'm unable to reproduce. I'm running Manjaro and have zen installed via Flatpack.

**Comment by LeMoonStar** [comment] 2024-10-18 05:11
> Have you tried upgrading to the latest version. on 1.0.1-a.8 and 1.0.1-a.10 I'm unable to reproduce. I'm running Manjaro and have zen installed via Flatpack. 

I do have the same issue with the latest version 1.0.1-a.10 - as AppImage and Flatpak. Even with the latest twilight, this issue occurs.

Do note that the tabs have to be separated by other tabs in the tab bar! If they are next to each other, everything works as expected.

**Comment by salamijason** [comment] 2024-10-29 18:10
Hey just testing this on windows 1.0.1-a.14 and it works fine and switches to the remaining tab from the split. Could you try again with the latest version of Zen?

**Comment by LeMoonStar** [comment] 2024-10-31 20:52
> Hey just testing this on windows 1.0.1-a.14 and it works fine and switches to the remaining tab from the split. Could you try again with the latest version of Zen?
@salamijason 

Yes, the issue still persists even on the newest twilight branch.
Keep in mind the tabs have to be separated with other tabs that are not part of the split group to reproduce, see the attached video. 

https://github.com/user-attachments/assets/93fa0604-32cd-4e82-8653-0d75e0bf5549

**Comment by krisMG21** [comment] 2024-11-03 00:18
Happens to me too, but it depends on the tab currently selected.
* If, as in the video, we have clicked on the second tab, we are currently in it, and we close it, we move to the middle tab outside the split.
* If we are operating in the first tab and we close the second one, the first one maximizes as it would be expected.

Every time a tab closes, the next one replaces it (unless we delete the last tab). 
When both split tabs are adjacent, the previous behavior aligns with the expected.

The thing is, is this unintended behavior by the developers or unexpected by the user?

Because it seems that, at the moment, the tab management operates independently, or treating them individually, and split only have a visual or render impact?

**Comment by salamijason** [comment] 2024-11-03 09:32
Hmm okay, I tried it again while having the second tab active and I was able to reproduce the issue. What @krisMG21 said is right too, I have no idea whether this is intentional or not. I'll ask around and get back to ya'll.

**Comment by LeMoonStar** [comment] 2024-11-03 10:56
> Hmm okay, I tried it again while having the second tab active and I was able to reproduce the issue. What @krisMG21 said is right too, I have no idea whether this is intentional or not. I'll ask around and get back to ya'll.

This is the default behaviour of Firefox: It switches to the tab in front or after the tab in the tab list if the current tab is being closed.
This is not intentional, but simply unhandled behaviour. It would be much more user friendly to switch to the next tab part of the current split view instead.

**Comment by krisMG21** [comment] 2024-11-03 10:59
> This is the default behaviour of Firefox: It switches to the tab in front or after the tab in the tab list if the current tab is being closed.
> This is not intentional, but simply unhandled behaviour. It would be much more user friendly to switch to the next tab part of the current split view instead.

Makes sense, i dont mind it much tho.
Either way, it's a change that should be made first by Firefox right?
Or can be reworked by Zen?

**Comment by LeMoonStar** [comment] 2024-11-03 11:04
> > This is the default behaviour of Firefox: It switches to the tab in front or after the tab in the tab list if the current tab is being closed.
> > This is not intentional, but simply unhandled behaviour. It would be much more user friendly to switch to the next tab part of the current split view instead.
> 
> Makes sense, i dont mind it much tho.
> Either way, it's a change that should be made first by Firefox right?
> Or can be reworked by Zen?

Firefox can't change and has no reason to change it, as it has no split views. It is a zen-exclusive problem.

**Comment by krisMG21** [comment] 2024-11-03 11:23
> Firefox can't change and has no reason to change it, as it has no split views. It is a zen-exclusive problem.

Oh shoot that's right XDDD my bad my bad.

**Closed as not planned** 2024-12-11 16:07 UTC
Labels: Bug, Improvement
