### ISSUE TITLE
Tabs disappeared in the latest update

### ISSUE THREAD

**Issue by itstamimi** [zen-browser/desktop#1515] opened 2024-09-17 21:50 UTC
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

After the last update, and restarting the browser, the tabs just disappeared, they are still there if I click the arrow, but the tab area is empty and you can't scroll anywhere.
![Screenshot_20240917_174611](https://github.com/user-attachments/assets/38322006-f00b-42f7-b973-6ac7c3e3633a)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.1 (64-bit)

### What platform are you seeing the problem on?

Linux

**Comment by onthejobtraining** [comment] 2024-09-17 22:12
Go to history-recently closed windows. You should find your lost window there.

**Comment by User344** [comment] 2024-09-18 00:01
+1 Same for me on Windows. It seems like it didn't just disappear but they are squished together and that scrolling is absent. Thus it appears like there are no tabs.
![image](https://github.com/user-attachments/assets/2392fc0d-0374-42f2-b102-2b8ec4d95728)

**Comment by sudanchapagain** [comment] 2024-09-18 00:37
Yeah. I was confused too. They exist but squished together. It is on latest update `1.0.1-a.1 (64-bit)`

**Comment by dannrs** [comment] 2024-09-18 00:39
+1 on Windows 10.
![image](https://github.com/user-attachments/assets/9fc62023-69a1-4279-b3e6-1083a598c6b3)

**Comment by sudanchapagain** [comment] 2024-09-18 00:40
this issue seems to be duplicate of https://github.com/zen-browser/desktop/issues/1491

**Comment by mauro-balades** [comment] 2024-09-18 05:07
This is fixed, please remember to update once I release it.

The release will be available in like 10 minutes

**Closed by mauro-balades** 2024-09-18 05:07 UTC
