### ISSUE TITLE
Application menu button can't move back to the right side

### ISSUE THREAD

**Issue by chrboesch** [zen-browser/desktop#1650] opened 2024-09-23 19:18 UTC
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Since update 1.0.1-a.3, the application menu button is on the left side and can no longer be moved back to the right side.

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.3

### What platform are you seeing the problem on?

Linux

**Comment by sjclayton** [comment] 2024-09-23 19:23
Duplicate of #1619

**Closed** 2024-09-23 19:26 UTC
