### ISSUE TITLE
Glance jumps to the first unpinned tab

### ISSUE THREAD

**Issue by Tealk** [zen-browser/desktop#2660] opened 2024-11-05 10:06 UTC
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

If I use Glance on a pinned tab and close the Glance window again, it jumps to the first unpinned tab.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.17

### What platform are you seeing the problem on?

Windows

**Comment by radiosilence** [comment] 2024-11-05 17:31
I am experiencing this on *any* tab, if I close a glance, it always skips to the next tab.

**Comment by Tealk** [comment] 2024-11-05 18:26
You're right
I was able to reproduce it on Linux too.

**Comment by MrPiggy105** [comment] 2024-11-07 05:53
Can confirm this on macOS 1.0.1-a.17 (Firefox 132.0, aarch64), even if you close it. There is also another bug for glance on pinned tabs, I'll make a new issue.

**Comment by RayZ3R0** [comment] 2024-11-07 13:01
Duplicate of #(I dunno man, no one checks for duplicates so there's a lot). Closing as it will be fixed in a18 soon.

**Closed as completed by RayZ3R0** 2024-11-07 13:01 UTC
Labels: Bug

**Comment by Tealk** [comment] 2024-11-07 13:46
Sorry I searched but found nothing for my keywords
