### ISSUE TITLE
Undo closed tab/window shortcut doesn't work

### ISSUE THREAD

**Issue by sidsharths1245** [zen-browser/desktop#1801] opened 2024-09-29 18:46 UTC
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I set the keyboard shortcut shift + ctrl + t to undo closed tabs or windows but it doesn't work properly. It works for a while but then I have to go back in  Keboard shortcut settings and set it again.

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.5 (64-bit)

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment] 2024-09-29 18:57
Duplicate of https://github.com/zen-browser/desktop/issues/1728, please follow this issue there. Thanks!

**Closed by mauro-balades** 2024-09-29 18:57 UTC
