### ISSUE TITLE
Zen browser cant restore tabs in their specific workspaces after closing the browser (Added video proof)

### ISSUE THREAD

**Issue by shwetarkadam** [zen-browser/desktop#2461] opened 2024-10-31 10:09 UTC
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

After updating Zen Browser to 1.0.1-a.16 to fix side toggle commands, it now fails to restore tabs in their workspaces after closing.

Video of the issue 
https://github.com/user-attachments/assets/df989ec0-9bd5-493a-8b15-a2e210a203a4

https://github.com/user-attachments/assets/c7082b14-1ca8-4752-b5c2-b95d67644289

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.16

### What platform are you seeing the problem on?

macOS - aarch64

## Notes 
- I checked in the settings for anything related to session management or startup or restore keyword couldn’t find anything

**Comment by salamijason** [comment] 2024-11-10 16:43
Hi this is really weird. Could you try a new profile? There's a good chance the profile got corrupted during the update.
Please also make sure you have this ticked:![Image](https://github.com/user-attachments/assets/0b8c088b-9382-47b7-9a8c-2554182c59b1)

**Comment by jalzur** [comment] 2024-11-24 06:30
Not sure if this could help, but I've noticed that the problem is when you close the window, not the app, in macOS. It also happens with other programs such as VSCode or Sublime Text. 

If you close the app (right click in the dock icon and select close) and reopen it, it should restore the tabs. But if you close the window (the close red button) then the app is still open in the dock but without any window, and if you try to open a new window now, it won't restore the tabs.

It would be nice an option such as "close the app instead of closing the last window".

**Comment by salamijason** [comment] 2024-12-02 15:48
@jalzur 

> It would be nice an option such as "close the app instead of closing the last window".

This option exists! If you click the three dot menu, there is an option to close Zen right at the bottom.

Due to session store, if you close windows one at a time, there's a good chance only the tabs of the very last window will be restored on next launch. To avoid this, it's best to use the option I mentioned earlier.

The original poster hasn't responded in quite a bit so I'll be closing this for now. Please reopen if the issue persists.

**Closed as completed by salamijason** 2024-12-02 15:48 UTC
Labels: Bug
