### ISSUE TITLE
URL bar BUG

### ISSUE THREAD

**Issue by Sionyyy** [zen-browser/desktop#3629] opened 2024-12-12 08:48 UTC
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

when typing in the new floating URL bar, if I use English, it works well. But if I use Chinese, the words jumps from the old urlbar and the floating urlbar. It is so annoying.
Furthermore, I recommend giving a shortcut to call the floating URL bar directly. The experience that I type in the urlbar but the floating urlbar appears suddenly is not braceful.
I love this browser so I hope the problem can be solved

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.1

### What platform are you seeing the problem on?

Windows

**Comment by iustinm1** [comment] 2024-12-12 08:50
+1

**Comment by kuqquk** [comment] 2024-12-12 16:12
Settings -> Firefox Labs -> enable "Address Bar: show results during IME composition"

**Comment by nneto** [comment] 2024-12-12 19:04
I for one would like if the floating bar opened with Ctrl/Cmd+L and Ctrl/Cmd+K

> The experience that I type in the urlbar but the floating urlbar appears suddenly is not braceful

I totally agree

**Comment by Sionyyy** [comment] 2024-12-13 05:14
> Settings -> Firefox Labs -> enable "Address Bar: show results during IME composition"

it works, thanks!

**Comment by JSGRD22** [comment] 2024-12-17 14:28
You may close the issue if the problem is solved to reduce clutter

**Closed as completed** 2024-12-17 14:28 UTC
Labels: Bug
