### ISSUE TITLE
Updating the browser clears history and open tabs in all workspaces

### ISSUE THREAD

**Issue by ReKylee** [zen-browser/desktop#2357] opened 2024-10-28 00:46 UTC
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

On my other browsers, updating doesn't close your current session, but here it does. 
Any way to avoid that? 

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.14 (Firefox 131.0.3) (64-bit)

### What platform are you seeing the problem on?

Windows

**Comment by Quephara** [comment] 2024-10-28 10:58
facing this issue. i have lost a couple of saved login sessions. the most important being a freelancing gig that i cannot recover the password for, not through their website and also not through the expected logins.json. the browser auto-switched to a new profile (defaut-alpha) and trying to open it in the default process makes it freeze : 
![Screenshot_20241028_135506](https://github.com/user-attachments/assets/6fd6bc19-130e-4d57-a685-53be8d5c4d06)

platform: arch linux

version: updated to latest build `Mozilla Zen 1.0.1-a.14`

this indicates the bug is likely from the new profiles feature

**Comment by mr-cheffy** [comment] 2024-10-29 11:38
> On my other browsers, updating doesn't close your current session, but here it does.
> Any way to avoid that?

Do you have this preference enabled?

![image](https://github.com/user-attachments/assets/e6116af2-7328-4e06-a3a1-b7cdbd8085a0)

**Comment by mr-cheffy** [comment] 2024-10-29 11:38
> facing this issue. i have lost a couple of saved login sessions. the most important being a freelancing gig that i cannot recover the password for, not through their website and also not through the expected logins.json. the browser auto-switched to a new profile (defaut-alpha) and trying to open it in the default process makes it freeze :

Could you run it from the terminal and send the logs? Thanks

**Comment by elcharitas** [comment] 2024-10-29 15:13
> facing this issue. i have lost a couple of saved login sessions.


I can confirm that I face the same issue with the same version but on MacOS.

I however noticed two more things
1. The browser clears my session on every restart which is weird
2. Memory usage has skyrocketed to about 250%. That's huge


At this point, I'm seriously considering either not using zen any longer or disable automatic updates and update manually.

**Comment by Quephara** [comment] 2024-10-30 13:34
> > ... makes it freeze :
> 
> Could you run it from the terminal and send the logs? Thanks

[desktop-alpha.txt](https://github.com/user-attachments/files/17573570/desktop-alpha.txt)
[desktop.txt](https://github.com/user-attachments/files/17573571/desktop.txt)


alpha is the one that successfully launches

**Comment by Quephara** [comment] 2024-10-30 13:37
> > facing this issue. i have lost a couple of saved login sessions.
> 
> I can confirm that I face the same issue with the same version but on MacOS.
> 
> I however noticed two more things
> 
>     1. The browser clears my session on every restart which is weird
> 
>     2. Memory usage has skyrocketed to about 250%. That's huge
> 
> 
> At this point, I'm seriously considering either not using zen any longer or disable automatic updates and update manually.

you could try running with  `zen-browser -p` from the terminal, see if that solves it, else find ~/.zen and delete the folder, if it works the same as linux, you will start on a completely new profile

**Comment by salamijason** [comment] 2024-12-02 16:06
Checking up on this issue since it's been quiet for a bit. Is the bug still occurring?

**Comment by ReKylee** [comment] 2024-12-02 16:09
Hi! On my end it seems to be fixed! Gone through few updates and the
browser seems to keep my session :D

**Comment by salamijason** [comment] 2024-12-02 16:31
Cool! @elcharitas @Quephara are you guys still getting this?

**Comment by elcharitas** [comment] 2024-12-02 16:40
> Cool! @elcharitas @Quephara are you guys still getting this?

I can confirm that I no longer get this bug

**Comment by salamijason** [comment] 2024-12-02 16:49
cool okay 2/3 ppl have reported the bug to be gone. if anyone else still has this, please reopen. I'll be closing this for now.

**Closed as completed by salamijason** 2024-12-02 16:49 UTC
Labels: Bug
