### ISSUE TITLE
Blank space above tabs

### ISSUE THREAD

**Issue by KKTasil** [zen-browser/desktop#3501] opened 2024-12-10 17:26 UTC
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Blank space above tabs. Space for workspace icon is there even when disabled and even additional margin above that.
![image](https://github.com/user-attachments/assets/6d83c3fe-cb5e-4d66-bda8-b8fd7fc77dd8)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.0 (Firefox 133.0) (64-bit)

### What platform are you seeing the problem on?

Windows

**Comment by filipjanevski** [comment] 2024-12-10 23:52
I also have the same problem, for me the space is even larger. I have no custom CSS edits. I also don't like that there is no space between window controls and back button on Mac.

<img width="266" alt="Screenshot 2024-12-11 at 00 43 37" src="https://github.com/user-attachments/assets/7b565aac-3113-49b9-8a2c-213e1a70467f">

**Comment by Couleur-Share** [comment] 2024-12-11 01:57
I also have the same problem, and this problem has appeared in multiple versions and has not been fixed yet!

**Comment by CcMenta** [comment] 2024-12-11 18:52
You can change this in `about:config` search for `zen.workspaces.show-workspace-indicator` and set it to `False`.

**Comment by filipjanevski** [comment] 2024-12-11 19:09
@CcMenta Thanks for the suggestion. I does reduce the blank space a little bit but it still looks bad.

**Comment by Couleur-Share** [comment] 2024-12-12 08:50
@CcMenta Thank you very much, it really solves this problem

**Comment by Smooth-E** [comment] 2024-12-15 22:21
> You can change this in `about:config` search for `zen.workspaces.show-workspace-indicator` and set it to `False`.

@KKTasil if this is the case for you, consider the closing this issue as duplicate of #2862

**Comment by KKTasil** [comment] 2024-12-15 22:24
The change that @CcMenta suggested does help, so thank you!

**Closed as completed** 2024-12-15 22:23 UTC
Labels: Bug

**Comment by hxchtiewei** [comment] 2024-12-20 01:17
@CcMenta 
ver 1.0.2-b.3, does not work..

**Comment by Couleur-Share** [comment] 2024-12-20 01:19
> @CcMenta ver 1.0.2-b.3, does not work..

Me too, it’s really annoying!

**Comment by hiwer** [comment] 2024-12-20 08:00
![image](https://github.com/user-attachments/assets/d95e14cf-2b2a-4f34-9f5a-131edbed6115)
That strange empty space is still there even in version 1.0.2-b.3 :(
