### ISSUE TITLE
Workspaces that are named after an emoji are not displayed correctly

### ISSUE THREAD

**Issue by RaduAvram** [zen-browser/desktop#1732] opened 2024-09-25 13:41 UTC
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

![image](https://github.com/user-attachments/assets/6b6ad293-a53d-49e1-b777-6034f7dd0991)
There are a few icons to choose from, but when pasting my own emoji - in this case the brain emoji - as the workspace's name, it does not get displayed correctly under the workspace icon, but is displayed in the workspace's name. 

I don't know if having an emoji picker for the workspace icons(harder to do) OR just taking the text the workspace is called - in my case a single emoji - is the better workaround.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.5

### What platform are you seeing the problem on?

Windows

**Comment by n7itro** [comment] 2024-09-25 14:28
The available icons are stored in the `zen.workspaces.icons` preference in `about:config`

**Comment by adam-adrian** [comment] 2024-09-30 05:06
Duplicate of #1656

**Closed** 2024-09-30 08:14 UTC
