### ISSUE TITLE
Weird blue bar at the top after update

### ISSUE THREAD

**Issue by maicek** [zen-browser/desktop#3502] opened 2024-12-10 17:40 UTC
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

![image](https://github.com/user-attachments/assets/f436e816-04c2-439b-893a-1ddb7f5ab797)

Just, after update the browser shown for me the redesigned welcome dialog for selecting preferences and after that the browser have luched normally with all previous state but renders for me this weird blue thing. 

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.0 (Firefox 133.0) (64-bit)

### What platform are you seeing the problem on?

Windows

**Comment by JosueGalRe** [comment] 2024-12-10 17:58
@maicek try disabling mica in about:config, search for mica, set the value to false and restart the browser

**Comment by ryannewcomer** [comment] 2024-12-10 18:21
that is what[ i got too](https://github.com/zen-browser/desktop/issues/3450). they fix it in the latest update

**Comment by maicek** [comment] 2024-12-11 06:17
> @maicek try disabling mica in about:config, search for mica, set the value to false and restart the browser

Thank you, works.

**Comment by j4yn1ck5** [comment] 2024-12-13 15:16
Mine is purple. Because I like purple. Disabling Mica fixed the problem for me. 

There is a release note for 1.0.2-b.1 that says "Fixed weird top-bar when mica is enabled with windows 11 accent color enabled."

I tried turning mica back on. The problem was not solved.

**Comment by Knopyaro** [comment] 2024-12-13 19:18
> Mine is purple. Because I like purple. Disabling Mica fixed the problem for me.
> 
> There is a release note for 1.0.2-b.1 that says "Fixed weird top-bar when mica is enabled with windows 11 accent color enabled."
> 
> I tried turning mica back on. The problem was not solved.

Same issue for me, the bug is not fixed and only disappears when I turn Mica off.

**Comment by xsidexpt** [comment] 2024-12-16 18:39
Same thing for me!

**Comment by swrgio** [comment] 2024-12-18 15:41
This is the same bug I'm having right now, I hope they fix it in a new update.

**Comment by mr-cheffy** [comment] 2024-12-28 18:49
Duplicate of https://github.com/zen-browser/desktop/issues/3546

**Closed as completed by mr-cheffy** 2024-12-28 18:49 UTC
Labels: Bug
