### ISSUE TITLE
zen google meet crashesh on audio device switch in ubuntu

### ISSUE THREAD

**Issue by Naveenv01** [zen-browser/desktop#1228] opened 2024-09-04 09:36 UTC
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

[Screencast from 2024-09-04 15-02-51.webm](https://github.com/user-attachments/assets/b79511b3-8a14-4e95-8aa4-f4b10e47d684)

In google meet when switching audio tab crashed as shown above video 

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

Alpha build - 1.0.0-a.35 (2024-09-03)

### What platform are you seeing the problem on?

Linux

**Comment by KeluDev-Code** [comment] 2024-09-04 14:22
Have the same issue on Linux - Zorin OS 17.1 Core 64 bits

### Version
Alpha build - 1.0.0-a.35 (2024-09-03)

### Reproducible?
 * [x]  I have checked that this issue cannot be reproduced on Mozilla Firefox.

**Comment by mauro-balades** [comment] 2024-09-07 16:56
Please, the checkboxes aren't just a captcha... this is a duplicate of https://github.com/zen-browser/desktop/issues/972

**Closed by mauro-balades** 2024-09-07 16:56 UTC
Labels: Triage
