### ISSUE TITLE
Extensions with companion programs do not detect your program from Zen browser

### ISSUE THREAD

**Issue by Uligonza** [zen-browser/desktop#1462] opened 2024-09-15 23:58 UTC
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Plugins such as Kaspersky Protection and 1Passwords do not detect the programs installed on the computer that are necessary for their operation

![1Passwords](https://github.com/user-attachments/assets/b8c7d5a3-963c-4864-98f5-d60676c38102)

![kaspersky](https://github.com/user-attachments/assets/aa5845f9-5691-4282-a512-2a0b5d04bfa0)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.39

### What platform are you seeing the problem on?

Windows

**Comment by PeterGion** [comment] 2024-09-16 15:02
I can confirm that I'm also seeing this issue on Linux as well.

**Comment by mdatla** [comment] 2024-09-18 14:41
Same issue windows 11. 

Primary blocker at the moment from making zen my default browser on all machines (well - would be firefox on mobile)

**Comment by drafolin** [comment] 2024-09-19 16:32
Same issue Linux // Arch (btw) // Wayland // GDM // Gnome

**Comment by dortlii** [comment] 2024-09-19 16:39
There's already an ongoing discussion about this: https://github.com/zen-browser/desktop/discussions/856 with some workarounds, but I'll guess this is already on a todo list.

**Comment by drafolin** [comment] 2024-09-19 17:47
For the Linux users that stumble upon this issue, said workaround is as follow:
```sh
sudo mkdir /etc/1password
sudo touch /etc/1password/custom_allowed_browsers
echo "zen-bin" | sudo tee -a /etc/1password/custom_allowed_browsers
```

Worked for me, hope it helps

**Comment by PeterGion** [comment] 2024-09-22 14:00
> For the Linux users that stumble upon this issue, said workaround is as follow:
> 
> ```shell
> sudo mkdir /etc/1password
> sudo touch /etc/1password/custom_allowed_browsers
> echo "zen-bin" | sudo tee -a /etc/1password/custom_allowed_browsers
> ```
> 
> Worked for me, hope it helps

That worked!!! thank you

**Comment by red-crate** [comment] 2024-09-24 04:56
Same issue for me in windows 11.
btw, 3rd party browsers have same issue like zen, floopr.

**Comment by drafolin** [comment] 2024-09-24 05:57
> Same issue Linux // Arch (btw) // Wayland // GDM // Gnome
> 
> Following is the 1P extension console log:
> 
> ```
> # From the extension console:
> 
> 💫 Looking for desktop app com.1password.1password background.js:1220:214654
> 📤 Sending <NmRequestAccounts> message to native core <3338843819> background.js:1220:216851
> Received <BrowserVerificationFailed> from the native core background.js:1220:216405
> ```

so far, it seems this might be due to the fact that Zen is not in 1password's list of trusted browser... Because the Native Messaging actually goes thru. Another thing that leans in this direction is that adding it manually to the list of trusted broswers fixes it... 
Can someone testify that this also happens with other applications having companion browser exts. ? I wouldn't be surprised if 1password was the only one.

**Comment by gregor160300** [comment] 2024-10-23 12:45
Just a heads-up for anyone that added the `custom_allowed_browsers` but still can't get the integration to work. It seems like the ownership of the directory zen (for me `/opt/zen`) is in needs to be `root:root`, this might break the auto-update feature though.

**Comment by apotenza92** [comment] 2024-11-10 02:41
Does anyone know of an equivalent workaround to make this work on macOS?

**Comment by adamlogan** [comment] 2024-11-10 20:25
1Password has an official function for adding custom browsers on MacOS, I found these instructions on their [community support website](https://1password.community/discussion/comment/719323#Comment_715517).

Instructions for Mac:
    Open and unlock the 1Password for Mac desktop app.
    Click on 1Password next to the  in the menu bar.
    Click Settings.
    Click Browser.
    Click Add Browser and choose your browser from the Applications folder (in this case, Zen Browser).

**Comment by dunestorm333** [comment] 2024-11-17 11:53
> 1Password has an official function for adding custom browsers on MacOS, I found these instructions on their [community support website](https://1password.community/discussion/comment/719323#Comment_715517).
> 
> Instructions for Mac: Open and unlock the 1Password for Mac desktop app. Click on 1Password next to the  in the menu bar. Click Settings. Click Browser. Click Add Browser and choose your browser from the Applications folder (in this case, Zen Browser).

This solution works great on my Mac running Sequoia, but we also need a solution for Windows too.

**Comment by salamijason** [comment] 2024-12-15 09:04
Has anyone found a solution for windows? is the issue still prevalent?

**Comment by CoreParadox** [comment] 2024-12-19 17:19
> Has anyone found a solution for windows? is the issue still prevalent?

There is no windows workaround. 1Password support has stated in their [support thread for ZenBrowser.](https://1password.community/discussion/147429/support-for-zen-browser)

I don't know if there's a path forward for users, maybe if core maintainers reached out to 1Password they might be willing to whitelist it, but it sounds like they are abandoning the "browser vetting" process they had in favor of custom browser whitelists. They have not provided any sense of if or when this core feature will be added to the Windows application, despite existing on MacOS.

**Comment by salamijason** [comment] 2024-12-21 07:28
Oh that's bizarre, ig we'll just have to wait for what they're gonna decide to do with the whitelists. For now, I'll be closing this thread as "not planned". Thank you all for your input!

**Closed by salamijason** 2024-12-21 07:28 UTC
