### ISSUE TITLE
Some videos don't work (udemy.com media license server)

### ISSUE THREAD

**Issue by nesterow** [zen-browser/desktop#588] opened 2024-08-24 15:08 UTC
### What happened?

On udemy.com videos dont work for any paid course. Works on Firefox.
I've tried to switch off tracking protection, but still on debugger I see the requests with `NS_BINDING_ABORTED` code.
<img width="1106" alt="Screenshot 2024-08-24 at 17 06 13" src="https://github.com/user-attachments/assets/ec5bce3f-6c4a-4383-a153-2e267a28237d">

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.28 (64-bit)

### Severity impact

Medium

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by bfayers** [comment] 2024-08-24 15:11
Duplicate of #503 which is the same issue as: https://github.com/ungoogled-software/ungoogled-chromium/issues/1258#issuecomment-2114305561

**Closed** 2024-08-24 15:11 UTC
Labels: kind: medium severity
