### ISSUE TITLE
Where did the Zen Mods Store link go?

### ISSUE THREAD

**Issue by GoremanX** [zen-browser/desktop#3794] opened 2024-12-15 21:22 UTC
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I swear there used to be a button for this before, but I don't see it anymore

![zenmods](https://github.com/user-attachments/assets/e913be00-2ba2-4b45-a68b-b27dcb0316c2)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2b2

### What platform are you seeing the problem on?

Windows

**Comment by Smooth-E** [comment] 2024-12-15 22:02
If you squint your eyes a whole lot, you can actually see the link there.

![Cropped screenshot of previously attached image depicting a low-contrast link](https://github.com/user-attachments/assets/a8658565-6e92-4572-9645-65da135bdc07)

Here is how it looks for me on a more blue-ish theme.

![Screenshot depicting Zen Mods store link being almost the same color as the background](https://github.com/user-attachments/assets/4319b772-2864-479a-b5de-44be377eb4de)

This issue can be considered a duplicate of #3727, which mentions such behavior being repeated all over the settings. For example, here is a similar thing on another settings page.

![Hardly visible link on another settings page](https://github.com/user-attachments/assets/1bd429a4-bf68-4c09-8195-fb451c651dd0)

Consider closing this issue as duplicate if you agree and thank you for your contribution! 👀

**Comment by mr-cheffy** [comment] 2024-12-15 22:57
Ill move this into https://github.com/zen-browser/desktop/issues/3727

**Closed as completed by mr-cheffy** 2024-12-15 22:57 UTC

**Comment by GoremanX** [comment] 2024-12-16 17:20
> If you squint your eyes a whole lot, you can actually see the link there.

Holy crap I had to look hard to find that 😂 Thank you!

I'd strongly suggest a button rather than a link

**Comment by Smooth-E** [comment] 2024-12-16 17:25
> > If you squint your eyes a whole lot, you can actually see the link there.
> 
> Holy crap I had to look hard to find that 😂 Thank you!
> 
> I'd strongly suggest a button rather than a link

Well, it is like that all over Firefox' system pages: you get a button when you need to perform an action and you get a link when you want to go to some other page. Therefore, I think that making it a button will look rather out of place.

**Comment by GoremanX** [comment] 2024-12-16 17:30
> Well, it is like that all over Firefox' system pages: you get a button when you need to perform an action and you get a link when you want to go to some other page. Therefore, I think that making it a button will look rather out of place.

That's fair
