### ISSUE TITLE
Color picker only works when Workspaces is enabled

### ISSUE THREAD

**Issue by litaniecontrelapeur** [zen-browser/desktop#3998] opened 2024-12-26 03:36 UTC
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

![image](https://github.com/user-attachments/assets/e0656cf6-6b0b-4aab-8cfb-2776a4fcf860)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.5

### What platform are you seeing the problem on?

Windows

**Comment by neurokitti** [comment] 2024-12-28 00:17
this seems to be a duplicate of: https://github.com/zen-browser/desktop/issues/2894

thank you for reporting it! but please check if there is already an issue open first!

**Closed as completed by neurokitti** 2024-12-28 00:17 UTC
Labels: Bug
