### ISSUE TITLE
Pinned tabs completely confused.

### ISSUE THREAD

**Issue by mikedlr** [zen-browser/desktop#2989] opened 2024-11-13 17:16 UTC
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I had a working browser configuration with a number of pinned tabs on each of several workspaces. I have recently made exactly two tabs essential so they are on all workspaces. 

Suddenly earlier today all pinned tab configuration changed. multiple of the pinned tabs from one workspace appeared on the other workspaces. The essential tabs have changed to use the container that is default in the other workspace I was using lost. 

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.19 (Firefox 132.0.1) (64-bit) 

### What platform are you seeing the problem on?

Linux

**Comment by gambithunt** [comment] 2024-11-13 17:20
I had the same thing happen to me.

**Comment by mikedlr** [comment] 2024-11-13 17:22
@gambithunt any idea what you did to trigger it? I am trying to reproduce this from a clean browser. I think I just started up in the new version but it might have been moving a tab from one workspace to another that triggered it????

**Comment by gambithunt** [comment] 2024-11-13 17:24
I was just restarting zen, it bugged out with the bitwarden plugin creating a window on the desktop that could not be closed instead of opening it on the top right of the screen.

**Comment by hdecoded** [comment] 2024-11-13 22:26
I am loosing both essentials and pinned tab on multiple workspaces on restarts. Also if i load new window essentials are not consistent across

**Comment by mikedlr** [comment] 2024-11-15 14:03
There seem to be several similar / related issues connected with pinned tabs

* https://github.com/zen-browser/desktop/issues/3012
* https://github.com/zen-browser/desktop/issues/3024

switching back to a previous version with

    flatpak update --commit 6057ce7f8cbd85b429adc79bc2d94bc7f9496fe23a6ec375a591b9b8d082793b io.github.zen_browser.zen
    flatpak mask b18679656e0c464571b8e8be9e6e3f4ba1aa048ea1cab921f9adab3411be35fd

seems to improve this.

**Comment by mikedlr** [comment] 2024-11-17 21:40
Moving back to the previous version reduced problems but after a time, I still got a problem where all my tabs in my main workspace ended up in one (wrong) container which meant they stopped working. I've now moved back one more version. 

    $ flatpak mask
    Masked patterns:
      6057ce7f8cbd85b429adc79bc2d94bc7f9496fe23a6ec375a591b9b8d082793b
      b18679656e0c464571b8e8be9e6e3f4ba1aa048ea1cab921f9adab3411be35fd
    $ sudo flatpak update --commit=35c12360aabd33b2d9cd98637fb09bb8f74eac6db5f097a2043d2a428c9c9033 io.github.zen_browser.zen

**Comment by bdbch** [comment] 2024-11-17 22:01
Related issues:
#3012 
#3024 
#3057 
#3070
#2875
#2949

**Comment by mbaltrusitis** [comment] 2024-11-21 18:56
Pinned tabs seem to be syncing across windows AND workspaces. I expect pinned tabs to be scoped to a specific browser window only.

**Comment by mikedlr** [comment] 2024-11-21 23:54
Remembering that I'm using the old version.  (commit 35c12360aabd33b2d9cd98637fb09bb8f74eac6db5f097a2043d2a428c9c9033 ) 
I have noticed that I get the same thing as @mbaltrusitis.

The thing is tough that even in this version I have noticed that, whilst in the first window the other tabs keep the correct container, in the new windows they don't. 

I agree with what mbaltrusitis is asking for - there should be a main window and other windows that behave differently, but it's a quite un-firefox way of doing things. With firefox you can close all of the windows in any order and as long as theres one still remaining the app is open. This is kind of asking for one special window that kind of shouldn't get closed or where other things change if it closes because all the pinned & tabs should be protected otherwise they should be copied across all windows, which is also a waste on a multi-screen environment.

**Comment by mbaltrusitis** [comment] 2024-11-22 01:01
It's similar to this issue where activating a workspace in one window would switch it across all of them. https://github.com/zen-browser/desktop/issues/2005

**Comment by mikedlr** [comment] 2024-11-22 20:13
I've tried this on the developer's build from the 21st - 

https://github.com/zen-browser/desktop/releases/tag/twilight

It seems to a bit improved but still shows the problem that, although pinned tabs have the same URLs, they can end up with different containers in new windows.

**Comment by mikedlr** [comment] 2024-12-20 11:48
On 1.0.2-b.2 (Firefox 133.0.3) (64-bit) I feel that this is largely resolved, although there's still a fundamental problem that if you open a new window and then have tabs open in both window, it's not clear which should be the one which remains when you restart. I've made a suggestion on discord but nobody bit.

Leaving this open for now in case anyone else has some suggestions what would reduce the confusion more.

**Comment by tkapous** [comment] 2024-12-21 15:23
IMHO, I think workspaces should be window agnostic, i.e a specific workspace should always contain the same tabs (either pinned or not) across windows.

That would solve the ambiguous tab sync when closing a window.

**Comment by mikedlr** [comment] 2024-12-22 19:23
@Biggybi  that feels very much like a new feature and it might not even be an easy one to do because having two different views of the same tab is not supported by firefox as far as I know.. I have brought something like that that up in the discord without getting much feedback. My suggestion was that new windows should default to opening without workspaces and only the first window opened should have them by default. 

I think it might be a good idea to [open a discussion](https://github.com/zen-browser/desktop/discussions) about that and reference this ticket and your idea.

**Comment by mr-cheffy** [comment] 2024-12-23 16:06
> Related issues: #3012 #3024 #3057 #3070 #2875 #2949

Thanks a lot.

Could anyone send a video so I can better visualize this? I dont seem to be able to reproduce. Thanks

**Comment by kakato10** [comment] 2024-12-23 16:21
I haven't observed this behavior for a while. I was able to reproduce it consistently. It looks like it got fixed with one of your previous releases.

**Comment by mikedlr** [comment] 2024-12-23 16:30
@mr-cheff ; I think the main bug here is now solved although I still see some annoying behavior due to having two separate windows with the same pinned tabs, especially with something like the following where WhatsApp doesn't cope with being open in two tabs; at least the following is annoying. 

1. make WhatsApp an essential (I use it with no container)
2. go into WhatsApp so that it's active
3. open a new window - WhatsApp will be an essential here as well
4. click on the WhatsApp essential tab in your new window - your new window will now become the active WhatsApp
5. repeat 3 & 4 - you now have moved the active WhatsApp twice
6. wait long enough that your first window stops being active
7. switch back to your first window - you cannot get WhatsApp to recover properly and have to login again

I will make a video of that in a fresh browser some time soon unless someone tells me it's not needed. Is there another bug covering something like that? 

Comment: other applications like Gmail work okay with the current design because they just allow you to have two separate windows open which ignore each other. I guess the fact that you end up using twice as much memory could be seen as a "bug".

**Comment by mr-cheffy** [comment] 2024-12-23 18:14
I agree, but firefox wasn't build with having "essentials" in mind... Since it looks like this issue has been fixed, ill close it and please link me an issue or open another one if you'd like about essentials not being ordered for each window. Thanks!

**Closed as completed by mr-cheffy** 2024-12-23 18:14 UTC
Labels: Bug

**Comment by mikedlr** [comment] 2024-12-23 18:40
Done my best to summarize what I think is outstanding from this in the following new bug: https://github.com/zen-browser/desktop/issues/3961

**Comment by mikedlr** [comment] 2024-12-24 14:53
On 1.0.2-b.3 (Firefox 133.0.3) (64-bit) I have now observed that windows that were pinned as essentials with one container can end up with another. This was one of the problems I was having before which made me open this bug, but I have now opened a new different one for that specific issue.

https://github.com/zen-browser/desktop/issues/3972
