### ISSUE TITLE
Change Tab(s) to Workspace - When tab is transferred, breaks the Compact Sidebar show/hide state

### ISSUE THREAD

**Issue by nategarrow** [zen-browser/desktop#3665] opened 2024-12-12 17:15 UTC
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

## Issue

When a tab is moved from one workspace to a different workspace, it breaks the "hide sidebar" compact mode. The sidebar remains visible and will not auto-hide. I've tried turning compact mode on and off repeatedly, creating new tabs, moving them to a new workspace, but the sidebar will not hide until I close the browser and re-open.

## Expected behavior

The sidebar should auto-hide after the tab is moved to a different workspace.

#### Setup
*  Need at least two work spaces
* Compact mode: ON
  * In my testing, I'm doing "Hide Sidebar" only

#### Actions
1. Open a new tab, go to any page
2. Right click the new tab and select "Change Tab(s) to Workspace" and select a different workspace
3. With Compact Mode: On, the sidebar doesn't hide, blocking everything behind it

Reproducible before and after updating from 1.0.2-b.0 -> 1.0.2-b.1

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.1

### What platform are you seeing the problem on?

Windows

**Comment by nategarrow** [comment] 2024-12-12 17:32
Loom: https://www.loom.com/share/270804070c92435199d52c54b32fb7e7?sid=3beacc98-c0c2-47df-99af-0997f00b242e

More Testing done:
- I can get the sidebar working by right clicking the sidebar and turning compact mode off that way (was previously using the ctrl+alt+c hotkey and that wasn't working)
- After transferring the tab to the new Workspace, right-clicking tabs doesn't work, but right clicking the sidebar does.

**Comment by neurokitti** [comment] 2024-12-21 22:29
if i am not mistaken this is a duplicate of the following issues:
https://github.com/zen-browser/desktop/issues/3046
https://github.com/zen-browser/desktop/issues/2980

thanks for reporting the bug! please check to see if its a repeat first though!

**Closed as completed by neurokitti** 2024-12-21 22:29 UTC
Labels: Bug
