### ISSUE TITLE
Using "peak" with multiple tabs refocuses to the wrong tab

### ISSUE THREAD

**Issue by mikeckennedy** [zen-browser/desktop#2703] opened 2024-11-07 00:23 UTC
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Using the peak feature for opening a new link without fully going there (ALT+click on macOS), when you are working on an active tab that is not the last tab in the tab list will navigate away from the entire tab.

Consider this setup in the tab bar. 

```
tab1
tab2
tab3
tab4
```

If you are on window `tab2` and you ALT+click a link, then dismiss the peak window (escape, click away, etc), when the window is dismissed, the next tab (this time tab3) is selected. 

The whole point of peak is to stay where you are, not jump to another random tab. :)

Love the browser, thank you.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.17

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by RayZ3R0** [comment] 2024-11-07 12:56
Duplicate of #(I dunno man, no one checks for duplicates so there's a lot). Closing as it will be fixed in a18 soon.

**Closed as completed by RayZ3R0** 2024-11-07 12:56 UTC
Labels: Bug

**Comment by mikeckennedy** [comment] 2024-11-07 16:42
Thanks @RayZ3R0 I did search for the peak and got zero results in the issues before posting this.

As you can see, one issue is this one, the other is unrelated.

<img width="631" alt="Screenshot 2024-11-07 at 8 41 42 AM" src="https://github.com/user-attachments/assets/6c8f1864-85f2-4ad9-95e0-1164ceebe224">

I appreciate the help. The snark, not so much.

**Comment by RayZ3R0** [comment] 2024-11-07 16:48
That is because the feature is called glance, not peek/peak. I wasn't trying to be negative, sorry if it came off as that

**Comment by mikeckennedy** [comment] 2024-11-07 22:04
Ah, got it. Sorry I thought it was called Peak. Thanks again for a great fresh take on the browser. :)
