### ISSUE TITLE
can't switch between profiles 

### ISSUE THREAD

**Issue by githlacker** [zen-browser/desktop#3663] opened 2024-12-12 16:49 UTC
### Captchas

- [X] I have read the instructions.
- [ ] I have searched existing issues and avoided creating duplicates.
- [x] I am not filing an enhancement request.

### What happened?

https://github.com/user-attachments/assets/238954f5-10e2-445a-839c-d4a0f8db1e4e

only opening them from `about:profiles` works

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2

### What platform are you seeing the problem on?

Linux

**Comment by eatenpancreas** [comment] 2024-12-13 02:29
Duplicate of https://github.com/zen-browser/desktop/issues/3495

**Comment by githlacker** [comment] 2024-12-13 11:21
yup

**Closed as completed** 2024-12-13 11:23 UTC
Labels: Bug
