### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by aliqut** [zen-browser/desktop#1005] opened 2024-08-28 13:26 UTC
### What happened?

Fresh install. Consistently crashes while simply browsing the zen website.

Could be an issue on my end, but I doubt it since this doesn't happen using vanilla Firefox.

### Reproducible?

- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.32 (64-bit)

### Severity impact

High

### What platform are you seeing the problem on?

Linux

### Relevant log output

```shell
> ./zen                                                                                                                                                                                   
[98005] Sandbox: Unexpected EOF, op 0 flags 02204000 path /sys/devices/system/node
[97813] Sandbox: failed to send broker response to pid 98005: EBADF
[98194] Sandbox: Unexpected EOF, op 0 flags 00 path /sys/devices/system/cpu/present
[97813] Sandbox: failed to send broker response to pid 98194: ENOTSOCK
[Parent 97813, Compositor] WARNING: Call to mmap failed: Bad file descriptor: file /home/runner/work/desktop/desktop/engine/ipc/chromium/src/base/shared_memory_posix.cc:515
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
[1]    97813 segmentation fault (core dumped)  ./zen
```

**Comment by aliqut** [comment] 2024-08-28 13:35
Crashed again, different log output this time. Seems like the issue is specific to Wayland, running Zen in an X11 session works just fine.

```
Crash Annotation GraphicsCriticalError: |[0][GFX1-]: Wayland protocol error: w
p_linux_drm_syncobj_surface_v1#93: error 5: Missing timeline
 (t=215.341) [GFX1-]: Wayland protocol error: wp_linux_drm_syncobj_surface_v1#93: error 5: Missing timeli
ne
Exiting due to channel error.                                                                                                                                                           
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
Crash Annotation GraphicsCriticalError: |[C0][GFX1-]: CompositorBridgeChild receives IPC close with reason=AbnormalShutdown (t=217.222) 
[1]  + 102321 segmentation fault (core dumped)
```

**Comment by n7itro** [comment] 2024-08-28 17:12
Possible duplicate of https://github.com/zen-browser/desktop/issues/296. This will be fixed with Firefox version 130

**Closed by n7itro** 2024-08-28 17:12 UTC
Labels: kind: high severity
