### ISSUE TITLE
Remove the corners of the browser

### ISSUE THREAD

**Issue by kralion** [zen-browser/desktop#1404] opened 2024-09-12 17:15 UTC
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Summary:
In a recent update, Zen Browser introduced a border in Compact Mode, which disrupts the previously full-screen experience. Details:

    Observation: The browser now displays a border even when in Compact Mode, which looks odd and detracts from the immersive experience.
    Previous Behavior: Previously, the browser filled the entire screen, providing a clean and distraction-free interface that I greatly appreciated.
    Current Workaround: I installed a plugin from the Themes Store to remove the corners and achieve a full-screen effect, but the new border remains an issue.

Request:
Please investigate this change and consider reverting to the previous full-screen functionality in Compact Mode, or provide a solution to eliminate the border. Thank you!

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.39

### What platform are you seeing the problem on?

Windows

### Relevant log output
![image](https://github.com/user-attachments/assets/5dac5ddb-6c98-4aaa-a674-eb70a0919e8c)
those black borders

**Comment by perrylets** [comment] 2024-09-12 17:43
You forgot to check the last checkbox

**Comment by mvahaste** [comment] 2024-09-12 17:54
I played around with the [No browser padding](https://zen-browser.app/themes/680424a8-a818-406b-98c5-7726214e2a9f) theme and got it to work for unsplit compact view with the following CSS:
```css
@media (-moz-bool-pref: "zen.view.compact") {
	#tabbrowser-tabpanels:not([zen-split-view]) {
		--zen-webview-border-radius: 0 0 0 0;
		--zen-element-separation: 0;
	}
}
```

Just had to add a case for compact mode and change it a bit as there isn't one by default.
It looks like it does the job, but I haven't extensively tested it.

**Comment by kralion** [comment] 2024-09-12 22:11
Sorry but Where should I add that for having  my Zen Browser with that configuration?

**Comment by mvahaste** [comment] 2024-09-13 05:51
Until it's officially added (if ever) to the theme you can just add it yourself.

Go to `about:profiles` in Zen (URL bar) and open the root directory of the current profile. The `chrome.css` should be located at `chrome/zen-themes/680424a8-a818-406b-98c5-7726214e2a9f`, just add the above CSS at the end of the file. It'll probably get deleted when the theme gets updated but I don't think that happens often since it's a very simple theme.

Also I noticed that the left side has a few pixels of padding still, if you wanna play around with the CSS yourself to maybe find a fix look into the [Browser Toolbox](https://firefox-source-docs.mozilla.org/devtools-user/browser_toolbox/index.html). If I have time to fix it I'll probably open an issue on the theme to maybe get it added.

**Comment by ivanjx** [comment] 2024-09-13 06:40
this also affects full screen video

![image](https://github.com/user-attachments/assets/6ea36593-c396-42c4-ba7b-233721fd7308)

**Comment by mvahaste** [comment] 2024-09-13 06:50
> this also affects full screen video

Is this with my CSS or just a comment on the issue in general? I'm using the last CSS snippet I posted and my fullscreen video is fine.

<details>
<summary>Screenshot</summary>
<img src="https://github.com/user-attachments/assets/ae3f8a40-a056-4e57-9aaf-f6596f676596" />
</details>

**Comment by ivanjx** [comment] 2024-09-13 07:40
no i do not modify anything yet. this should be fixed by the browser itself rather than adding custom css.

**Comment by SstarLit** [comment] 2024-09-13 18:29
> this also affects full screen video
> 
> ![image](https://private-user-images.githubusercontent.com/12814796/367176166-6ea36593-c396-42c4-ba7b-233721fd7308.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyNTIzMDMsIm5iZiI6MTcyNjI1MjAwMywicGF0aCI6Ii8xMjgxNDc5Ni8zNjcxNzYxNjYtNmVhMzY1OTMtYzM5Ni00MmM0LWJhN2ItMjMzNzIxZmQ3MzA4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEzVDE4MjY0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmNzU4MjY1YzM2MTFlMDFhNGRhZjliN2FlMDI0ODc0NThkMzdkOTU2YTYyYTRhMmVjZDVhMzZlMDhiZDdlNTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.blqm_Obg8zYW4rb_SLMpVz1wIHcizmNSGygPQ6eYt-k)

tested on a fresh portable release for sanity, the borders do disrupt fullscreen, and seem to cause very subtle flickering on fullscreen youtube videos somehow, even once paused! has anyone been able to notice this on a fullscreen video, where the background may be solid white?

**Comment by mauro-balades** [comment] 2024-09-13 18:37
This has been fixed for the next release... Ill probably release today or tomorrow... Thanks everyone!

**Closed by mauro-balades** 2024-09-13 18:37 UTC

**Comment by kazi-10g80d** [comment] 2024-11-11 06:40
Same issue, browser is up to date.

Not possible to get rid of the top and bottom margin (was able to get rid of left and right using extension).
Does not happen when video is playing in full screen.

@mvahaste your script worked for me, thank you.

**Comment by kralion** [comment] 2024-11-11 15:16
Solved with this zen mod https://zen-browser.app/mods/bfcc400a-4ecb-4752-bfd2-a68f116a2722

**Comment by kazi-10g80d** [comment] 2024-11-11 18:10
Thanks, it worked for me.

I wish it would show up if we search for remove padding or margin.

**Comment by kralion** [comment] 2024-11-11 23:08
Yeah. but zen mods are good for customizing your browser, other devs are working behind the scenes which is great

**Comment by Irtiza90** [comment] 2025-01-11 13:30
> Solved with this zen mod https://zen-browser.app/mods/bfcc400a-4ecb-4752-bfd2-a68f116a2722

Thank you so much, as little of an issue it might seem like, It was driving me insane.
I do not understand why this isn't by default in the browser

**Comment by Kam0797** [comment] 2025-02-03 21:21
> Solved with this zen mod https://zen-browser.app/mods/bfcc400a-4ecb-4752-bfd2-a68f116a2722

Thankyou man.. you saved my day

**Comment by Kroc** [comment] 2025-02-16 22:16
The borders also prevent being able to throw the mouse to the side of the screen and click on the scrollbar -- how is it that in 2025 no app cares about Fitt's law anymore!? If Zen Browser wishes to keep the border by default that's okay, but please make the scrollbar clickable on the rightmost pixel of the screen!

**Comment by jannis-baum** [comment] 2025-04-27 19:47
Are there any updates on this? I'm on `1.11.5b`, tried @mvahaste suggestion without success and the URL https://zen-browser.app/mods/bfcc400a-4ecb-4752-bfd2-a68f116a2722 just brings me to the homepage which I guess might mean the mod doesn't exist anymore?

I would really like to remove these borders since they seem like quite a bit of wasted space, taking away from the idea of a "zen" experience.

**EDIT:**

Adding the following to the `<profile-dir>/chrome/userChrome.css` does it as off `1.11.5b`:

```css
:root {
    --zen-element-separation: 0px !important;
}
```

However I really think this should be an option or better yet the default for the browser as I don't see why we would want to waste space on these borders

**Comment by Blackheat45** [comment] 2025-05-12 22:58
@jannis-baum method fixed it for me. Finally after all this time, thank you! <3

**Comment by nowm** [comment] 2025-05-22 01:10
> Adding the following to the `<profile-dir>/chrome/userChrome.css` does it as off `1.11.5b`:
> 
> ```css
> :root {
>     --zen-element-separation: 0px !important;
> }
> ```

Another way to achieve the same effect: the `zen.theme.content-element-separation` option in `about:config`. It sets border width in pixels.

**Comment by Nao** [comment] 2025-11-15 14:25
@nowm this is no longer working, as of ~October 2025. I'm not sure which update broke it.
I can confirm @jannis-baum's solution works as of November 2025, as I reached it independently through UI inspection. I wish I'd found this sooner, though! I only found this because I was looking for information on --zen-element-separation.

**Comment by nowm** [comment] 2025-11-15 23:12
> [@nowm](https://github.com/nowm) this is no longer working, as of ~October 2025. I'm not sure which update broke it. I can confirm [@jannis-baum](https://github.com/jannis-baum)'s solution works as of November 2025, as I reached it independently through UI inspection. I wish I'd found this sooner, though! I only found this because I was looking for information on --zen-element-separation.

Umm, it still works for me, for some reason. I use version 1.17.6b (for macOS), which is the latest version right now. The option exists in my `about:config`, and borders are being changed immediately when I change its value.

Also, as I see [in search](https://github.com/search?q=repo%3Azen-browser%2Fdesktop+content-element-separation&type=commits), there were no code changes related to the option after my message. Maybe some conflicting mods, options, or userChrome.css styles?

**Comment by Nao** [comment] 2025-11-18 17:55
I do have the option in my settings, it just doesn't work to remove the final 1-pixel wide column next to the scrollbar.
This is probably an issue limited to Windows (11), I guess.
I didn't change anything after my initial install a few months ago. My userChrome file was created after I had this bug, and only contains the variable fix, as well as a font replacement (Inter Variable everywhere).
I did install a theme that disappeared recently. (It looks like Zen removed theme support?)
I thought it was all related to that change.

**Comment by CastAMCF** [comment] 2025-11-26 02:03
> Adding the following to the `<profile-dir>/chrome/userChrome.css` does it as off `1.11.5b`:
> 
>```css
> :root {
>     --zen-element-separation: 0px !important;
> }
> ```
For me the solution provided by @jannis-baum completely messed up the whole browser make it kinda buggy, so i come up with this (`tested on version 1.17.9b for linux`)
```css
:root[zen-compact-mode="true"] {
	@media -moz-pref("zen.view.compact.hide-tabbar") or -moz-pref("zen.view.compact.hide-toolbar") or -moz-pref("zen.view.use-single-toolbar") {
		& #zen-appcontent-wrapper {
			--zen-element-separation: 0;
		}
		& .browserSidebarContainer {
			--zen-native-inner-radius: 0;
			--zen-big-shadow: none;
		}
	}
}
```
**NOTE:** 
If you are hiding the toolbar on compact mode and it doesn't appear while hovering the mouse, you have 2 options:

1. Do Ctrl+L and hover the mouse on the toolbar while is visible
2. Add this, it will add the top gap back (which is against removing all gaps but the toolbar only appears when hovering this element)
```css
#zen-appcontent-navbar-wrapper {
	--zen-element-separation: 8px;
}
```
