### ISSUE TITLE
Arrow keys stop working after a while on Linux

### ISSUE THREAD

**Issue by ItaruYasha** [zen-browser/desktop#4015] opened 2024-12-26 20:47 UTC
### Captchas

- [X] I have read the instructions.
- [x] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

After using the Zen browser for a while, the arrow keys on the main keyboard stop working, while the arrow keys on the numpad remain functional. This issue causes keyboard shortcuts that rely on the main arrow keys to fail, making text navigation cumbersome. On a laptop where the "home" key is combined with the left arrow key (accessible via the Fn key), pressing Fn and the arrow key also doesn't work. All other applications outside the browser function correctly. Closing and reopening the browser temporarily resolves the issue.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.2

### What platform are you seeing the problem on?

Linux

**Comment by kuqquk** [comment] 2024-12-27 11:38
Is this related to #2743 ?

**Comment by mr-cheffy** [comment] 2024-12-27 18:44
Duplicate of https://github.com/zen-browser/desktop/issues/2743

**Closed as completed by mr-cheffy** 2024-12-27 18:44 UTC
Labels: Bug
