### ISSUE TITLE
No File, Edit, View, Window, Help menu in Zen Browser

### ISSUE THREAD

**Issue by KjalaNIX** [zen-browser/desktop#282] opened 2024-08-16 15:21 UTC
### What happened?

I'm reposting this issue because I mistakenly put the previous one in medium severity whereas actually there is no workaround. Pressing Alt after ticking the menu bar option in the conext menu does nothing and I've not found an extension to replicate this core browser function.
My proposal is that the tab manager could be recycled as this menu.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0.-a.20

### Severity impact

High

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment] 2024-08-21 09:31
Duplicate of https://github.com/zen-browser/desktop/issues/281

**Closed by mauro-balades** 2024-08-21 09:31 UTC
Labels: kind: high severity
