### ISSUE TITLE
[BUG] Context Menu Exceeds Display Area When Right-Clicking Links or Web Pages

### ISSUE THREAD

**Issue by CodingHashira** [zen-browser/desktop#1910] opened 2024-10-05 03:25 UTC
### Captchas

- [x] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

When right-clicking on a link or web page in Zen Browser, the context menu sometimes appears in a position where the top options, such as "Open in New Tab," go beyond the screen display. This makes it difficult to access those options, especially on smaller screens or when the browser window is resized.

**Screenshots:**
**1**
![screenshot-2024-10-05-03-15-55](https://github.com/user-attachments/assets/3064a8b0-10c8-4619-a63e-89daf027994d)

**2**
![screenshot-2024-10-05-03-21-16](https://github.com/user-attachments/assets/2a351636-8592-48ea-ac82-4235a98d85b2)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.7 (64-bit)

### What platform are you seeing the problem on?

Linux (Pop!_OS 24.04)

**Comment by bhaumik-tripathi** [comment] 2024-10-05 04:24
hello, @iamkartiknayak , your issue is not reproducible on my end(I use fedora), when there is less space, the context menu places arrows on top( and/or bottom), hovering on which you can go up and down. Is it also present in yours?
![Screenshot from 2024-10-05 09-50-10](https://github.com/user-attachments/assets/590f1884-9650-4cda-a85f-86b9c37445de)

**Comment by iamkartiknayak** [comment] 2024-10-05 05:30
> your issue is not reproducible on my end(I use fedora),

I'm using Pop!_OS 24.04 Alpha. It might still be reproducible in other systems.

**Comment by salamijason** [comment] 2024-10-30 11:14
Bug could not be reproduced on latest version 1.0.1-a.14. Could you please try again on the latest ver and let me know how it goes?

**Comment by kodebarista** [comment] 2024-10-31 12:52
I think this bug can only be reproduced in lower res displays. Still reproducible in my external display with res `1440x800` but not in FHD
- New tab & New container tab overflow above 
- overflow in bottom


**Overflow at top:**

![image](https://github.com/user-attachments/assets/fc6203bb-ef2d-4b17-949a-38466fe3bacc)

**Overflow at bottom:**

![image](https://github.com/user-attachments/assets/68d29912-9ebf-4b45-a9c7-74a42c1bfd54)

**Items missing in bottom overflow:**
![image](https://github.com/user-attachments/assets/744dc7e5-fe7d-42df-9cc9-5a93dc93ac5a)

**Comment by salamijason** [comment] 2024-12-02 16:09
Hi are you still getting this on the latest version of Zen? (a22 as of this comment.) We tried to recreate this on our side a while back but couldnt

**Comment by salamijason** [comment] 2024-12-15 08:42
No response in 2 weeks, will be closing this issue. Please reopen if you still get the bug.

**Comment by kodebarista** [comment] 2024-12-16 12:27
> Hi are you still getting this on the latest version of Zen? (a22 as of this comment.) We tried to recreate this on our side a while back but couldnt

Sorry, I couldn't get back to you in time. The issue still persists for smaller resolution displays. Tested on `1440x800` 

Screenshot of top portion of screen in `1440x800` display. You can see the XDM extension above the bookmarks.

![screenshot-2024-12-16-12-26-09](https://github.com/user-attachments/assets/03fe1a50-35b4-4b9d-8a4e-86e285333f97)

**Comment by kodebarista** [comment] 2024-12-16 12:33
It'll either overflow at the top or bottom. Only possible solution seems to be setting up a scroll based on resolution of display and number of items in context menu.

Also can you please re-open this issue

**Comment by salamijason** [comment] 2024-12-21 07:17
Hmm, none of us on the bug team experience this issue currently. Could you please try on a new profile and let us know? Here's a quick [guide](https://docs.zen-browser.app/guides/manage-profiles)

**Comment by salamijason** [comment] 2024-12-21 10:55
I've also been told that this _could_ be a script issue. Could you try a diff installation? (flatpak, appimage, tarball) Please let us know which of the installations you have this bug on. 

Also don't forget to try a new profile!

**Comment by kodebarista** [comment] 2024-12-21 12:14
I recently moved from Pop OS to Fedora & the issue doesn't seem to exist in this installation.

Closing this issue as it is not reproducible anymore

**Closed by kodebarista** 2024-12-21 12:14 UTC
