### ISSUE TITLE
Console devtools not showing return

### ISSUE THREAD

**Issue by jackskelt** [zen-browser/desktop#636] opened 2024-08-25 01:33 UTC
### What happened?

Return codes evaluated in the devtools Console tab are not being shown in Zen

![Zen console printscreen](https://github.com/user-attachments/assets/c52c68b1-1658-4528-93cf-6b2bd4995127)

In the Firefox version 127.0 is working normally

![Firefox console printscreen](https://github.com/user-attachments/assets/1fc5d90b-c1e9-4983-b05a-eedc71153fe0)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.28

### Severity impact

Enhancement

### What platform are you seeing the problem on?

Linux

**Comment by dayblox** [comment] 2024-08-25 01:42
Same on 1.0.0-a.29

**Comment by Moshyfawn** [comment] 2024-08-25 02:32
Duplicate of #593

**Comment by SuperluminalKnight** [comment] 2024-08-25 05:10
Its not just not showing returns. It's not executing javascript at all
````js
let a = 5;
a
````

You'll get a preview saying `a` is undefined

**Closed** 2024-08-25 06:41 UTC
Labels: kind: enhancement
