### ISSUE TITLE
tab bar is confusing between right and left placement

### ISSUE THREAD

**Issue by ivanjx** [zen-browser/desktop#1744] opened 2024-09-26 03:22 UTC
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

when i enable tabs on the right, this happens:

https://github.com/user-attachments/assets/0a8139ba-f013-4206-91e5-7f6afdaff4a2

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.5

### What platform are you seeing the problem on?

Linux

**Comment by sjclayton** [comment] 2024-09-26 15:42
I had this happen randomly in 1.0.1-a.5 on Linux while toggling compact mode on and then back off again a short while later, restarting the browser seemed to fix it. 

Will keep an eye out to see if it happens again, and see if there is a concrete way to reproduce it.

**Comment by KarimElsayad247** [comment] 2024-09-27 13:36
It's happening currently for me.  1.0.1-a.5 on Linux 

![image](https://github.com/user-attachments/assets/7c99733f-85d9-4dc6-a6cf-a47db1a8b282)

And this funny thing happens when I disable "Tabs on the right" and toggle tabs expansion

https://github.com/user-attachments/assets/a6ddd974-1ead-4f38-bfc8-ac5984ff9bae

**Comment by KarimElsayad247** [comment] 2024-09-27 13:40
Lol I seem to have reached a state where it thinks it's on the left and right at the same time

https://github.com/user-attachments/assets/5b8015fe-0b4a-4aa5-8ee3-ae9a82f1f479

Notice how stuff on the right kinda jiggles heavily? this suggests to me that the bar appeared on the right, then was moved to the left. Maybe there are two values for right bar check?

**Comment by khan5ula** [comment] 2024-10-09 06:15
Similar issue here. Opening history panel (ctrl + h) or bookmarks panel (ctrl +b) causes the tab bar to shift from right to left. So far I've only been able to revert the tab bar position back to right by closing the browser.

**Comment by ivanjx** [comment] 2024-10-12 04:56
introduces new bugs:
- expand on hover shifts the whole tab content (again).
- ![image](https://github.com/user-attachments/assets/dfee2b5b-fe1a-44b4-bc8c-6f151552abe8)

**Comment by salamijason** [comment] 2024-11-08 12:49
Heylo, looks like this post was made a while back and the right sidebar has been polished since. Are you still getting this issue? (latest ver a.17 as of this comment)

**Comment by salamijason** [comment] 2024-11-16 13:49
No response in 1 week. For the sake of keeping the roadmap clean, I'll be closing this issue but please reopen if you still get this issue. Thank you.

**Closed by salamijason** 2024-11-16 13:49 UTC
