### ISSUE TITLE
Bookmarks stop working. Impossible to add and manage

### ISSUE THREAD

**Issue by iuvi7** [zen-browser/desktop#3886] opened 2024-12-19 06:01 UTC
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I updated Zen to 1.0.2-b.2 (2024-12-14) 64-bit Windows version

Then, i notice:

If i use Ctrl+D or just push on Star in address bar - it get blue, but **it does not** actually add bookmark to my vault anymore. **Also** i can not choose to wich holder to save it anymore, no more fallout window to do so. In previous version\release it was works just fine

Thanks! 

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.2

### What platform are you seeing the problem on?

Windows

**Comment by machiav3lli** [comment] 2024-12-19 13:49
duplicate of #3797

**Closed as completed** 2024-12-19 14:08 UTC
Labels: Bug
