### ISSUE TITLE
Two new tab buttons in the sidebar after new update

### ISSUE THREAD

**Issue by Kroszborg** [zen-browser/desktop#2486] opened 2024-10-31 17:45 UTC
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Two new tab buttons in the sidebar after new update, Both are functional
![Screenshot 2024-10-31 224343](https://github.com/user-attachments/assets/991be703-519e-4805-8837-11511e57797f)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.16

### What platform are you seeing the problem on?

Windows

**Comment by C0untZero** [comment] 2024-10-31 18:05
Same behavior here. The bot has it wrong though.

**Comment by Axenide** [comment] 2024-10-31 20:27
One is the one that Zen adds from the settings at the bottom of the tab list, the other is the one from the toolbar. You can disable the first or remove the second one by editing the layout.

**Comment by nihalsheikh** [comment] 2024-11-01 06:01
Same issue here, 2 new Open new tab buttons in sidebar... and the option to hide the Open new tab button from the Minimal Sidebar extension (Zen Mod) also doesn't work properly.

![Sidebar-Image](https://github.com/user-attachments/assets/1f023206-aea3-4113-90e7-a0de59ec6db3)

**Comment by RayZ3R0** [comment] 2024-11-01 11:02
Can you remove the other one with customize toolbar or is it fixed? Right click on sidebar to select customize toolbar and try taking it out and dropping it below and see if it works

**Comment by C0untZero** [comment] 2024-11-01 17:01
Right, one can be removed. Now that I think about it, I did have to add the new tab button myself at one point since one wasn't present. I guess it was now just added by default, which is why some of us who added it manually before are now seeing it double.

**Comment by RayZ3R0** [comment] 2024-11-02 09:49
Yeah its not really a bug and can be removed. Closing this

**Comment by Kroszborg** [comment] 2024-11-02 15:16
> Yeah its not really a bug and can be removed. Closing this

i do think its a bug @RayZ3R0 , while i removed one button of new tab it now looks like this-
![image](https://github.com/user-attachments/assets/a1f5f411-f3c4-41ba-9041-6332508d4e20)

there is no way to position the button to the end of the bar which would be better since while switching tabs, you sometimes click the new tab button and instead of switching it opens a new tab. Very annoying, fixing this issue would be a quality of life improvement.

**Comment by RayZ3R0** [comment] 2024-11-02 19:51
> > Yeah its not really a bug and can be removed. Closing this
> 
> i do think its a bug @RayZ3R0 , while i removed one button of new tab it now looks like this- ![image](https://private-user-images.githubusercontent.com/87552456/382481838-a1f5f411-f3c4-41ba-9041-6332508d4e20.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA1NzcyODgsIm5iZiI6MTczMDU3Njk4OCwicGF0aCI6Ii84NzU1MjQ1Ni8zODI0ODE4MzgtYTFmNWY0MTEtZjNjNC00MWJhLTkwNDEtNjMzMjUwOGQ0ZTIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAyVDE5NDk0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUxMzZkODVhODg2NjdmNWFmOTJjZjI5YTM5YjY0Mzg2ZGU4YzhiMjI4NzQ3ZGQwNDE2NGQ2NTJiZmNlZWQwMDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.rYTyVwCxlYIAnGPtnQwlamWqXa8dlv2_QmVi4YjVgnw)
> 
> there is no way to position the button to the end of the bar which would be better since while switching tabs, you sometimes click the new tab button and instead of switching it opens a new tab. Very annoying, fixing this issue would be a quality of life improvement.

Uhh, I did not really understand what you meant. Which new tab button did you remove? the top one or the bottom one?

**Comment by salamijason** [comment] 2024-11-10 03:32
This is a dupe of https://github.com/zen-browser/desktop/issues/2449 and it should be solved now. 
Configure your desired settings here: 
![image](https://github.com/user-attachments/assets/6032704f-1fde-4c17-838c-15c63378a61b)

In a.18, the draggable toolbar + button has been removed and I'm not sure whether it'll be added back or not.

**Closed as completed by salamijason** 2024-11-10 03:32 UTC
