### ISSUE TITLE
Sidebar does not retain the state of the webpage

### ISSUE THREAD

**Issue by Akhash16** [zen-browser/desktop#2320] opened 2024-10-25 10:31 UTC
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

If I have a video playing on YouTube in the sidebar and close the sidebar, I can still hear the audio. However, when I click the sidebar icon in the bottom left to reopen it, the page refreshes, and the site’s state is lost. This happens for every webpage.

### Reproducible?

- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.12

### What platform are you seeing the problem on?

Windows

**Comment by sjclayton** [comment] 2024-10-25 13:15
Duplicate of #2022

This should be closed.

**Closed as not planned** 2024-12-02 16:09 UTC
Labels: Bug
