### ISSUE TITLE
adjust hovering for vertical tab

### ISSUE THREAD

**Issue by LemuelDayrit** [zen-browser/desktop#596] opened 2024-08-24 17:07 UTC
### What happened?

is someone know how to adjust hovering everytime my mouse goes to the left then shows the vertical tabs because when i go to history then when i was about to click it already hovers which is annoying 

here's the video: 

https://github.com/user-attachments/assets/3ae08e67-7ee1-4450-b60f-0f4edd22b751

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0 a.28

### Severity impact

Low

### What platform are you seeing the problem on?

Linux

**Comment by Moshyfawn** [comment] 2024-08-24 17:11
The hover area issue is a duplicate of #520 and is fixed for the next release.

**Comment by dhruvvk2326** [comment] 2024-08-24 17:11
Its been corrected for next release and is same as issue #520

**Comment by NOCanoa** [comment] 2024-08-24 17:21
Lol 2 comments that didn't see eatch other xD

**Closed by NOCanoa** 2024-08-24 17:21 UTC
Labels: kind: low severity
