### ISSUE TITLE
Windows "Show accent color on title bars and window borders" option looks broken with new titlebar

### ISSUE THREAD

**Issue by CyberSer0** [zen-browser/desktop#3546] opened 2024-12-11 06:32 UTC
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Hello, I updated to the newest 1.0.2-b.0 version and I have the accent color shown on title bars by default on my system. I noticed the new titlebar looks kind of broken with that option enabled, turning it off fixes the issue.
When it's on:
![image](https://github.com/user-attachments/assets/494f0e58-a393-407d-b098-577a3c064b94)
![image](https://github.com/user-attachments/assets/bef6e028-5413-4190-9cf4-2b87b08cce15)

When it's off:
![image](https://github.com/user-attachments/assets/0a2a5575-1229-4dbe-b45d-8dea27819d5b)

### Reproducible?

- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.0

### What platform are you seeing the problem on?

Windows

**Comment by PHATWalrus** [comment] 2024-12-11 07:12
![image](https://github.com/user-attachments/assets/7b4f3e8e-575a-43cf-865b-858df00dcb99)
same here

**Comment by daFinndus** [comment] 2024-12-11 08:56
Same. Also on Windows 11 and with the Version 1.0.2-b.0.

It's also fixed for me after toggling off "Show accent colour on title bars and windows borders" in the Window Settings > Personalisation > Colours > Accent Colour.

![image](https://github.com/user-attachments/assets/0648ed71-77f6-49e1-b2a5-0319741429ec)

**Comment by DudeSjef** [comment] 2024-12-11 12:19
Same thing here, Windows 11, Zen build 1.0.2-b.0.
My blue accent colour makes the UI buttons almost invisible due to the contrast. After disabling the 'Show accent color on title bars and window borders' setting, the issue disappears.

<img width="1120" alt="Screenshot 2024-12-11 131454" src="https://github.com/user-attachments/assets/61c7793d-d078-4160-819a-6e4ce0d72eb7">

**Comment by CyberSer0** [comment] 2024-12-11 13:12
I also noticed that the close button stopped working, should this be another issue in itself?
https://github.com/user-attachments/assets/f2d8e0c7-0389-4bc9-9daf-9b1102babf83

**Comment by DudeSjef** [comment] 2024-12-11 13:30
@CyberSer0 I do not have that issue. Although I would encourage you to open a new issue if this is an issue with the Zen browser, if one doesn't exist already.

**Comment by r7zq** [comment] 2024-12-11 15:05
same here windows 11, Zen build 1.0.2-b.0

but it's only on normal window it doesn't show on private window
![Screenshot (5)](https://github.com/user-attachments/assets/11615259-06e7-4602-a7f3-ee0f07cdb291)

**Comment by lug-mbs** [comment] 2024-12-12 07:46
Hi,
im Running 1.0.2-b.1 and looks to be the same issue as 1.0.2-b.0
![image](https://github.com/user-attachments/assets/2efc9df6-0327-4a5d-8a98-1bedc0b9eb41)

**Comment by mr-cheffy** [comment] 2024-12-20 20:39
Duplicate of https://github.com/zen-browser/desktop/issues/3469

please god search for duplicates before adding a new issue

**Closed as completed by mr-cheffy** 2024-12-20 20:39 UTC
Labels: Bug
