### ISSUE TITLE
Hiding toolbar in Compact Mode breaks Profile Switcher

### ISSUE THREAD

**Issue by AQDuck97** [zen-browser/desktop#3990] opened 2024-12-25 11:51 UTC
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

When I click the profile button in an expanded sidebar while the top bar is hidden, the profile switcher pops up for a split second then disappears and the sidebar gets stuck.
Workaround is to temporarily disable compact mode and do the profile switch, then re-enable compact mode.

Confirmed on Zen `1.0.2-b.2` - `1.0.2-b.4`, tested on both a desktop running Arch Linux with Hyprland and a laptop running Fedora with KDE.
![zenbug](https://github.com/user-attachments/assets/ed4e8ecc-6937-4a75-9d56-bea233a91e85)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.4

### What platform are you seeing the problem on?

Linux

**Comment by neurokitti** [comment] 2024-12-28 00:23
this is a duplicate of: https://github.com/zen-browser/desktop/issues/3877

fyi please check that an issue is not a duplicate before posting!

**Closed as completed by neurokitti** 2024-12-28 00:23 UTC
Labels: Bug
