### ISSUE TITLE
New Tab button missing from toolbar/customisation

### ISSUE THREAD

**Issue by VuthMuul** [zen-browser/desktop#2793] opened 2024-11-10 03:10 UTC
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

a18 removed the New Tab button from customisation. This means if you disable the "new tab in tab list" there is now no New Tab button at all.

Removing the button from the default layout in favour of the embedded one is fine, but it needs to remain available in the customisation selection.

![image](https://github.com/user-attachments/assets/d0d636c7-5771-4965-a08b-9bb646fdb772)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.18

### What platform are you seeing the problem on?

Windows

**Comment by wysh3** [comment] 2024-11-10 03:21
yeah i would love the have a moveable new tab button back

**Comment by kar731** [comment] 2024-11-10 03:50
Duplicate of #2778

**Closed as not planned** 2024-12-18 16:06 UTC
Labels: Bug
