### ISSUE TITLE
The browser window is literally TOO wide to use.

### ISSUE THREAD

**Issue by kris3713** [zen-browser/desktop#2440] opened 2024-10-31 03:22 UTC
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

The window for the Zen Browser is much wider than in the previous version.

Furthermore, whoever the developer is, it is important to bear in mind that not everyone possess a wide monitor.

https://github.com/user-attachments/assets/3645634f-573d-4bb8-93b4-8fd56e5815e7

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

I literally can't tell because the window of the Zen Browser is too damn wide!

### What platform are you seeing the problem on?

Windows

### Relevant log output

```shell
Same problem that I explained in the VERSION section.
```

**Comment by kar731** [comment] 2024-10-31 04:25
Duplicate of #2434 

You can temporarily fix this by hiding the bookmarks toolbar.

**Comment by lightcax** [comment] 2024-10-31 05:25
same problem, makes the browser unusable

**Comment by gkuba** [comment] 2024-10-31 05:57
Same here takes up 2/3 of my two 2560x1440 screens to see the whole window. I can confirm kar731's recommendation fixed it for me.

**Comment by RayZ3R0** [comment] 2024-10-31 06:16
Duplicate of #2434 Please move there

**Closed as completed by RayZ3R0** 2024-10-31 06:16 UTC
Labels: Bug

**Comment by kris3713** [comment] 2024-10-31 17:10
> Duplicate of #2434
> 
> You can temporarily fix this by hiding the bookmarks toolbar.

I will just stick with the previous version until this is patched.
