### ISSUE TITLE
Rounded corners breaking on specific websites

### ISSUE THREAD

**Issue by vshwjth** [zen-browser/desktop#3844] opened 2024-12-17 06:37 UTC
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Basically on some website the clipping applied to round the corners do not work well. causing the website to have sharp corners.

Happens to me on the release notes page and official website.

I am on macOS 14.7.1

https://github.com/user-attachments/assets/67fa39f2-5282-46fc-bd68-e2cc8dfda1ea

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.2

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by JSGRD22** [comment] 2024-12-17 06:57
Duplicate of  #3053  #497

**Closed as duplicate** 2024-12-21 10:19 UTC
Labels: Bug
