### ISSUE TITLE
Moving tab to another workspace causes context menu stuck

### ISSUE THREAD

**Issue by Naezr** [zen-browser/desktop#3706] opened 2024-12-13 12:22 UTC
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Steps to reproduce:
- Turn on compact mode for clarity
- Right click on a tab > Change Tab(s) To Workspace

After moving the tab to another workspace, the sidebar does not slide back in. Also, when right-clicking on any tab, nothing happens. To remove this, I have to right click somewhere on the web page.

According to my assumptions this happens because when moving a tab to another workspace, the context menu is not closed correctly, and as if remains open, although it is not displayed on the screen. Opening another type of context menu resets the previous one, so the effect disappears

https://github.com/user-attachments/assets/1e9c8dcd-07ab-428b-85b7-f280a9e42980

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.1

### What platform are you seeing the problem on?

Linux

**Comment by mandiuk** [comment] 2024-12-13 13:24
Same here.
Windows 11, 1.0.2-b.1 (Firefox 133.0) (64-bit)

**Comment by rdaniel0** [comment] 2024-12-18 01:03
Duplicate issues for older version `1.0.1-a.19`
https://github.com/zen-browser/desktop/issues/3046
https://github.com/zen-browser/desktop/issues/2980

**Comment by rdaniel0** [comment] 2024-12-18 01:05
Confirming issue still exists in `1.0.2-b.2` on Windows

**Comment by neurokitti** [comment] 2024-12-21 22:29
if i am not mistaken this is a duplicate of the following issues:
https://github.com/zen-browser/desktop/issues/3046
https://github.com/zen-browser/desktop/issues/2980

thanks for reporting the bug! please check to see if its a repeat first though!

**Closed as completed by neurokitti** 2024-12-21 22:29 UTC
Labels: Bug
