### ISSUE TITLE
Tab group indicator showing in Workspace associated with that tab group

### ISSUE THREAD

**Issue by Evthestrike** [zen-browser/desktop#1537] opened 2024-09-18 18:54 UTC
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

![Zen_Browser_Issue](https://github.com/user-attachments/assets/68743603-cce9-4fe2-900d-3987d959439b)

This "Coding" workspace is associated with the tab group whose color is blue. All four tabs in the image are in the same tab group, but one of them has the blue tab group indicator. That tab should match the others and not have the indicator. This is a recurring issue, and it happens in other workspaces associated with other tab groups as well.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

Mozilla Zen 1.0.1-a.1-1

### What platform are you seeing the problem on?

Linux

**Comment by sjclayton** [comment] 2024-09-19 02:46
Seems like a dupe of #1472

**Closed** 2024-09-21 06:12 UTC
