### ISSUE TITLE
Screenshot button not matching selected color

### ISSUE THREAD

**Issue by GodPuffin** [zen-browser/desktop#3755] opened 2024-12-15 00:47 UTC
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

When using Firefox's Built in Screenshot (Ctrl+Shift+S), the buttons to download or copy dont match the selected color theme. Rather they seem to be the default zen colors.

Image: Purple is selected but the bottons are orange

![image](https://github.com/user-attachments/assets/6d3eb256-9ec0-4e07-98f3-1133a3424b8a)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.1

### What platform are you seeing the problem on?

Windows

**Comment by JSGRD22** [comment] 2024-12-17 13:29
Duplicate of #3739. This is also present in many other UI elements.

**Closed as completed** 2024-12-17 20:10 UTC
Labels: Bug
