### ISSUE TITLE
Appimage fails to run

### ISSUE THREAD

**Issue by thebobbyboy420** [zen-browser/desktop#2103] opened 2024-10-14 22:58 UTC
### Captchas

- [ ] I have read the instructions.
- [ ] I have searched existing issues and avoided creating duplicates.
- [ ] I am not filing an enhancement request.

### What happened?

Appimage fails to run on a fresh install of EndeavourOS KDE 6.2

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

latest app image

### What platform are you seeing the problem on?

Linux

### Relevant log output

```shell
./zen-specific.AppImage 
QFont::fromString: Invalid description 'Noto Sans,11,-1,5,400,0,0,0,0,0,0,0,0,0,0,1'
QFont::fromString: Invalid description 'Hack,11,-1,5,400,0,0,0,0,0,0,0,0,0,0,1'
QFont::fromString: Invalid description 'Noto Sans,11,-1,5,400,0,0,0,0,0,0,0,0,0,0,1'
QFont::fromString: Invalid description 'Noto Sans,11,-1,5,400,0,0,0,0,0,0,0,0,0,0,1'
execv error: No such file or directory
```
```

**Comment by Samueru-sama** [comment] 2024-10-15 04:54
Duplicate of #312

**Comment by thebobbyboy420** [comment] 2024-10-15 04:58
appimagelauncher works 100% fine for every appimage i have on my system 

i will not install something else to get your appimage to work sorry

**Comment by Samueru-sama** [comment] 2024-10-15 05:12
> appimagelauncher works 100% fine for every appimage i have on my system
> 
> i will not install something else to get your appimage to work sorry

You sure? try these: 

https://github.com/cemu-project/Cemu/releases
https://github.com/qarmin/czkawka/releases/tag/8.0.0
https://github.com/ivan-hc/GIMP-appimage/releases/tag/continuous-stable

Also did the yuzu appimage ever work with appimage launcher? I was never able to get it to work despite the fact that it never used the static appimage runtime, which is the reason appimagelauncher is broken here. 

[See reasoning](https://github.com/cemu-project/Cemu/issues/653#issuecomment-1440108288)

The Zen appimage and the few I linked use the static appimage runtime, which gets rid of the libfuse2 dependency (a common issue that affects appimages since libfuse2 no longer comes installed by default) it also switches to zstd compression which results in smaller appimages that startup faster. 

So there are two choices, either go back to an EOL library, break the appimage for new distros and increase the startup time by using gzip or switch to one of the many appimage integration tools that already support the static runtime without issues, like Gearlever or AM. 

Edit: Also Zen has its own install script for the appimage.

**Comment by thebobbyboy420** [comment] 2024-10-15 06:03
its working now i installed gearlever thanks all

**Comment by sjclayton** [comment] 2024-10-15 06:39
@elogicuk 

If it is working properly for you now, this can be closed. Thanks!

**Closed as completed** 2024-10-20 09:24 UTC
