### ISSUE TITLE
Importing from another browser is detected as a malware by Sophos Endpoint

### ISSUE THREAD

**Issue by michelchafouin** [zen-browser/desktop#268] opened 2024-08-15 09:37 UTC
### What happened?

After installing the portable version and launching it for the first time, I clicked import settings / bookmarks from the wizard and it got detected as a malware.

Creds_2a (T1555.003) detected at C:\Users\chafouin\Desktop\zen\zen.exe

I use Firefox and imported settings from other browsers a few months ago without any warning.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.19

### Severity impact

Medium

### What platform are you seeing the problem on?

Windows

**Comment by Yasunaii** [comment] 2024-08-15 23:55
I'm not in the best position to explain everything but I'm attaching some reddit posts that talk about it (the first has the dev's answer on the subject). 

But basically it is false positive because Zen lacks signature is that it is quite tedious to do so anti-virus detects it 

https://www.reddit.com/r/zen_browser/comments/1esh723/comment/li7e7o6/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button

https://www.reddit.com/r/browsers/comments/1egxdlq/kaspersky_detected_a_trojan_in_zen_browser/

https://www.reddit.com/r/zen_browser/comments/1ehvcsu/windows_defender_flags/

**Comment by fritol** [comment] 2024-08-21 01:10
avg does the same Win64:Evo-gen [Trj] zen

**Comment by Donnnno** [comment] 2024-08-25 09:59
We're working on getting an app-signature for Windows, that will likely fix the issue!
https://github.com/zen-browser/desktop/issues/432
https://ko-fi.com/zen_browser/goal?g=210

**Comment by mauro-balades** [comment] 2024-08-29 22:39
Duplicate of https://github.com/zen-browser/desktop/issues

**Closed by mauro-balades** 2024-08-29 22:39 UTC
Labels: kind: medium severity
