### ISSUE TITLE
Sometimes the auto-hidden sidebar becomes transparent when it pops up

### ISSUE THREAD

**Issue by lindongbin** [zen-browser/desktop#1063] opened 2024-08-30 03:37 UTC
### What happened?

Sometimes the auto-hidden sidebar becomes transparent when it pops up
![ec742627-0077-4aac-924d-2126260337c8](https://github.com/user-attachments/assets/05fea7b3-1473-46df-8bc1-f6f8e1a6df81)

Click the left or right button on the page at will and it will return to normal.
![518de9ed-7f32-4e39-bd8a-af5a86f12256](https://github.com/user-attachments/assets/a12be20d-a21e-441c-9433-65edbc279507)

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a32

### Severity impact

Low

### What platform are you seeing the problem on?

Windows

**Comment by n7itro** [comment] 2024-09-04 20:54
Duplicate of #1033

**Closed by n7itro** 2024-09-04 20:54 UTC
Labels: kind: low severity
