### ISSUE TITLE
I can't open any tabs (i need reopen the zen browser)

### ISSUE THREAD

**Issue by QuesBo** [zen-browser/desktop#2479] opened 2024-10-31 15:54 UTC
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [ ] I am not filing an enhancement request.

### What happened?

When the computer goes to sleep and I turn it back on, zen browser locks up. I can't open any tabs and it acts like I have no internet. I have to restart it and I'm tired of doing this. Every time my computer goes to sleep I restart zen browser. [Macbook Pro M1 2020 (Sequoia 15.1 (24B83))]  [Zen Browser 1.0.1-a.16 (Firefox 132.0) (aarch64)]

https://github.com/user-attachments/assets/a9017d66-468a-4e24-b2bd-f3fb93aab8fe

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.16

### What platform are you seeing the problem on?

macOS - aarch64

### Relevant log output

```shell
I don't know how to do it
```

**Comment by JayTheCoderX** [comment] 2024-10-31 16:14
This also happens for me, however it only affects inactive tabs and I can open new tabs without issue. This issue started with the most recent update

**Comment by freedom0116** [comment] 2024-10-31 16:14
Same problem happens on Windows. My system is Windows 10 22H2 and browser version 1.0.1-a.16 (64-bit)

**Comment by QuesBo** [comment] 2024-10-31 16:41
This time my computer wouldn't go to sleep. Suddenly several tabs stopped opening. I don't know what to do now. My first browser was Zen Browser, but now I'm going back to Safari Browser. I'm tired of this.

https://github.com/user-attachments/assets/a1553b01-24fe-4fbf-95e1-3c2d100b5328

**Comment by asmund20** [comment] 2024-10-31 16:57
Have the same issue, on ubuntu, going back to the previous version.

**Comment by theafterglow** [comment] 2024-10-31 17:16
okay so i'm not the only one and this started happening with the latest(?) update
edit: windows 11 pro 23h2 64bit

**Comment by rui-ad-monte** [comment] 2024-10-31 17:17
Same here, this start happening in the last update. In Windows 11

**Comment by Scridgeon** [comment] 2024-10-31 18:09
> This also happens for me, however it only affects inactive tabs and I can open new tabs without issue. This issue started with the most recent update

I'm noticing the same thing. I turned off the tab unloader feature until this bug is addressed.

**Comment by Frestein** [comment] 2024-10-31 23:11
Duplicate of https://github.com/zen-browser/desktop/issues/2436.

**Comment by aier9500** [comment] 2024-11-01 00:56
> This also happens for me, however it only affects inactive tabs and I can open new tabs without issue. This issue started with the most recent update

I'm using the Flatpak version of Zen 1.0.1-a.16 on NixOS and it only affects unactive tabs, too.

**Comment by DevSnyco** [comment] 2024-11-01 04:53
fixed with new release `1.0.1-a.17`, y'all can close this now.

**Comment by freedom0116** [comment] 2024-11-01 10:51
> fixed with new release `1.0.1-a.17`, y'all can close this now.

thanks so much for the fix

**Comment by RayZ3R0** [comment] 2024-11-01 11:12
Its fixed in a.17 closing the issue

**Closed as completed by RayZ3R0** 2024-11-01 11:12 UTC
Labels: Bug

**Comment by rihards-simanovics** [comment] 2025-03-17 16:04
Hey @RayZ3R0, it looks like there is a regression. Sleeping tabs are not recovering in version 1.9.1b (Firefox 136.0.1) (64-bit).

https://github.com/user-attachments/assets/5ee7abe3-a6eb-4632-b89b-3c76961cf952
