### ISSUE TITLE
Full browser overflows

### ISSUE THREAD

**Issue by BramLeisink** [zen-browser/desktop#3036] opened 2024-11-15 16:37 UTC
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

For some reason, the whole browser overflows. When not in compact mode, the sidebar doesn't overflow.
My PC runs Fedora.

https://github.com/user-attachments/assets/ccef5a90-e88a-4944-a198-30800aec2434

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1

### What platform are you seeing the problem on?

Linux

**Comment by LiamHammersley** [comment] 2024-12-08 03:42
I have had this issue too. I have found it happens after I have watched a video in Fullscreen and persists after I have closed and reopened the Browser.

I am running Windows 11 and the Zen Twilight 1.0.1-t.22 (Firefox 133.0) (2024-12-07) (64-bit)

**Comment by Woutuuur** [comment] 2024-12-17 15:48
Duplicate of https://github.com/zen-browser/desktop/issues/2731, caused by floating find bar mod.

See: https://github.com/zen-browser/desktop/issues/2731#issuecomment-2519394047

**Closed as completed** 2024-12-18 22:57 UTC
Labels: Bug
