### ISSUE TITLE
Unloaded apps do no open or reload

### ISSUE THREAD

**Issue by KripaMishra** [zen-browser/desktop#2558] opened 2024-11-01 18:47 UTC
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

There is an option for tab unloading, the tabs that are unloaded, do not reload even if i try to open it. It can however be reopened if i create a duplicate of that tab and then try to open the new duplicate. 

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.16

### What platform are you seeing the problem on?

Windows

### Relevant log output

```shell
none
```

**Comment by uncompute** [comment] 2024-11-01 23:15
https://github.com/zen-browser/desktop/issues/2436

**Comment by LeMoonStar** [comment] 2024-11-01 23:22
This is a duplicate of #2436 and has been fixed in Zen 1.0.1-a.17
Please update to the latest version of Zen.

This issue will be closed as duplicate. Should you still experience issues, feel free to comment, re-open this issue or create a new one.

**Closed as not planned by LeMoonStar** 2024-11-01 23:22 UTC
Labels: Bug
