### ISSUE TITLE
Printing Preview rendering does not work.

### ISSUE THREAD

**Issue by GuafterCW** [zen-browser/desktop#3657] opened 2024-12-12 15:08 UTC
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Hey,

when I try to print a PDF-File and the preview has loaded, I get random symbols. 
If I actually print the page, the output is normal. 
Here's a screenshot:

![bug](https://github.com/user-attachments/assets/ff95d6b4-d897-4956-8933-5a6a11b59d15) 

Best regards,
Philipp

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.1 (Firefox 133.0)

### What platform are you seeing the problem on?

Windows

**Comment by signalno11** [comment] 2024-12-12 18:21
Works properly over on macOS for me.

**Comment by JSGRD22** [comment] 2024-12-17 13:38
Duplicate of https://github.com/zen-browser/desktop/issues/3238

**Comment by syscat29** [comment] 2024-12-17 14:35
Closing this, let's keep it all in one thread #3541

**Closed as completed by syscat29** 2024-12-17 14:35 UTC
Labels: Bug
