### ISSUE TITLE
Perfomance issue when scaling isn't 100% on KDE Plasma

### ISSUE THREAD

**Issue by Obamium69** [zen-browser/desktop#2160] opened 2024-10-16 11:02 UTC
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Hi there,

I'm currently experiencing some performance issues compared to Firefox. It is very noticeable for me when browsing Google Maps and moving the map around. It becomes quite stuttery, but when I use Firefox, there's almost no stutter. I tried enabling and disabling hardware acceleration, but this didn’t have any effect. I also tried the AppImage, Flatpak, and the AUR package, but all have the same issue. I noticed that when setting my scaling to 100% (I normally use 110%) everything is works fine

```

OS: EndeavourOS x86_64
Kernel: Linux 6.11.1-zen1-1-zen
DE: KDE Plasma 6.1.5 (Wayland)
CPU: i7-13700K
GPU: NVIDIA GeForce RTX 3080 12GB
RAM: 32GB
Display (Samsung Electronics Odyssey G93SC): 5120x1440 @ 240 Hz
Browser Version: 1.0.1-a.7
```
Zen-Browser

https://github.com/user-attachments/assets/b0bb3daf-b3d8-4ca1-8ac0-b4c78548af3e

Firefox

https://github.com/user-attachments/assets/db7d34fa-e85f-4d93-9a76-7deaafe54060

Zen-Browser 100% scaling
![grafik](https://github.com/user-attachments/assets/48acbc94-b91b-4cb8-85f9-5aad81b734b9)

Zen-Browser 110% scaling
![SAErT2z](https://github.com/user-attachments/assets/67367030-7641-4c38-b524-82fb2e5c5722)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.10 (64-Bit)

### What platform are you seeing the problem on?

Linux

**Comment by RayZ3R0** [comment] 2024-10-30 14:16
Does this still happen on latest version?

**Comment by Obamium69** [comment] 2024-10-30 15:13
@RayZ3R0 Tried it with 1.0.1-a.14 version and the issue is still there

**Comment by RayZ3R0** [comment] 2024-10-30 15:16
Alright we'll look into it

**Comment by StrongSand94191** [comment] 2024-11-04 19:11
Can you check if the issue still happens on 200% and 300% scaling

**Comment by Obamium69** [comment] 2024-11-04 19:43
@StrongSand94191 I tested 200% and 300% and the issue does not occur

**Comment by StrongSand94191** [comment] 2024-11-05 15:39
might be related to #2384

**Comment by RayZ3R0** [comment] 2024-11-07 16:45
Yup, duplicate of #2384 then it seems, will close this. Please move to that one

**Closed as completed by RayZ3R0** 2024-11-07 16:45 UTC

**Comment by Obamium69** [comment] 2025-01-02 20:52
Hi

 The issue #2384 was closed but this issue is still present. I checked that widget.wayland.fractional-scale.enabled is set to false.
