### ISSUE TITLE
Disabled right click menu on changing tab workspace

### ISSUE THREAD

**Issue by sndev28** [zen-browser/desktop#3083] opened 2024-11-18 07:13 UTC
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

On changing workspace of a tab, on going back to the previous workspace immediately, the right click menu on tabs doesn't open anymore. 

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.19 

### What platform are you seeing the problem on?

Windows

**Comment by m2x07** [comment] 2024-11-18 08:20
+1 on this. happens on linux too, installed using flatpak. version 1.0.1-a.19

for now I've been manually moving tabs

**Comment by thiemohaller** [comment] 2024-11-18 18:08
+1 on Windows as well, right clicking in the empty area under "New Tab" in the side menu fixes it temporarily, however, I haven't found a way to reliably replicate it yet?

**Comment by edgar-vincent** [comment] 2024-11-22 09:57
Duplicate of https://github.com/zen-browser/desktop/issues/2963, https://github.com/zen-browser/desktop/issues/2791, https://github.com/zen-browser/desktop/issues/2562, https://github.com/zen-browser/desktop/issues/2343

**Comment by neurokitti** [comment] 2024-12-21 22:22
thanks for reporting the bug! please check to see if its a repeat first though!

**Closed as completed by neurokitti** 2024-12-21 22:22 UTC
Labels: Bug

**Comment by neurokitti** [comment] 2024-12-21 22:27
this is a duplicate issue! Thanks for reporting the bug! please check to see if its a repeat first though!
