### ISSUE TITLE
top padding?

### ISSUE THREAD

**Issue by NOCanoa** [zen-browser/desktop#122] opened 2024-07-31 23:47 UTC
**Is your feature request related to a problem? Please describe.**
Could you remove the top padding ( top of the red box to the top off the screen), to put the X in the corner, I am always missing the X when I want to close fast xD
![image](https://github.com/user-attachments/assets/3cf0da9e-3891-46ad-a80f-477cac1766f8)
Win 11

**Comment by mauro-balades** [comment] 2024-08-02 13:05
Duplicate of #134, im gonna move it to there

**Closed by mauro-balades** 2024-08-02 13:05 UTC
Labels: bug, kind: enhancement
