### ISSUE TITLE
Private Window and Zen Sidebar conflict shortcuts

### ISSUE THREAD

**Issue by sound-friend** [zen-browser/desktop#516] opened 2024-08-23 16:52 UTC
### What happened?

It seems that the Private Window and Zen sidebar share the same shortcut (Ctrl+Shift+P), making it so you can't open a Private window via keyboard by default. I know it's a simple fix, but I wanted to see if the defaults can be fixed.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.27

### Severity impact

Low

### What platform are you seeing the problem on?

Linux

**Comment by anatasiajp** [comment] 2024-08-23 17:28
Should be easy to fix but we need to find a new shortcut for Sidebar, there's not so many ctrl+shift combo left.

How about Alt+p ?

**Comment by sound-friend** [comment] 2024-08-23 18:57
That can work, but what about changing the private window shortcut? Maybe
matching with chromes with Ctrl+shit+N (unless that's used for something
else)

**Comment by gunir** [comment] 2024-08-24 00:49
> That can work, but what about changing the private window shortcut? Maybe matching with chromes with Ctrl+shit+N (unless that's used for something else)

I don't think that's a good idea, this shortcut has become the standard, all web browsers use it at this point and there'll be users who complain.

**Comment by sound-friend** [comment] 2024-08-24 00:56
ive seen all chromium based browsers use ctrl+shift+n, but i may be
incorrect. it's been a while since i was one chrome

**Comment by gunir** [comment] 2024-08-24 01:47
> ive seen all chromium based browsers use ctrl+shift+n, but i may be incorrect. it's been a while since i was one chrome

Anyway, the Private Browsing keyboard shortcut can be changed in Customizable shortcut, a Zen feature.

**Comment by alebcay** [comment] 2024-08-24 03:14
For what it's worth, by default Firefox uses <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>N</kbd> (or equivalent on macOS) for reopen last window. So moving to use that combo for private browsing would leave reopen last window without a shortcut.

**Comment by gunir** [comment] 2024-08-24 03:32
Yeah, the issue is as https://github.com/zen-browser/desktop/issues/516#issuecomment-2307515257 mentioned, Ctrl+Shift+`?` are mostly used by Gecko, need to really think about something else to not overlapped.

**Comment by mauro-balades** [comment] 2024-08-24 13:18
Fixed 👍🏽 
https://github.com/zen-browser/components/pull/2

**Closed by mauro-balades** 2024-08-24 13:18 UTC
Labels: kind: low severity
