### ISSUE TITLE
 Can't open the browser on Fedora KDE 

### ISSUE THREAD

**Issue by MW-J97** [zen-browser/desktop#1937] opened 2024-10-06 20:35 UTC
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

 Hi there,

I have just installed Fedora with KDE and installed Zen from Flathub. But, when I run it, it keeps spinning and doesn't load. It opens when I open it from terminal. https://imgur.com/a/GGpfJbv

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.7

### What platform are you seeing the problem on?

Linux

**Comment by bhaumik-tripathi** [comment] 2024-10-07 04:00
Please check if flatpak is setup properly,(means if other flatpak apps are working,it should be setup properly), since you mentioned that you have just installed it, there can be the most likely error in it.

If everything is fine please run the application from terminal with the command
```
flatpak run --verbose io.github.zen_browser.zen
```
**Note** that you would need to exit the program with `ctrl+c` if it doesn't shows the prompt again/stops by itself after some time. I insist again to check flatpak config before running it from [here](https://flathub.org/setup/Fedora).

**Comment by MW-J97** [comment] 2024-10-08 08:24
@bhaumik-tripathi 
> Please check if flatpak is setup properly,(means if other flatpak apps are working,it should be setup properly), since you mentioned that you have just installed it, there can be the most likely error in it.

I uninstalled Flatpak from discover and reinstalled it from the link above. It worked fine ,but just for the first time and after that it doesn't respond as the same issue. 



> `flatpak run --verbose io.github.zen_browser.zen`

`flatpak run --verbose io.github.zen_browser.zen
F: No installations directory in /etc/flatpak/installations.d. Skipping
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/minawaheed/.local/share/flatpak
F: Opening user flatpak installation at path /home/minawaheed/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Skipping parental controls check for app/io.github.zen_browser.zen/x86_64/stable since parental controls are disabled globally
F: Opening user flatpak installation at path /home/minawaheed/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: /var/lib/flatpak/runtime/org.freedesktop.Platform/x86_64/23.08/cb2bd72f6b227a6ef91c194b21880d95bee4e198c4ab7cb0fa7bea30649338ae/files/lib32 does not exist
F: Cleaning up unused container id 1174233756
F: Cleaning up per-app-ID state for io.github.zen_browser.zen
F: Allocated instance id 3544621436
F: Add defaults in dir /io/github/zen_browser/zen/
F: Add locks in dir /io/github/zen_browser/zen/
F: Allowing wayland access
F: Allowing pulseaudio access
F: Pulseaudio user configuration file '/home/minawaheed/.config/pulse/client.conf': Error opening file /home/minawaheed/.config/pulse/client.conf: No such file or directory
F: CUPS configuration file '/home/minawaheed/.cups/client.conf': Error opening file /home/minawaheed/.cups/client.conf: No such file or directory
F: Running '/usr/bin/bwrap --args 39 -- /usr/bin/xdg-dbus-proxy --args=43'
F: Running '/usr/bin/bwrap --args 41 -- launch-script.sh'
Warning: ConnectToCompositor() try again : Resource temporarily unavailable
Warning: ConnectToCompositor() try again : Resource temporarily unavailable
Warning: ConnectToCompositor() try again : Resource temporarily unavailable
Warning: ConnectToCompositor() try again : Resource temporarily unavailable
Warning: ConnectToCompositor() try again : Resource temporarily unavailable
Warning: ConnectToCompositor() try again : Resource temporarily unavailable
Warning: ConnectToCompositor() try again : Resource temporarily unavailable
Warning: ConnectToCompositor() try again : Resource temporarily unavailable
Warning: ConnectToCompositor() try again : Resource temporarily unavailable
Warning: ConnectToCompositor() try again : Resource temporarily unavailable
Warning: ConnectToCompositor() try again : Resource temporarily unavailable
Warning: ConnectToCompositor() try again : Resource temporarily unavailable
Warning: ConnectToCompositor() try again : Resource temporarily unavailable
Warning: ConnectToCompositor() try again : Resource temporarily unavailable
Warning: ConnectToCompositor() try again : Resource temporarily unavailable
Warning: ConnectToCompositor() try again : Resource temporarily unavailable
Warning: ConnectToCompositor() try again : Resource temporarily unavailable
Warning: ConnectToCompositor() try again : Resource temporarily unavailable
Warning: ConnectToCompositor() try again : Resource temporarily unavailable
Warning: ConnectToCompositor() try again : Resource temporarily unavailable
Warning: ConnectToCompositor() try again : Resource temporarily unavailable
Warning: ConnectToCompositor() try again : Resource temporarily unavailable
Warning: ConnectToCompositor() try again : Resource temporarily unavailable
Warning: ConnectToCompositor() try again : Resource temporarily unavailable
Warning: ConnectToCompositor() try again : Resource temporarily unavailable
Warning: ConnectToCompositor() try again : Resource temporarily unavailable
Warning: ConnectToCompositor() try again : Resource temporarily unavailable
Warning: ConnectToCompositor() try again : Resource temporarily unavailable
Warning: ConnectToCompositor() try again : Resource temporarily unavailable
Warning: ConnectToCompositor() try again : Resource temporarily unavailable
Warning: ConnectToCompositor() try again : Resource temporarily unavailable
Warning: ConnectToCompositor() try again : Resource temporarily unavailable
Warning: ConnectToCompositor() try again : Resource temporarily unavailable
Warning: ConnectToCompositor() try again : Resource temporarily unavailable
Warning: ConnectToCompositor() try again : Resource temporarily unavailable
Warning: ConnectToCompositor() try again : Resource temporarily unavailable
Warning: ConnectToCompositor() try again : Resource temporarily unavailable
Warning: ConnectToCompositor() try again : Resource temporarily unavailable
Warning: ConnectToCompositor() try again : Resource temporarily unavailable
Warning: ConnectToCompositor() try again : Resource temporarily unavailable
Warning: ConnectToCompositor() try again : Resource temporarily unavailable
Warning: ConnectToCompositor() try again : Resource temporarily unavailable
Warning: ConnectToCompositor() try again : Resource temporarily unavailable
Warning: ConnectToCompositor() try again : Resource temporarily unavailable
Warning: ConnectToCompositor() try again : Resource temporarily unavailable
Warning: ConnectToCompositor() try again : Resource temporarily unavailable
Warning: ConnectToCompositor() try again : Resource temporarily unavailable
Warning: ConnectToCompositor() try again : Resource temporarily unavailable
Warning: ConnectToCompositor() try again : Resource temporarily unavailable
Warning: ConnectToCompositor() try again : Resource temporarily unavailable
Warning: ConnectToCompositor() try again : Resource temporarily unavailable
Warning: ConnectToCompositor() try again : Resource temporarily unavailable
Warning: ConnectToCompositor() try again : Resource temporarily unavailable
Warning: ConnectToCompositor() try again : Resource temporarily unavailable
Warning: ConnectToCompositor() try again : Resource temporarily unavailable
Warning: ConnectToCompositor() try again : Resource temporarily unavailable
Warning: ConnectToCompositor() try again : Resource temporarily unavailable
Warning: ConnectToCompositor() try again : Resource temporarily unavailable
Warning: ConnectToCompositor() try again : Resource temporarily unavailable
Warning: ConnectToCompositor() try again : Resource temporarily unavailable
Warning: ConnectToCompositor() try again : Resource temporarily unavailable
Warning: ConnectToCompositor() try again : Resource temporarily unavailable
Warning: ConnectToCompositor() try again : Resource temporarily unavailable
Warning: ConnectToCompositor() try again : Resource temporarily unavailable
Warning: ConnectToCompositor() try again : Resource temporarily unavailable
Warning: ConnectToCompositor() try again : Resource temporarily unavailable
Warning: ConnectToCompositor() try again : Resource temporarily unavailable
Warning: ConnectToCompositor() try again : Resource temporarily unavailable
Warning: ConnectToCompositor() try again : Resource temporarily unavailable
Warning: ConnectToCompositor() try again : Resource temporarily unavailable
Warning: ConnectToCompositor() try again : Resource temporarily unavailable
Warning: ConnectToCompositor() try again : Resource temporarily unavailable
Warning: ConnectToCompositor() try again : Resource temporarily unavailable
Warning: ConnectToCompositor() try again : Resource temporarily unavailable
Warning: ConnectToCompositor() try again : Resource temporarily unavailable
Warning: ConnectToCompositor() try again : Resource temporarily unavailable
Warning: ConnectToCompositor() try again : Resource temporarily unavailable
Warning: ConnectToCompositor() try again : Resource temporarily unavailable
Warning: ConnectToCompositor() try again : Resource temporarily unavailable
Warning: ConnectToCompositor() try again : Resource temporarily unavailable
Warning: ConnectToCompositor() try again : Resource temporarily unavailable
Warning: ConnectToCompositor() try again : Resource temporarily unavailable
Warning: ConnectToCompositor() try again : Resource temporarily unavailable
Warning: ConnectToCompositor() try again : Resource temporarily unavailable
Warning: ConnectToCompositor() try again : Resource temporarily unavailable
Warning: ConnectToCompositor() try again : Resource temporarily unavailable
Warning: ConnectToCompositor() try again : Resource temporarily unavailable
Warning: ConnectToCompositor() try again : Resource temporarily unavailable
Warning: ConnectToCompositor() try again : Resource temporarily unavailable
Warning: ConnectToCompositor() try again : Resource temporarily unavailable
Warning: ConnectToCompositor() try again : Resource temporarily unavailable
Warning: ConnectToCompositor() try again : Resource temporarily unavailable
Warning: ConnectToCompositor() try again : Resource temporarily unavailable
Warning: ConnectToCompositor() try again : Resource temporarily unavailable
Warning: ConnectToCompositor() try again : Resource temporarily unavailable
Warning: ConnectToCompositor() try again : Resource temporarily unavailable
Warning: ConnectToCompositor() try again : Resource temporarily unavailable
Warning: ConnectToCompositor() try again : Resource temporarily unavailable

`

**Comment by bhaumik-tripathi** [comment] 2024-10-09 11:47
I don't use KDE, hence I can't reproduce the error on my end, maybe someone else with KDE can dig better, but some internet rolling showed that there seems to be some common issue with KDE fedora and firefox derivatives. There is an open issue for Floorp(another firefox derivative) mentioning the same issue and specification as yours ([ref](https://github.com/Floorp-Projects/Floorp/issues/1452), [old ref](https://bugzilla.redhat.com/show_bug.cgi?id=2262959) ).

Somehow I don't like flatpak, had some resource and memory issues before. I use an **unofficial** build from copr, you can try that as an alternative(**But make sure you trust it.**){I do trust it :) }. You can view it [here ](https://copr.fedorainfracloud.org/coprs/sneexy/zen-browser/)
```
sudo dnf copr enable sneexy/zen-browser
sudo dnf install zen-browser
```

**Comment by RealDishwash** [comment] 2024-10-24 00:24
I'm on fedora kde and can confirm that flatpak zen works fine for me

**Comment by MW-J97** [comment] 2024-10-25 15:03
> I'm on fedora kde and can confirm that flatpak zen works fine for me

@RealVishy  Thanks for replying. 
So, what can be the issue? 
Or is there any update happened that fixed the issue?

**Comment by RayZ3R0** [comment] 2024-10-30 15:46
@MW-J97 can you try reinstalling the latest update and see if it still happens

**Comment by MW-J97** [comment] 2024-10-31 08:46
> @MW-J97 can you try reinstalling the latest update and see if it still happens

Thanks for replying. 
It took a lot of time to install it, but it's working now. I'll try it and give feedback if the error came back again.

**Comment by RayZ3R0** [comment] 2024-10-31 14:56
Alright, will close this issue for now then. Reopen if it still happens please, thank you

**Closed by RayZ3R0** 2024-10-31 14:56 UTC
