### ISSUE TITLE
Tab unloaded can not be load again

### ISSUE THREAD

**Issue by tanphat1102** [zen-browser/desktop#2472] opened 2024-10-31 13:58 UTC
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

When tab unloaded, I can not access again.
https://github.com/user-attachments/assets/8b6b61bb-9f31-431b-b65b-901e702643c3

### Reproducible?

- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.16 (64-bit)

### What platform are you seeing the problem on?

Windows

**Comment by Slinet6056** [comment] 2024-10-31 14:03
I have the same problem. When I leave for a while, the entire browser will freeze and I cannot open any page. I have to restart the browser.

**Comment by sunba23** [comment] 2024-10-31 14:14
check #2436

**Comment by StepanAsk** [comment] 2024-10-31 14:14
> I have the same problem. When I leave for a while, the entire browser will freeze and I cannot open any page. I have to restart the browser.

Same issue

**Comment by 12th-devs** [comment] 2024-10-31 14:17
This seems to be a bug with a.16/a.15 It is not the browser itself freezing up, but the unloaded tabs, for whatever reason unloaded tabs are unable to be opened and basically are completely static and have no visual indication on click. You can change the time it takes to unload a tab to 9999 in the settings as a temporary fix, you will just need to stay on-top of closing your tabs frequently to prevent high ram usage. Hope this can help

**Comment by RayZ3R0** [comment] 2024-10-31 14:42
Duplicate of #2436 it is caused by unloaded tabs. It will be fixed in the next update

**Closed as completed by RayZ3R0** 2024-10-31 14:42 UTC
