### ISSUE TITLE
Sidebar Position Issue in Compact Mode

### ISSUE THREAD

**Issue by pSwaqtch** [zen-browser/desktop#895] opened 2024-08-26 11:00 UTC
### What happened?

I am experiencing an issue with the sidebar position in Zen Browser when using compact mode. Despite configuring the sidebar to appear on the right side, it continues to show up on the left side.

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.28

### Severity impact

Medium

### What platform are you seeing the problem on?

Linux

**Comment by ch4og** [comment] 2024-08-26 11:08
duplicate of https://github.com/zen-browser/desktop/issues/632

**Closed** 2024-08-26 11:58 UTC
Labels: kind: medium severity
