### ISSUE TITLE
Pinned tabs in a workspace create a blank space between the end of the tab scroll region and the workspace buttons in another workspace with fewer tabs

### ISSUE THREAD

**Issue by gbrlbrbs** [zen-browser/desktop#2592] opened 2024-11-03 01:33 UTC
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

When you change between a workspace that has multiple pinned tabs to another that has less/no pinned tabs, a blank space is created between the end of the scrollable region of tabs and the workspace buttons.

![Workspace with a lot of pinned tabs, no blank space between the tab scroll region and the workspace buttons](https://github.com/user-attachments/assets/b0c9b033-5925-4887-a1f7-ebaae2bceba9)

![Workspace with fewer pinned tabs, notice the space between the end of the scrollable region and the workspace buttons](https://github.com/user-attachments/assets/4ff5dd49-a040-4cc0-a6e4-beeb16783182)

The space exactly matches the difference in pinned tabs:

![When the number of pinned tabs is the same, the space is gone](https://github.com/user-attachments/assets/aad46974-cc43-4f1a-81c5-ac3438d9c195)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.17 Flatpak on NixOS

### What platform are you seeing the problem on?

Linux

**Comment by salamijason** [comment] 2024-11-10 17:28
Hey I'm having trouble understanding what you mean. Could you send a screen recording? Thank you!

**Comment by gbrlbrbs** [comment] 2024-11-10 18:39
Hi! Here is a screen recording with the behavior I tried to describe with the pictures.

[Screencast_20241110_153516.webm](https://github.com/user-attachments/assets/842cdd7c-3e84-4174-b963-1aa151afa2e8)

**Comment by salamijason** [comment] 2024-11-16 12:43
Oh what that's real bizarre. Could you try it on the latest version? (a19 of this comment) As soon as you confirm this bug still happens, I'll send it off as a bug.

**Comment by gbrlbrbs** [comment] 2024-11-17 17:54
Still happens with pinned tabs. Using Essentials is a workaround since they appear in every workspace.

**Comment by gbrlbrbs** [comment] 2024-11-17 17:58
Related: #2848

**Comment by Truleu** [comment] 2024-11-19 11:11
I have this problem as well. When I open Zen in the first workspace there's no blank space but if I switch to the workspace with pinned tabs and come back to previous workspace the blank space shows up and seems to be the exact size of the pinned tabs section in the other workspace

**Comment by salamijason** [comment] 2024-11-23 10:49
Was able to recreate this on a.19 (windows). thank you all for your input!

**Comment by mr-cheffy** [comment] 2024-12-21 19:36
This should be fixed now, can anyone confirm?

**Comment by mr-cheffy** [comment] 2024-12-22 09:14
Im closing this as fixed as I cant reproduce it anymore, if it still persists, please let me know 👍🏽

**Closed as completed by mr-cheffy** 2024-12-22 09:14 UTC
