### ISSUE TITLE
cmd + F is making browser fullscreen instead of search in page

### ISSUE THREAD

**Issue by heyrmi** [zen-browser/desktop#1672] opened 2024-09-24 06:17 UTC
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

cmd + F is making browser fullscreen instead of search in page

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.4

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by HarryHeres** [comment] 2024-09-24 06:39
Duplicate of [https://github.com/zen-browser/desktop/issues/1629](https://github.com/zen-browser/desktop/issues/1629)

**Closed** 2024-09-24 06:40 UTC
