### ISSUE TITLE
Font Rendering on Google Sheets

### ISSUE THREAD

**Issue by MikeLBN** [zen-browser/desktop#3268] opened 2024-11-28 14:16 UTC
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Font of content of Google Sheet is rendering funky
![Screenshot 2024-11-28 at 13-11-29 Allegro Autosvit - Google Sheets](https://github.com/user-attachments/assets/95ef11b8-bd5a-4a72-82a1-8f20d696a95f)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.21

### What platform are you seeing the problem on?

Windows

**Comment by gnc-07** [comment] 2024-12-11 04:28
Hello, is this still happening on the latest version of Zen (1.0.2-b.0)? Also, if it is still occurring, does it happen in Google Docs as well? A similar issue was reported with Google Docs #3541.

**Comment by MikeLBN** [comment] 2024-12-11 20:30
Hi. It's still an issue, on Docs as well, and on every version since alpha 20 (except alpha 22, which was rollback to a 19)

**Comment by JSGRD22** [comment] 2024-12-17 13:40
Duplicate of https://github.com/zen-browser/desktop/issues/3238 (same underlying bug)

**Comment by syscat29** [comment] 2024-12-17 14:36
Closing this, let's keep it all in one thread #3541

**Closed as completed by syscat29** 2024-12-17 14:36 UTC
