### ISSUE TITLE
TAB-BAR/TOOLBAR ISSUE

### ISSUE THREAD

**Issue by dhruvvk2326** [zen-browser/desktop#584] opened 2024-08-24 14:16 UTC
### What happened?

When in compact mode  the toolbar comes very early even if i am not hovering to the left side of the page like it comes very early . eg- you cant hover the starting of a video timeline in youtube , it will pop up the tab bar. 
Also sometimes the tab--bar is sort of transparent but when i click it it comes back to normal .
![Screenshot 2024-08-24 190153](https://github.com/user-attachments/assets/19a10d8c-2c30-4198-8fc0-c33fb333bc9d)
.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.28

### Severity impact

Enhancement

### What platform are you seeing the problem on?

Windows

**Comment by kLabz** [comment] 2024-08-24 14:40
Same as #549 (see comment for a workaround); not sure what the transparency issue is about, though.

**Comment by Moshyfawn** [comment] 2024-08-24 15:06
The hover area issue is a duplicate of #520 and is fixed for the next release.

**Closed** 2024-08-24 15:06 UTC
Labels: kind: enhancement

**Comment by ulrichSchreiner** [comment] 2024-08-29 14:04
On linux the transparency happens when the browser is not the active window but you hover with the mouse. for example: open multiple tabs, switch to a terminal window in your linux desktop and then hover the tab-icons of zen-browser but let the terminal be the active window. now then panel is transparent.
