### ISSUE TITLE
Opening Find makes the whole web content jump

### ISSUE THREAD

**Issue by wysh3** [zen-browser/desktop#2594] opened 2024-11-03 04:07 UTC
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

opening find causing this weird thing where the whole ui jumps

https://github.com/user-attachments/assets/5514aa19-fbe5-44d0-9f7b-3e81cc59a713

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.17

### What platform are you seeing the problem on?

Linux

**Comment by MrMati** [comment] 2024-11-03 09:38
This is caused by a commit d228a96944e515dc8d6b4fd8ed2cb515f7e1e109 which added:
https://github.com/zen-browser/desktop/blob/24a6013195f7a5aa90c4c49e2160d8de253c1646/src/browser/base/content/zen-styles/zen-browser-ui.css#L79

**Comment by wysh3** [comment] 2024-12-06 16:11
This issue is still occuring in a.22 and t.22 build

**Comment by mr-cheffy** [comment] 2024-12-22 13:55
I cant reproduce anymore, ill close this issue. Please let me know if the issue persists

**Closed as completed by mr-cheffy** 2024-12-22 13:55 UTC
Labels: Bug
