### ISSUE TITLE
About Search engines

### ISSUE THREAD

**Issue by WHMyyds** [zen-browser/desktop#1584] opened 2024-09-21 13:54 UTC
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

![图片](https://github.com/user-attachments/assets/a02aecd0-ad8f-411f-9151-83dfe723e2d7)
As you can see,there's no bing search in the choices
Though i know Mozilla is to blame for this,i think you can fix it 

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1 a2

### What platform are you seeing the problem on?

Windows

**Comment by n7itro** [comment] 2024-09-21 14:49
You can still manually add Bing in the settings. Duplicate of #1147

**Closed by n7itro** 2024-09-21 14:49 UTC

**Comment by WHMyyds** [comment] 2024-09-21 15:59
sorry for interurpt you
