### ISSUE TITLE
No keyboard shortcuts displayed for customization on Mac Sonoma

### ISSUE THREAD

**Issue by cmcallister** [zen-browser/desktop#2136] opened 2024-10-15 16:13 UTC
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Host: MacBook Pro (14-inch, Nov 2023, Three Thunderbolt 4 ports)
OS: macOS Sonoma 14.6.1 x86_64
Kernel: Darwin 23.6.0

I updated Zen via the About Zen window. Upon restart I was presented with a non-functional app, so I reinstalled. While setting up this new install I navigate to `about:preferences#zenCKS` and am presented with only the page's descriptive text box that includes the **Reset to Default** button (see linked screen capture)

[linked screen capture](https://imgur.com/a/hAmNSBT)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.9 

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by sjclayton** [comment] 2024-10-15 16:46
Duplicate of #2111, Related #2118, #2131

This can be closed,  fixed in next update (a.10)

**Closed as completed** 2024-10-15 18:22 UTC
