### ISSUE TITLE
Taking Screenshot in compact mode opens tab list

### ISSUE THREAD

**Issue by GodPuffin** [zen-browser/desktop#1653] opened 2024-09-23 21:07 UTC
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

When in compact mode with the hidden tabs, taking a firefox screenshot (Ctrl+Shift+S) opens the tabs list. This does not feel necessarily intentional.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.3

### What platform are you seeing the problem on?

Windows

**Comment by RayZ3R0** [comment] 2024-10-30 15:55
Cannot reproduce. Does this still happen on latest version? (a.14 as of this comment)

**Comment by RayZ3R0** [comment] 2024-10-30 15:56
Yeah it does do that, but if you take the screenshot, it only screenshots the webpage. But yeah this is still awkward, will move this up

**Comment by RayZ3R0** [comment] 2024-10-30 18:31
Duplicate of [#917](https://github.com/zen-browser/desktop/issues/917) Moving there

**Closed by RayZ3R0** 2024-10-30 18:31 UTC
