### ISSUE TITLE
Full-screen videos are not quite in full-screen and have slightly rounded corners

### ISSUE THREAD

**Issue by AlphaCraft9658** [zen-browser/desktop#1999] opened 2024-10-10 16:54 UTC
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

I was just playing YouTube videos in full-screen, when I noticed that there is a slight gap in each corner. All the corners are slightly rounded, even in full-screen. Usually, those corners should also be filled by the played video. This is a minor bug, but it's hard to unsee. I have also disabled any installed Zen mods to make sure it's not caused by any of those and it is something caused by Zen itself.

Here is an image of the top-left corner. You have to zoom in to really see it, but it's there:
![grafik](https://github.com/user-attachments/assets/80ea1863-65bc-4bf8-9aa9-ff22a0008b66)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.7

### What platform are you seeing the problem on?

Linux

**Comment by RayZ3R0** [comment] 2024-10-30 14:19
Cannot reproduce this. Does this still happen in latest version?

**Comment by BigEnding-8347** [comment] 2024-11-01 14:46
This may be related to Zen Mods being active on your end, as I have the same issue.

Update: I have now found the mod that is responsible, it is the SuperGradient v1.2.1 for me. I think the developer of the mod will be the one who has to fix it. Maybe you and others who are affected should check this, if it is the same one for them.

Update 2: Also just found out, that since Zen has built-in gradients now, the mod is not required anymore and should be uninstalled anyways. The built in feature seems exactly the same, but easier to use as well.

**Comment by RayZ3R0** [comment] 2024-11-02 10:07
Yeah it should be fixed by now. Will be closing the issue. Please reopen if it still happens

**Closed by RayZ3R0** 2024-11-02 10:07 UTC

**Comment by AlphaCraft9658** [comment] 2024-11-14 09:41
> This may be related to Zen Mods being active on your end, as I have the same issue.
> 
> Update: I have now found the mod that is responsible, it is the SuperGradient v1.2.1 for me. I think the developer of the mod will be the one who has to fix it. Maybe you and others who are affected should check this, if it is the same one for them.
> 
> Update 2: Also just found out, that since Zen has built-in gradients now, the mod is not required anymore and should be uninstalled anyways. The built in feature seems exactly the same, but easier to use as well.

It looks like the gradient mod caused the issue. It's not even available anymore. I'm going to try the built-in gradient feature.
