### ISSUE TITLE
New tab's "最近のアクティビティ" is not work.

### ISSUE THREAD

**Issue by array** [zen-browser/desktop#2108] opened 2024-10-15 06:58 UTC
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

1.0.1-a9で、新しいタブの”最近のアクティビティ’が表示されません。また設定の画面でもチェックがオンにならない状況です。

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a9

### What platform are you seeing the problem on?

Windows

**Comment by RayZ3R0** [comment] 2024-10-30 06:50
Hello, can you specify more, in English if possible

**Comment by krisMG21** [comment] 2024-11-03 00:02
>New tab's "Recent Activity" is not working.
>The "Recent Activity" option is not displayed in the new tab, and it cannot be checked in the settings screen.

I guess they are talking about the following option:
![Image](https://github.com/user-attachments/assets/a4b821c0-2540-415d-baea-418f00459f49)

I don't know if the problem is, they check it, tab doesn't show and the option is unchecked the next time,
or it is not checked and expected to work xD.

**Comment by krisMG21** [comment] 2024-11-03 00:03
Oh, but it's not a tab, it's the recent activity, that it's shown in the homepage.
Current version on Windows 10, working for me

![Image](https://github.com/user-attachments/assets/481dc37e-3ced-4c8d-9d9a-af181ae018e7)

**Comment by salamijason** [comment] 2024-11-03 09:55
Looks like the author hasn't responded and diff user has shown it working, will be closing this issue. Please reopen if anyone is still facing this issue.

**Closed as completed by salamijason** 2024-11-03 09:55 UTC
