### ISSUE TITLE
Pin Extension: Icon offset

### ISSUE THREAD

**Issue by ThibautPV** [zen-browser/desktop#452] opened 2024-08-22 18:32 UTC
### What happened?

Small display problem with the icon when you want to pin an extension
<img width="437" alt="Capture d’écran 2024-08-22 à 20 28 10" src="https://github.com/user-attachments/assets/167038f0-d5b0-41f7-a1b8-212c237250f5">

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.27

### Severity impact

Low

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by jimfr** [comment] 2024-08-22 19:12
This is a duplicate of https://github.com/zen-browser/desktop/issues/177 and https://github.com/zen-browser/desktop/issues/248 and has been marked as fixed in the upcoming release.

**Closed** 2024-08-22 19:17 UTC
Labels: kind: low severity

**Comment by ThibautPV** [comment] 2024-08-22 19:43
Sorry...
Thank you
